/* THIS FILE GENERATED BY bcd.gen */
module bcd.libxml2.xmlreader;
align(4):
public import bcd.libxml2.xmlschemas;
public import bcd.libxml2.relaxng;
public import bcd.libxml2.threads;
public import bcd.libxml2.globals;
public import bcd.libxml2.SAX2;
public import bcd.libxml2.SAX;
public import bcd.libxml2.xlink;
public import bcd.libxml2.parser;
public import bcd.libxml2.xmlIO;
public import bcd.libxml2.encoding;
public import bcd.libxml2.entities;
public import bcd.libxml2.hash;
public import bcd.libxml2.valid;
public import bcd.libxml2.xmlautomata;
public import bcd.libxml2.list;
public import bcd.libxml2.xmlerror;
public import bcd.libxml2.xmlmemory;
public import bcd.libxml2.tree;
public import bcd.libxml2.xmlregexp;
public import bcd.libxml2.dict;
public import bcd.libxml2.xmlstring;
public import bcd.libxml2.xmlversion;
enum xmlParserSeverities {
XML_PARSER_SEVERITY_VALIDITY_WARNING=1,
XML_PARSER_SEVERITY_VALIDITY_ERROR=2,
XML_PARSER_SEVERITY_WARNING=3,
XML_PARSER_SEVERITY_ERROR=4,
}
alias void function(void *, char *, int, void *) _BCD_func__1822;
alias _BCD_func__1822 xmlTextReaderErrorFunc;
alias void * xmlTextReaderLocatorPtr;
alias void xmlTextReader;
alias void * xmlTextReaderPtr;
enum xmlReaderTypes {
XML_READER_TYPE_NONE=0,
XML_READER_TYPE_ELEMENT=1,
XML_READER_TYPE_ATTRIBUTE=2,
XML_READER_TYPE_TEXT=3,
XML_READER_TYPE_CDATA=4,
XML_READER_TYPE_ENTITY_REFERENCE=5,
XML_READER_TYPE_ENTITY=6,
XML_READER_TYPE_PROCESSING_INSTRUCTION=7,
XML_READER_TYPE_COMMENT=8,
XML_READER_TYPE_DOCUMENT=9,
XML_READER_TYPE_DOCUMENT_TYPE=10,
XML_READER_TYPE_DOCUMENT_FRAGMENT=11,
XML_READER_TYPE_NOTATION=12,
XML_READER_TYPE_WHITESPACE=13,
XML_READER_TYPE_SIGNIFICANT_WHITESPACE=14,
XML_READER_TYPE_END_ELEMENT=15,
XML_READER_TYPE_END_ENTITY=16,
XML_READER_TYPE_XML_DECLARATION=17,
}
enum xmlParserProperties {
XML_PARSER_LOADDTD=1,
XML_PARSER_DEFAULTATTRS=2,
XML_PARSER_VALIDATE=3,
XML_PARSER_SUBST_ENTITIES=4,
}
enum xmlTextReaderMode {
XML_TEXTREADER_MODE_INITIAL=0,
XML_TEXTREADER_MODE_INTERACTIVE=1,
XML_TEXTREADER_MODE_ERROR=2,
XML_TEXTREADER_MODE_EOF=3,
XML_TEXTREADER_MODE_CLOSED=4,
XML_TEXTREADER_MODE_READING=5,
}
extern (C) void xmlTextReaderGetErrorHandler(void *, _BCD_func__1822 *, void * *);
alias void function(void *, _xmlError *) _BCD_func__2147;
extern (C) void xmlTextReaderSetStructuredErrorHandler(void *, _BCD_func__2147, void *);
extern (C) void xmlTextReaderSetErrorHandler(void *, _BCD_func__1822, void *);
extern (C) char * xmlTextReaderLocatorBaseURI(void *);
extern (C) int xmlTextReaderLocatorLineNumber(void *);
alias int function(void *, char *, int) _BCD_func__2056;
alias int function(void *) _BCD_func__1572;
extern (C) int xmlReaderNewIO(void *, _BCD_func__2056, _BCD_func__1572, void *, char *, char *, int);
extern (C) int xmlReaderNewFd(void *, int, char *, char *, int);
extern (C) int xmlReaderNewMemory(void *, char *, int, char *, char *, int);
extern (C) int xmlReaderNewFile(void *, char *, char *, int);
extern (C) int xmlReaderNewDoc(void *, char *, char *, char *, int);
extern (C) int xmlReaderNewWalker(void *, _xmlDoc *);
extern (C) void * xmlReaderForIO(_BCD_func__2056, _BCD_func__1572, void *, char *, char *, int);
extern (C) void * xmlReaderForFd(int, char *, char *, int);
extern (C) void * xmlReaderForMemory(char *, int, char *, char *, int);
extern (C) void * xmlReaderForFile(char *, char *, int);
extern (C) void * xmlReaderForDoc(char *, char *, char *, int);
extern (C) void * xmlReaderWalker(_xmlDoc *);
extern (C) int xmlTextReaderByteConsumed(void *);
extern (C) int xmlTextReaderStandalone(void *);
extern (C) char * xmlTextReaderConstXmlVersion(void *);
extern (C) int xmlTextReaderSetSchema(void *, void *);
extern (C) int xmlTextReaderSchemaValidate(void *, char *);
extern (C) int xmlTextReaderRelaxNGSetSchema(void *, void *);
extern (C) int xmlTextReaderRelaxNGValidate(void *, char *);
extern (C) int xmlTextReaderIsValid(void *);
extern (C) int xmlTextReaderNextSibling(void *);
extern (C) int xmlTextReaderNext(void *);
extern (C) _xmlNode * xmlTextReaderExpand(void *);
extern (C) _xmlDoc * xmlTextReaderCurrentDoc(void *);
extern (C) int xmlTextReaderPreservePattern(void *, char *, char * *);
extern (C) _xmlNode * xmlTextReaderPreserve(void *);
extern (C) int xmlTextReaderGetParserColumnNumber(void *);
extern (C) int xmlTextReaderGetParserLineNumber(void *);
extern (C) _xmlNode * xmlTextReaderCurrentNode(void *);
extern (C) int xmlTextReaderGetParserProp(void *, int);
extern (C) int xmlTextReaderSetParserProp(void *, int, int);
extern (C) char * xmlTextReaderConstEncoding(void *);
extern (C) int xmlTextReaderNormalization(void *);
extern (C) int xmlTextReaderMoveToElement(void *);
extern (C) int xmlTextReaderMoveToNextAttribute(void *);
extern (C) int xmlTextReaderMoveToFirstAttribute(void *);
extern (C) int xmlTextReaderMoveToAttributeNs(void *, char *, char *);
extern (C) int xmlTextReaderMoveToAttribute(void *, char *);
extern (C) int xmlTextReaderMoveToAttributeNo(void *, int);
extern (C) char * xmlTextReaderLookupNamespace(void *, char *);
extern (C) _xmlParserInputBuffer * xmlTextReaderGetRemainder(void *);
extern (C) char * xmlTextReaderGetAttributeNs(void *, char *, char *);
extern (C) char * xmlTextReaderGetAttribute(void *, char *);
extern (C) char * xmlTextReaderGetAttributeNo(void *, int);
extern (C) int xmlTextReaderClose(void *);
extern (C) char * xmlTextReaderValue(void *);
extern (C) char * xmlTextReaderXmlLang(void *);
extern (C) char * xmlTextReaderPrefix(void *);
extern (C) char * xmlTextReaderNamespaceUri(void *);
extern (C) char * xmlTextReaderName(void *);
extern (C) char * xmlTextReaderLocalName(void *);
extern (C) char * xmlTextReaderBaseUri(void *);
extern (C) char * xmlTextReaderConstValue(void *);
extern (C) char * xmlTextReaderConstString(void *, char *);
extern (C) char * xmlTextReaderConstXmlLang(void *);
extern (C) char * xmlTextReaderConstPrefix(void *);
extern (C) char * xmlTextReaderConstNamespaceUri(void *);
extern (C) char * xmlTextReaderConstName(void *);
extern (C) char * xmlTextReaderConstLocalName(void *);
extern (C) char * xmlTextReaderConstBaseUri(void *);
extern (C) int xmlTextReaderIsNamespaceDecl(void *);
extern (C) int xmlTextReaderReadState(void *);
extern (C) int xmlTextReaderQuoteChar(void *);
extern (C) int xmlTextReaderNodeType(void *);
extern (C) int xmlTextReaderIsEmptyElement(void *);
extern (C) int xmlTextReaderIsDefault(void *);
extern (C) int xmlTextReaderHasValue(void *);
extern (C) int xmlTextReaderHasAttributes(void *);
extern (C) int xmlTextReaderDepth(void *);
extern (C) int xmlTextReaderAttributeCount(void *);
extern (C) int xmlTextReaderReadAttributeValue(void *);
extern (C) char * xmlTextReaderReadString(void *);
extern (C) char * xmlTextReaderReadOuterXml(void *);
extern (C) char * xmlTextReaderReadInnerXml(void *);
extern (C) int xmlTextReaderRead(void *);
extern (C) void xmlFreeTextReader(void *);
extern (C) void * xmlNewTextReaderFilename(char *);
extern (C) void * xmlNewTextReader(_xmlParserInputBuffer *, char *);
alias void function(void *, char *, ...) _BCD_func__1830;
alias void function(_xmlNode *) _BCD_func__1876;
alias _xmlOutputBuffer * function(char *, _xmlCharEncodingHandler *, int) _BCD_func__1877;
alias _xmlParserInputBuffer * function(char *, int) _BCD_func__1878;
alias void function(void *, _xmlNode *, int, char * *, char * *, int, char * *, char * *) _BCD_func__1884;
alias void function(void *, _xmlNode *, int, char * *, char * *, int, char * *, char * *, int *, int *, int, char * *, char * *) _BCD_func__1885;
alias void function(void *, _xmlNode *, char *, char *, char *) _BCD_func__1886;
alias void function(void *, _xmlNode *) _BCD_func__1887;
alias int function(void *, void *) _BCD_func__1904;
alias int function(void *, char *, int) _BCD_func__2053;
alias void * function(char *) _BCD_func__2054;
alias int function(char *) _BCD_func__2055;
alias int function(char *, int *, char *, int *) _BCD_func__2066;
alias _xmlParserInput * function(char *, char *, _xmlParserCtxt *) _BCD_func__2069;
alias void function(void *, char *, char *, char *) _BCD_func__2100;
alias void function(void *, char *, char *, char *, int, char * *, int, int, char * *) _BCD_func__2101;
alias void function(void *, char *, int) _BCD_func__2102;
alias void function(void *, char *) _BCD_func__2103;
alias void function(void *, char *, char *) _BCD_func__2104;
alias void function(void *, char *, char * *) _BCD_func__2105;
alias void function(void *) _BCD_func__2106;
alias void function(void *, _xmlSAXLocator *) _BCD_func__2107;
alias void function(void *, char *, char *, char *, char *) _BCD_func__2108;
alias void function(void *, char *, int, _xmlElementContent *) _BCD_func__2109;
alias void function(void *, char *, char *, int, int, char *, _xmlEnumeration *) _BCD_func__2110;
alias void function(void *, char *, int, char *, char *, char *) _BCD_func__2111;
alias _xmlEntity * function(void *, char *) _BCD_func__2112;
alias _xmlParserInput * function(void *, char *, char *) _BCD_func__2113;
alias void function(char *) _BCD_func__2126;
alias void function(void *) _BCD_func__2146;
alias void function(void *, void *, char *, char *, char *) _BCD_func__2163;
alias void function(void *, void *, char *) _BCD_func__2164;
alias void * function(void *, char *) _BCD_func__2165;
alias void function(void *, char *) _BCD_func__2166;
alias char * function(char *) _BCD_func__2171;
alias void * function(void *, uint) _BCD_func__2172;
alias void * function(uint) _BCD_func__2173;
alias void function(void *, char *, void *, void *) _BCD_func__2292;
alias int function(void *, long *, int) _BCD_func__1574;
alias int function(void *, char *, uint) _BCD_func__1576;
alias int function(void *, char *, uint) _BCD_func__1578;
alias int function(void * *, char *) _BCD_func__2565;
alias int function(char *, char * * *, uint *) _BCD_func__2566;
alias int function(void *, char *, char *, char *, char *) _BCD_func__2567;
