/* THIS FILE GENERATED BY bcd.gen */
module bcd.fltk.Fl;
public import bcd.bind;
public import bcd.fltk.Enumerations;
extern (C) void _BCD_delete_2Fl(void *);
extern (C) void _BCD_set__ZN2Fl8e_numberE(void *, int);
extern (C) int _BCD_get__ZN2Fl8e_numberE(void *);
extern (C) void _BCD_set__ZN2Fl3e_xE(void *, int);
extern (C) int _BCD_get__ZN2Fl3e_xE(void *);
extern (C) void _BCD_set__ZN2Fl3e_yE(void *, int);
extern (C) int _BCD_get__ZN2Fl3e_yE(void *);
extern (C) void _BCD_set__ZN2Fl8e_x_rootE(void *, int);
extern (C) int _BCD_get__ZN2Fl8e_x_rootE(void *);
extern (C) void _BCD_set__ZN2Fl8e_y_rootE(void *, int);
extern (C) int _BCD_get__ZN2Fl8e_y_rootE(void *);
extern (C) void _BCD_set__ZN2Fl4e_dxE(void *, int);
extern (C) int _BCD_get__ZN2Fl4e_dxE(void *);
extern (C) void _BCD_set__ZN2Fl4e_dyE(void *, int);
extern (C) int _BCD_get__ZN2Fl4e_dyE(void *);
extern (C) void _BCD_set__ZN2Fl7e_stateE(void *, int);
extern (C) int _BCD_get__ZN2Fl7e_stateE(void *);
extern (C) void _BCD_set__ZN2Fl8e_clicksE(void *, int);
extern (C) int _BCD_get__ZN2Fl8e_clicksE(void *);
extern (C) void _BCD_set__ZN2Fl10e_is_clickE(void *, int);
extern (C) int _BCD_get__ZN2Fl10e_is_clickE(void *);
extern (C) void _BCD_set__ZN2Fl8e_keysymE(void *, int);
extern (C) int _BCD_get__ZN2Fl8e_keysymE(void *);
extern (C) void _BCD_set__ZN2Fl6e_textE(void *, char *);
extern (C) char * _BCD_get__ZN2Fl6e_textE(void *);
extern (C) void _BCD_set__ZN2Fl8e_lengthE(void *, int);
extern (C) int _BCD_get__ZN2Fl8e_lengthE(void *);
extern (C) void _BCD_set__ZN2Fl11belowmouse_E(void *, bcd.bind.BoundClass *);
extern (C) bcd.bind.BoundClass * _BCD_get__ZN2Fl11belowmouse_E(void *);
extern (C) void _BCD_set__ZN2Fl7pushed_E(void *, bcd.bind.BoundClass *);
extern (C) bcd.bind.BoundClass * _BCD_get__ZN2Fl7pushed_E(void *);
extern (C) void _BCD_set__ZN2Fl6focus_E(void *, bcd.bind.BoundClass *);
extern (C) bcd.bind.BoundClass * _BCD_get__ZN2Fl6focus_E(void *);
extern (C) void _BCD_set__ZN2Fl7damage_E(void *, int);
extern (C) int _BCD_get__ZN2Fl7damage_E(void *);
extern (C) void _BCD_set__ZN2Fl16selection_owner_E(void *, bcd.bind.BoundClass *);
extern (C) bcd.bind.BoundClass * _BCD_get__ZN2Fl16selection_owner_E(void *);
extern (C) void _BCD_set__ZN2Fl6modal_E(void *, bcd.bind.BoundClass *);
extern (C) bcd.bind.BoundClass * _BCD_get__ZN2Fl6modal_E(void *);
extern (C) void _BCD_set__ZN2Fl5grab_E(void *, bcd.bind.BoundClass *);
extern (C) bcd.bind.BoundClass * _BCD_get__ZN2Fl5grab_E(void *);
extern (C) void _BCD_set__ZN2Fl13compose_stateE(void *, int);
extern (C) int _BCD_get__ZN2Fl13compose_stateE(void *);
extern (C) void _BCD_set__ZN2Fl14visible_focus_E(void *, int);
extern (C) int _BCD_get__ZN2Fl14visible_focus_E(void *);
extern (C) void _BCD_set__ZN2Fl13dnd_text_ops_E(void *, int);
extern (C) int _BCD_get__ZN2Fl13dnd_text_ops_E(void *);
extern (C) void _BCD_set__ZN2Fl7scheme_E(void *, char *);
extern (C) char * _BCD_get__ZN2Fl7scheme_E(void *);
extern (C) void _BCD_set__ZN2Fl10scheme_bg_E(void *, bcd.bind.BoundClass *);
extern (C) bcd.bind.BoundClass * _BCD_get__ZN2Fl10scheme_bg_E(void *);
extern (C) char * _BCD_get__ZN2Fl4helpE(void *);
extern (C) void _BCD__ZN2Fl6damageEi(int);
extern (C) double _BCD__ZN2Fl7versionEv();
extern (C) int _BCD__ZN2Fl3argEiPPcRi(int, char * *, int *);
alias int function(int, char * *, int *) _BCD_func__391;
extern (C) int _BCD__ZN2Fl4argsEiPPcRiPFiiS1_S2_E(int, char * *, int *, _BCD_func__391);
extern (C) void _BCD__ZN2Fl4argsEiPPc(int, char * *);
extern (C) void _BCD__ZN2Fl7displayEPKc(char *);
extern (C) int _BCD__ZN2Fl6visualEi(int);
extern (C) void _BCD__ZN2Fl12own_colormapEv();
extern (C) void _BCD__ZN2Fl17get_system_colorsEv();
extern (C) void _BCD__ZN2Fl10foregroundEhhh(char, char, char);
extern (C) void _BCD__ZN2Fl10backgroundEhhh(char, char, char);
extern (C) void _BCD__ZN2Fl11background2Ehhh(char, char, char);
extern (C) int _BCD__ZN2Fl6schemeEPKc(char *);
extern (C) char * _BCD__ZN2Fl6schemeEv();
extern (C) int _BCD__ZN2Fl13reload_schemeEv();
extern (C) int _BCD__ZN2Fl4waitEv();
extern (C) double _BCD__ZN2Fl4waitEd(double);
extern (C) int _BCD__ZN2Fl5checkEv();
extern (C) int _BCD__ZN2Fl5readyEv();
extern (C) int _BCD__ZN2Fl3runEv();
extern (C) bcd.bind.BoundClass * _BCD__ZN2Fl9readqueueEv();
alias void function(void *) _BCD_func__341;
alias _BCD_func__341 Fl_Timeout_Handler;
extern (C) void _BCD__ZN2Fl11add_timeoutEdPFvPvES0_(double, _BCD_func__341, void *);
extern (C) void _BCD__ZN2Fl14repeat_timeoutEdPFvPvES0_(double, _BCD_func__341, void *);
extern (C) int _BCD__ZN2Fl11has_timeoutEPFvPvES0_(_BCD_func__341, void *);
extern (C) void _BCD__ZN2Fl14remove_timeoutEPFvPvES0_(_BCD_func__341, void *);
extern (C) void _BCD__ZN2Fl9add_checkEPFvPvES0_(_BCD_func__341, void *);
extern (C) void _BCD__ZN2Fl12remove_checkEPFvPvES0_(_BCD_func__341, void *);
alias void function(int, void *) _BCD_func__392;
extern (C) void _BCD__ZN2Fl6add_fdEiiPFviPvES0_(int, int, _BCD_func__392, void *);
extern (C) void _BCD__ZN2Fl6add_fdEiPFviPvES0_(int, _BCD_func__392, void *);
extern (C) void _BCD__ZN2Fl9remove_fdEii(int, int);
extern (C) void _BCD__ZN2Fl9remove_fdEi(int);
extern (C) void _BCD__ZN2Fl8add_idleEPFvPvES0_(_BCD_func__341, void *);
extern (C) int _BCD__ZN2Fl8has_idleEPFvPvES0_(_BCD_func__341, void *);
extern (C) void _BCD__ZN2Fl11remove_idleEPFvPvES0_(_BCD_func__341, void *);
extern (C) int _BCD__ZN2Fl6damageEv();
extern (C) void _BCD__ZN2Fl6redrawEv();
extern (C) void _BCD__ZN2Fl5flushEv();
extern (C) bcd.bind.BoundClass * _BCD__ZN2Fl12first_windowEv();
extern (C) void _BCD__ZN2Fl12first_windowEP9Fl_Window(void *);
extern (C) bcd.bind.BoundClass * _BCD__ZN2Fl11next_windowEPK9Fl_Window(void *);
extern (C) bcd.bind.BoundClass * _BCD__ZN2Fl5modalEv();
extern (C) bcd.bind.BoundClass * _BCD__ZN2Fl4grabEv();
extern (C) void _BCD__ZN2Fl4grabEP9Fl_Window(void *);
extern (C) int _BCD__ZN2Fl5eventEv();
extern (C) int _BCD__ZN2Fl7event_xEv();
extern (C) int _BCD__ZN2Fl7event_yEv();
extern (C) int _BCD__ZN2Fl12event_x_rootEv();
extern (C) int _BCD__ZN2Fl12event_y_rootEv();
extern (C) int _BCD__ZN2Fl8event_dxEv();
extern (C) int _BCD__ZN2Fl8event_dyEv();
extern (C) void _BCD__ZN2Fl9get_mouseERiS0_(int *, int *);
extern (C) int _BCD__ZN2Fl12event_clicksEv();
extern (C) void _BCD__ZN2Fl12event_clicksEi(int);
extern (C) int _BCD__ZN2Fl14event_is_clickEv();
extern (C) void _BCD__ZN2Fl14event_is_clickEi(int);
extern (C) int _BCD__ZN2Fl12event_buttonEv();
extern (C) int _BCD__ZN2Fl11event_stateEv();
extern (C) int _BCD__ZN2Fl11event_stateEi(int);
extern (C) int _BCD__ZN2Fl9event_keyEv();
extern (C) int _BCD__ZN2Fl9event_keyEi(int);
extern (C) int _BCD__ZN2Fl7get_keyEi(int);
extern (C) char * _BCD__ZN2Fl10event_textEv();
extern (C) int _BCD__ZN2Fl12event_lengthEv();
extern (C) int _BCD__ZN2Fl7composeERi(int *);
extern (C) void _BCD__ZN2Fl13compose_resetEv();
extern (C) int _BCD__ZN2Fl12event_insideEiiii(int, int, int, int);
extern (C) int _BCD__ZN2Fl12event_insideEPK9Fl_Widget(void *);
extern (C) int _BCD__ZN2Fl13test_shortcutEi(int);
extern (C) int _BCD__ZN2Fl6handleEiP9Fl_Window(int, void *);
extern (C) bcd.bind.BoundClass * _BCD__ZN2Fl10belowmouseEv();
extern (C) void _BCD__ZN2Fl10belowmouseEP9Fl_Widget(void *);
extern (C) bcd.bind.BoundClass * _BCD__ZN2Fl6pushedEv();
extern (C) void _BCD__ZN2Fl6pushedEP9Fl_Widget(void *);
extern (C) bcd.bind.BoundClass * _BCD__ZN2Fl5focusEv();
extern (C) void _BCD__ZN2Fl5focusEP9Fl_Widget(void *);
alias int function(int) _BCD_func__395;
extern (C) void _BCD__ZN2Fl11add_handlerEPFiiE(_BCD_func__395);
extern (C) void _BCD__ZN2Fl14remove_handlerEPFiiE(_BCD_func__395);
extern (C) void _BCD__ZN2Fl4copyEPKcii(char *, int, int);
extern (C) void _BCD__ZN2Fl5pasteER9Fl_Widgeti(void *, int);
extern (C) int _BCD__ZN2Fl3dndEv();
extern (C) bcd.bind.BoundClass * _BCD__ZN2Fl15selection_ownerEv();
extern (C) void _BCD__ZN2Fl15selection_ownerEP9Fl_Widget(void *);
extern (C) void _BCD__ZN2Fl9selectionER9Fl_WidgetPKci(void *, char *, int);
extern (C) void _BCD__ZN2Fl5pasteER9Fl_Widget(void *);
extern (C) int _BCD__ZN2Fl1xEv();
extern (C) int _BCD__ZN2Fl1yEv();
extern (C) int _BCD__ZN2Fl1wEv();
extern (C) int _BCD__ZN2Fl1hEv();
extern (C) int _BCD__ZN2Fl12screen_countEv();
extern (C) void _BCD__ZN2Fl11screen_xywhERiS0_S0_S0_(int *, int *, int *, int *);
extern (C) void _BCD__ZN2Fl11screen_xywhERiS0_S0_S0_ii(int *, int *, int *, int *, int, int);
extern (C) void _BCD__ZN2Fl11screen_xywhERiS0_S0_S0_i(int *, int *, int *, int *, int);
extern (C) void _BCD__ZN2Fl9set_colorE8Fl_Colorhhh(int, char, char, char);
extern (C) void _BCD__ZN2Fl9set_colorE8Fl_Colorj(int, uint);
extern (C) uint _BCD__ZN2Fl9get_colorE8Fl_Color(int);
extern (C) void _BCD__ZN2Fl9get_colorE8Fl_ColorRhS1_S1_(int, char *, char *, char *);
extern (C) void _BCD__ZN2Fl10free_colorE8Fl_Colori(int, int);
extern (C) char * _BCD__ZN2Fl8get_fontE7Fl_Font(int);
extern (C) char * _BCD__ZN2Fl13get_font_nameE7Fl_FontPi(int, int *);
extern (C) int _BCD__ZN2Fl14get_font_sizesE7Fl_FontRPi(int, int * *);
extern (C) void _BCD__ZN2Fl8set_fontE7Fl_FontPKc(int, char *);
extern (C) void _BCD__ZN2Fl8set_fontE7Fl_FontS0_(int, int);
extern (C) int _BCD__ZN2Fl9set_fontsEPKc(char *);
alias void function(bcd.bind.BoundClass *, int, int, int, int, int) _BCD_func__10;
alias _BCD_func__10 Fl_Label_Draw_F;
alias void function(bcd.bind.BoundClass *, int *, int *) _BCD_func__8;
alias _BCD_func__8 Fl_Label_Measure_F;
extern (C) void _BCD__ZN2Fl13set_labeltypeE12Fl_LabeltypePFvPK8Fl_Labeliiii8Fl_AlignEPFvS3_RiS7_E(int, _BCD_func__10, _BCD_func__8);
alias void function(int, int, int, int, int) _BCD_func__6;
alias _BCD_func__6 Fl_Box_Draw_F;
extern (C) _BCD_func__6 _BCD__ZN2Fl11get_boxtypeE10Fl_Boxtype(int);
extern (C) void _BCD__ZN2Fl11set_boxtypeE10Fl_BoxtypePFviiii8Fl_ColorEhhhh(int, _BCD_func__6, char, char, char, char);
extern (C) void _BCD__ZN2Fl11set_boxtypeE10Fl_BoxtypeS0_(int, int);
extern (C) int _BCD__ZN2Fl6box_dxE10Fl_Boxtype(int);
extern (C) int _BCD__ZN2Fl6box_dyE10Fl_Boxtype(int);
extern (C) int _BCD__ZN2Fl6box_dwE10Fl_Boxtype(int);
extern (C) int _BCD__ZN2Fl6box_dhE10Fl_Boxtype(int);
extern (C) int _BCD__ZN2Fl15draw_box_activeEv();
extern (C) void _BCD__ZN2Fl15default_atcloseEP9Fl_WindowPv(void *, void *);
alias void function(bcd.bind.BoundClass *, void *) _BCD_func__389;
extern (C) void _BCD__ZN2Fl11set_atcloseEPFvP9Fl_WindowPvE(_BCD_func__389);
extern (C) int _BCD__ZN2Fl11event_shiftEv();
extern (C) int _BCD__ZN2Fl10event_ctrlEv();
extern (C) int _BCD__ZN2Fl9event_altEv();
extern (C) int _BCD__ZN2Fl13event_buttonsEv();
extern (C) int _BCD__ZN2Fl13event_button1Ev();
extern (C) int _BCD__ZN2Fl13event_button2Ev();
extern (C) int _BCD__ZN2Fl13event_button3Ev();
alias void function() _BCD_func__387;
extern (C) void _BCD__ZN2Fl8set_idleEPFvvE(_BCD_func__387);
extern (C) void _BCD__ZN2Fl7releaseEv();
extern (C) void _BCD__ZN2Fl13visible_focusEi(int);
extern (C) int _BCD__ZN2Fl13visible_focusEv();
extern (C) void _BCD__ZN2Fl12dnd_text_opsEi(int);
extern (C) int _BCD__ZN2Fl12dnd_text_opsEv();
extern (C) void _BCD__ZN2Fl13delete_widgetEP9Fl_Widget(void *);
extern (C) void _BCD__ZN2Fl18do_widget_deletionEv();
extern (C) void _BCD_RI_2Fl(void *cd, void *dd);
extern (C) void _BCD_delete_2Fl__Fl_R(void *This);
class Fl : bcd.bind.BoundClass {
this(ifloat ignore) {
super(ignore);
}
this(ifloat ignore, void *x) {
super(ignore);
__C_data = x;
__C_data_owned = false;
}
~this() {
if (__C_data && __C_data_owned) _BCD_delete_2Fl(__C_data);
__C_data = null;
}
void set_e_number(int x) {
_BCD_set__ZN2Fl8e_numberE(__C_data, x);
}
int get_e_number() {
return _BCD_get__ZN2Fl8e_numberE(__C_data);
}
void set_e_x(int x) {
_BCD_set__ZN2Fl3e_xE(__C_data, x);
}
int get_e_x() {
return _BCD_get__ZN2Fl3e_xE(__C_data);
}
void set_e_y(int x) {
_BCD_set__ZN2Fl3e_yE(__C_data, x);
}
int get_e_y() {
return _BCD_get__ZN2Fl3e_yE(__C_data);
}
void set_e_x_root(int x) {
_BCD_set__ZN2Fl8e_x_rootE(__C_data, x);
}
int get_e_x_root() {
return _BCD_get__ZN2Fl8e_x_rootE(__C_data);
}
void set_e_y_root(int x) {
_BCD_set__ZN2Fl8e_y_rootE(__C_data, x);
}
int get_e_y_root() {
return _BCD_get__ZN2Fl8e_y_rootE(__C_data);
}
void set_e_dx(int x) {
_BCD_set__ZN2Fl4e_dxE(__C_data, x);
}
int get_e_dx() {
return _BCD_get__ZN2Fl4e_dxE(__C_data);
}
void set_e_dy(int x) {
_BCD_set__ZN2Fl4e_dyE(__C_data, x);
}
int get_e_dy() {
return _BCD_get__ZN2Fl4e_dyE(__C_data);
}
void set_e_state(int x) {
_BCD_set__ZN2Fl7e_stateE(__C_data, x);
}
int get_e_state() {
return _BCD_get__ZN2Fl7e_stateE(__C_data);
}
void set_e_clicks(int x) {
_BCD_set__ZN2Fl8e_clicksE(__C_data, x);
}
int get_e_clicks() {
return _BCD_get__ZN2Fl8e_clicksE(__C_data);
}
void set_e_is_click(int x) {
_BCD_set__ZN2Fl10e_is_clickE(__C_data, x);
}
int get_e_is_click() {
return _BCD_get__ZN2Fl10e_is_clickE(__C_data);
}
void set_e_keysym(int x) {
_BCD_set__ZN2Fl8e_keysymE(__C_data, x);
}
int get_e_keysym() {
return _BCD_get__ZN2Fl8e_keysymE(__C_data);
}
void set_e_text(char * x) {
_BCD_set__ZN2Fl6e_textE(__C_data, x);
}
char * get_e_text() {
return _BCD_get__ZN2Fl6e_textE(__C_data);
}
void set_e_length(int x) {
_BCD_set__ZN2Fl8e_lengthE(__C_data, x);
}
int get_e_length() {
return _BCD_get__ZN2Fl8e_lengthE(__C_data);
}
void set_belowmouse_(bcd.bind.BoundClass * x) {
_BCD_set__ZN2Fl11belowmouse_E(__C_data, x);
}
bcd.bind.BoundClass * get_belowmouse_() {
return _BCD_get__ZN2Fl11belowmouse_E(__C_data);
}
void set_pushed_(bcd.bind.BoundClass * x) {
_BCD_set__ZN2Fl7pushed_E(__C_data, x);
}
bcd.bind.BoundClass * get_pushed_() {
return _BCD_get__ZN2Fl7pushed_E(__C_data);
}
void set_focus_(bcd.bind.BoundClass * x) {
_BCD_set__ZN2Fl6focus_E(__C_data, x);
}
bcd.bind.BoundClass * get_focus_() {
return _BCD_get__ZN2Fl6focus_E(__C_data);
}
void set_damage_(int x) {
_BCD_set__ZN2Fl7damage_E(__C_data, x);
}
int get_damage_() {
return _BCD_get__ZN2Fl7damage_E(__C_data);
}
void set_selection_owner_(bcd.bind.BoundClass * x) {
_BCD_set__ZN2Fl16selection_owner_E(__C_data, x);
}
bcd.bind.BoundClass * get_selection_owner_() {
return _BCD_get__ZN2Fl16selection_owner_E(__C_data);
}
void set_modal_(bcd.bind.BoundClass * x) {
_BCD_set__ZN2Fl6modal_E(__C_data, x);
}
bcd.bind.BoundClass * get_modal_() {
return _BCD_get__ZN2Fl6modal_E(__C_data);
}
void set_grab_(bcd.bind.BoundClass * x) {
_BCD_set__ZN2Fl5grab_E(__C_data, x);
}
bcd.bind.BoundClass * get_grab_() {
return _BCD_get__ZN2Fl5grab_E(__C_data);
}
void set_compose_state(int x) {
_BCD_set__ZN2Fl13compose_stateE(__C_data, x);
}
int get_compose_state() {
return _BCD_get__ZN2Fl13compose_stateE(__C_data);
}
void set_visible_focus_(int x) {
_BCD_set__ZN2Fl14visible_focus_E(__C_data, x);
}
int get_visible_focus_() {
return _BCD_get__ZN2Fl14visible_focus_E(__C_data);
}
void set_dnd_text_ops_(int x) {
_BCD_set__ZN2Fl13dnd_text_ops_E(__C_data, x);
}
int get_dnd_text_ops_() {
return _BCD_get__ZN2Fl13dnd_text_ops_E(__C_data);
}
void set_scheme_(char * x) {
_BCD_set__ZN2Fl7scheme_E(__C_data, x);
}
char * get_scheme_() {
return _BCD_get__ZN2Fl7scheme_E(__C_data);
}
void set_scheme_bg_(bcd.bind.BoundClass * x) {
_BCD_set__ZN2Fl10scheme_bg_E(__C_data, x);
}
bcd.bind.BoundClass * get_scheme_bg_() {
return _BCD_get__ZN2Fl10scheme_bg_E(__C_data);
}
char * get_help() {
return _BCD_get__ZN2Fl4helpE(__C_data);
}
static void damage(int d) {
_BCD__ZN2Fl6damageEi(d);
}
static double version_() {
return _BCD__ZN2Fl7versionEv();
}
static int arg(int _0, char * * _1, int * _2) {
return _BCD__ZN2Fl3argEiPPcRi(_0, _1, _2);
}
static int args(int _0, char * * _1, int * _2, _BCD_func__391 _3) {
return _BCD__ZN2Fl4argsEiPPcRiPFiiS1_S2_E(_0, _1, _2, _3);
}
static void args(int _0, char * * _1) {
_BCD__ZN2Fl4argsEiPPc(_0, _1);
}
static void display(char * _0) {
_BCD__ZN2Fl7displayEPKc(_0);
}
static int visual(int _0) {
return _BCD__ZN2Fl6visualEi(_0);
}
static void own_colormap() {
_BCD__ZN2Fl12own_colormapEv();
}
static void get_system_colors() {
_BCD__ZN2Fl17get_system_colorsEv();
}
static void foreground(char _0, char _1, char _2) {
_BCD__ZN2Fl10foregroundEhhh(_0, _1, _2);
}
static void background(char _0, char _1, char _2) {
_BCD__ZN2Fl10backgroundEhhh(_0, _1, _2);
}
static void background2(char _0, char _1, char _2) {
_BCD__ZN2Fl11background2Ehhh(_0, _1, _2);
}
static int scheme(char * _0) {
return _BCD__ZN2Fl6schemeEPKc(_0);
}
static char * scheme() {
return _BCD__ZN2Fl6schemeEv();
}
static int reload_scheme() {
return _BCD__ZN2Fl13reload_schemeEv();
}
static int wait() {
return _BCD__ZN2Fl4waitEv();
}
static double wait(double time) {
return _BCD__ZN2Fl4waitEd(time);
}
static int check() {
return _BCD__ZN2Fl5checkEv();
}
static int ready() {
return _BCD__ZN2Fl5readyEv();
}
static int run() {
return _BCD__ZN2Fl3runEv();
}
static bcd.bind.BoundClass * readqueue() {
return _BCD__ZN2Fl9readqueueEv();
}
static void add_timeout(double t, _BCD_func__341 _1, void * _2) {
_BCD__ZN2Fl11add_timeoutEdPFvPvES0_(t, _1, _2);
}
static void repeat_timeout(double t, _BCD_func__341 _1, void * _2) {
_BCD__ZN2Fl14repeat_timeoutEdPFvPvES0_(t, _1, _2);
}
static int has_timeout(_BCD_func__341 _0, void * _1) {
return _BCD__ZN2Fl11has_timeoutEPFvPvES0_(_0, _1);
}
static void remove_timeout(_BCD_func__341 _0, void * _1) {
_BCD__ZN2Fl14remove_timeoutEPFvPvES0_(_0, _1);
}
static void add_check(_BCD_func__341 _0, void * _1) {
_BCD__ZN2Fl9add_checkEPFvPvES0_(_0, _1);
}
static void remove_check(_BCD_func__341 _0, void * _1) {
_BCD__ZN2Fl12remove_checkEPFvPvES0_(_0, _1);
}
static void add_fd(int fd, int when, _BCD_func__392 cb, void * _3) {
_BCD__ZN2Fl6add_fdEiiPFviPvES0_(fd, when, cb, _3);
}
static void add_fd(int fd, _BCD_func__392 cb, void * _2) {
_BCD__ZN2Fl6add_fdEiPFviPvES0_(fd, cb, _2);
}
static void remove_fd(int _0, int when) {
_BCD__ZN2Fl9remove_fdEii(_0, when);
}
static void remove_fd(int _0) {
_BCD__ZN2Fl9remove_fdEi(_0);
}
static void add_idle(_BCD_func__341 cb, void * _1) {
_BCD__ZN2Fl8add_idleEPFvPvES0_(cb, _1);
}
static int has_idle(_BCD_func__341 cb, void * _1) {
return _BCD__ZN2Fl8has_idleEPFvPvES0_(cb, _1);
}
static void remove_idle(_BCD_func__341 cb, void * _1) {
_BCD__ZN2Fl11remove_idleEPFvPvES0_(cb, _1);
}
static int damage() {
return _BCD__ZN2Fl6damageEv();
}
static void redraw() {
_BCD__ZN2Fl6redrawEv();
}
static void flush() {
_BCD__ZN2Fl5flushEv();
}
static bcd.bind.BoundClass * first_window() {
return _BCD__ZN2Fl12first_windowEv();
}
static void first_window(bcd.bind.BoundClass * _0) {
_BCD__ZN2Fl12first_windowEP9Fl_Window(_0.__C_data);
}
static bcd.bind.BoundClass * next_window(bcd.bind.BoundClass * _0) {
return _BCD__ZN2Fl11next_windowEPK9Fl_Window(_0.__C_data);
}
static bcd.bind.BoundClass * modal() {
return _BCD__ZN2Fl5modalEv();
}
static bcd.bind.BoundClass * grab() {
return _BCD__ZN2Fl4grabEv();
}
static void grab(bcd.bind.BoundClass * _0) {
_BCD__ZN2Fl4grabEP9Fl_Window(_0.__C_data);
}
static int event() {
return _BCD__ZN2Fl5eventEv();
}
static int event_x() {
return _BCD__ZN2Fl7event_xEv();
}
static int event_y() {
return _BCD__ZN2Fl7event_yEv();
}
static int event_x_root() {
return _BCD__ZN2Fl12event_x_rootEv();
}
static int event_y_root() {
return _BCD__ZN2Fl12event_y_rootEv();
}
static int event_dx() {
return _BCD__ZN2Fl8event_dxEv();
}
static int event_dy() {
return _BCD__ZN2Fl8event_dyEv();
}
static void get_mouse(int * _0, int * _1) {
_BCD__ZN2Fl9get_mouseERiS0_(_0, _1);
}
static int event_clicks() {
return _BCD__ZN2Fl12event_clicksEv();
}
static void event_clicks(int i) {
_BCD__ZN2Fl12event_clicksEi(i);
}
static int event_is_click() {
return _BCD__ZN2Fl14event_is_clickEv();
}
static void event_is_click(int i) {
_BCD__ZN2Fl14event_is_clickEi(i);
}
static int event_button() {
return _BCD__ZN2Fl12event_buttonEv();
}
static int event_state() {
return _BCD__ZN2Fl11event_stateEv();
}
static int event_state(int i) {
return _BCD__ZN2Fl11event_stateEi(i);
}
static int event_key() {
return _BCD__ZN2Fl9event_keyEv();
}
static int event_key(int _0) {
return _BCD__ZN2Fl9event_keyEi(_0);
}
static int get_key(int _0) {
return _BCD__ZN2Fl7get_keyEi(_0);
}
static char * event_text() {
return _BCD__ZN2Fl10event_textEv();
}
static int event_length() {
return _BCD__ZN2Fl12event_lengthEv();
}
static int compose(int * del) {
return _BCD__ZN2Fl7composeERi(del);
}
static void compose_reset() {
_BCD__ZN2Fl13compose_resetEv();
}
static int event_inside(int _0, int _1, int _2, int _3) {
return _BCD__ZN2Fl12event_insideEiiii(_0, _1, _2, _3);
}
static int event_inside(bcd.bind.BoundClass * _0) {
return _BCD__ZN2Fl12event_insideEPK9Fl_Widget(_0.__C_data);
}
static int test_shortcut(int _0) {
return _BCD__ZN2Fl13test_shortcutEi(_0);
}
static int handle(int _0, bcd.bind.BoundClass * _1) {
return _BCD__ZN2Fl6handleEiP9Fl_Window(_0, _1.__C_data);
}
static bcd.bind.BoundClass * belowmouse() {
return _BCD__ZN2Fl10belowmouseEv();
}
static void belowmouse(bcd.bind.BoundClass * _0) {
_BCD__ZN2Fl10belowmouseEP9Fl_Widget(_0.__C_data);
}
static bcd.bind.BoundClass * pushed() {
return _BCD__ZN2Fl6pushedEv();
}
static void pushed(bcd.bind.BoundClass * _0) {
_BCD__ZN2Fl6pushedEP9Fl_Widget(_0.__C_data);
}
static bcd.bind.BoundClass * focus() {
return _BCD__ZN2Fl5focusEv();
}
static void focus(bcd.bind.BoundClass * _0) {
_BCD__ZN2Fl5focusEP9Fl_Widget(_0.__C_data);
}
static void add_handler(_BCD_func__395 h) {
_BCD__ZN2Fl11add_handlerEPFiiE(h);
}
static void remove_handler(_BCD_func__395 h) {
_BCD__ZN2Fl14remove_handlerEPFiiE(h);
}
static void copy(char * stuff, int len, int clipboard) {
_BCD__ZN2Fl4copyEPKcii(stuff, len, clipboard);
}
static void paste(bcd.bind.BoundClass receiver, int clipboard) {
_BCD__ZN2Fl5pasteER9Fl_Widgeti(receiver.__C_data, clipboard);
}
static int dnd() {
return _BCD__ZN2Fl3dndEv();
}
static bcd.bind.BoundClass * selection_owner() {
return _BCD__ZN2Fl15selection_ownerEv();
}
static void selection_owner(bcd.bind.BoundClass * _0) {
_BCD__ZN2Fl15selection_ownerEP9Fl_Widget(_0.__C_data);
}
static void selection(bcd.bind.BoundClass owner, char * _1, int len) {
_BCD__ZN2Fl9selectionER9Fl_WidgetPKci(owner.__C_data, _1, len);
}
static void paste(bcd.bind.BoundClass receiver) {
_BCD__ZN2Fl5pasteER9Fl_Widget(receiver.__C_data);
}
static int x() {
return _BCD__ZN2Fl1xEv();
}
static int y() {
return _BCD__ZN2Fl1yEv();
}
static int w() {
return _BCD__ZN2Fl1wEv();
}
static int h() {
return _BCD__ZN2Fl1hEv();
}
static int screen_count() {
return _BCD__ZN2Fl12screen_countEv();
}
static void screen_xywh(int * x, int * y, int * w, int * h) {
_BCD__ZN2Fl11screen_xywhERiS0_S0_S0_(x, y, w, h);
}
static void screen_xywh(int * x, int * y, int * w, int * h, int mx, int my) {
_BCD__ZN2Fl11screen_xywhERiS0_S0_S0_ii(x, y, w, h, mx, my);
}
static void screen_xywh(int * x, int * y, int * w, int * h, int n) {
_BCD__ZN2Fl11screen_xywhERiS0_S0_S0_i(x, y, w, h, n);
}
static void set_color(int _0, char _1, char _2, char _3) {
_BCD__ZN2Fl9set_colorE8Fl_Colorhhh(_0, _1, _2, _3);
}
static void set_color(int _0, uint _1) {
_BCD__ZN2Fl9set_colorE8Fl_Colorj(_0, _1);
}
static uint get_color(int _0) {
return _BCD__ZN2Fl9get_colorE8Fl_Color(_0);
}
static void get_color(int _0, char * _1, char * _2, char * _3) {
_BCD__ZN2Fl9get_colorE8Fl_ColorRhS1_S1_(_0, _1, _2, _3);
}
static void free_color(int _0, int overlay) {
_BCD__ZN2Fl10free_colorE8Fl_Colori(_0, overlay);
}
static char * get_font(int _0) {
return _BCD__ZN2Fl8get_fontE7Fl_Font(_0);
}
static char * get_font_name(int _0, int * attributes) {
return _BCD__ZN2Fl13get_font_nameE7Fl_FontPi(_0, attributes);
}
static int get_font_sizes(int _0, int * * sizep) {
return _BCD__ZN2Fl14get_font_sizesE7Fl_FontRPi(_0, sizep);
}
static void set_font(int _0, char * _1) {
_BCD__ZN2Fl8set_fontE7Fl_FontPKc(_0, _1);
}
static void set_font(int _0, int _1) {
_BCD__ZN2Fl8set_fontE7Fl_FontS0_(_0, _1);
}
static int set_fonts(char * _0) {
return _BCD__ZN2Fl9set_fontsEPKc(_0);
}
static void set_labeltype(int _0, _BCD_func__10 _1, _BCD_func__8 _2) {
_BCD__ZN2Fl13set_labeltypeE12Fl_LabeltypePFvPK8Fl_Labeliiii8Fl_AlignEPFvS3_RiS7_E(_0, _1, _2);
}
static _BCD_func__6 get_boxtype(int _0) {
return _BCD__ZN2Fl11get_boxtypeE10Fl_Boxtype(_0);
}
static void set_boxtype(int _0, _BCD_func__6 _1, char _2, char _3, char _4, char _5) {
_BCD__ZN2Fl11set_boxtypeE10Fl_BoxtypePFviiii8Fl_ColorEhhhh(_0, _1, _2, _3, _4, _5);
}
static void set_boxtype(int _0, int from) {
_BCD__ZN2Fl11set_boxtypeE10Fl_BoxtypeS0_(_0, from);
}
static int box_dx(int _0) {
return _BCD__ZN2Fl6box_dxE10Fl_Boxtype(_0);
}
static int box_dy(int _0) {
return _BCD__ZN2Fl6box_dyE10Fl_Boxtype(_0);
}
static int box_dw(int _0) {
return _BCD__ZN2Fl6box_dwE10Fl_Boxtype(_0);
}
static int box_dh(int _0) {
return _BCD__ZN2Fl6box_dhE10Fl_Boxtype(_0);
}
static int draw_box_active() {
return _BCD__ZN2Fl15draw_box_activeEv();
}
static void default_atclose(bcd.bind.BoundClass * _0, void * _1) {
_BCD__ZN2Fl15default_atcloseEP9Fl_WindowPv(_0.__C_data, _1);
}
static void set_atclose(_BCD_func__389 f) {
_BCD__ZN2Fl11set_atcloseEPFvP9Fl_WindowPvE(f);
}
static int event_shift() {
return _BCD__ZN2Fl11event_shiftEv();
}
static int event_ctrl() {
return _BCD__ZN2Fl10event_ctrlEv();
}
static int event_alt() {
return _BCD__ZN2Fl9event_altEv();
}
static int event_buttons() {
return _BCD__ZN2Fl13event_buttonsEv();
}
static int event_button1() {
return _BCD__ZN2Fl13event_button1Ev();
}
static int event_button2() {
return _BCD__ZN2Fl13event_button2Ev();
}
static int event_button3() {
return _BCD__ZN2Fl13event_button3Ev();
}
static void set_idle(_BCD_func__387 cb) {
_BCD__ZN2Fl8set_idleEPFvvE(cb);
}
static void release() {
_BCD__ZN2Fl7releaseEv();
}
static void visible_focus(int v) {
_BCD__ZN2Fl13visible_focusEi(v);
}
static int visible_focus() {
return _BCD__ZN2Fl13visible_focusEv();
}
static void dnd_text_ops(int v) {
_BCD__ZN2Fl12dnd_text_opsEi(v);
}
static int dnd_text_ops() {
return _BCD__ZN2Fl12dnd_text_opsEv();
}
static void delete_widget(bcd.bind.BoundClass * w) {
_BCD__ZN2Fl13delete_widgetEP9Fl_Widget(w.__C_data);
}
static void do_widget_deletion() {
_BCD__ZN2Fl18do_widget_deletionEv();
}
}
class Fl_R : Fl {
~this() {
if (__C_data && __C_data_owned) _BCD_delete_2Fl__Fl_R(__C_data);
__C_data = null;
}
this() { super(cast(ireal) 0); }
}
