/* THIS FILE GENERATED BY bcd.gen */
module bcd.fltk.Fl_File_Icon;
public import bcd.bind;
public import bcd.fltk.Fl;
public import bcd.fltk.Enumerations;
extern (C) void _BCD_delete_12Fl_File_Icon(void *);
extern (C) void *_BCD_new__ZN12Fl_File_IconC1EPKciiPs(char *, int, int, short *);
extern (C) short * _BCD__ZN12Fl_File_Icon3addEs(void *This, short);
extern (C) short * _BCD__ZN12Fl_File_Icon9add_colorE8Fl_Color(void *This, int);
extern (C) short * _BCD__ZN12Fl_File_Icon10add_vertexEii(void *This, int, int);
extern (C) short * _BCD__ZN12Fl_File_Icon10add_vertexEff(void *This, float, float);
extern (C) void _BCD__ZN12Fl_File_Icon5clearEv(void *This);
extern (C) void _BCD__ZN12Fl_File_Icon4drawEiiii8Fl_Colori(void *This, int, int, int, int, int, int);
extern (C) void _BCD__ZN12Fl_File_Icon5labelEP9Fl_Widget(void *This, void *);
extern (C) void _BCD__ZN12Fl_File_Icon9labeltypeEPK8Fl_Labeliiii8Fl_Align(void *, int, int, int, int, int);
extern (C) void _BCD__ZN12Fl_File_Icon4loadEPKc(void *This, char *);
extern (C) int _BCD__ZN12Fl_File_Icon8load_ftiEPKc(void *This, char *);
extern (C) int _BCD__ZN12Fl_File_Icon10load_imageEPKc(void *This, char *);
extern (C) Fl_File_Icon * _BCD__ZN12Fl_File_Icon4nextEv(void *This);
extern (C) char * _BCD__ZN12Fl_File_Icon7patternEv(void *This);
extern (C) int _BCD__ZN12Fl_File_Icon4sizeEv(void *This);
extern (C) int _BCD__ZN12Fl_File_Icon4typeEv(void *This);
extern (C) short * _BCD__ZN12Fl_File_Icon5valueEv(void *This);
extern (C) Fl_File_Icon * _BCD__ZN12Fl_File_Icon4findEPKci(char *, int);
extern (C) Fl_File_Icon * _BCD__ZN12Fl_File_Icon5firstEv();
extern (C) void _BCD__ZN12Fl_File_Icon17load_system_iconsEv();
extern (C) void _BCD_RI_12Fl_File_Icon(void *cd, void *dd);
extern (C) void _BCD_delete_12Fl_File_Icon__Fl_File_Icon_R(void *This);
extern (C) void *_BCD_new__ZN12Fl_File_IconC1EPKciiPs_R(char *, int, int, short *);
alias void function(void *) _BCD_func__373;
alias void function(int, int, int, int, int) _BCD_func__7;
alias void function(bcd.bind.BoundClass *, int *, int *) _BCD_func__9;
alias void function(bcd.bind.BoundClass *, int, int, int, int, int) _BCD_func__11;
const int ANY = 0;
const int PLAIN = 1;
const int FIFO = 2;
const int DEVICE = 3;
const int LINK = 4;
const int DIRECTORY = 5;
const int END = 0;
const int COLOR = 1;
const int LINE = 2;
const int CLOSEDLINE = 3;
const int POLYGON = 4;
const int OUTLINEPOLYGON = 5;
const int VERTEX = 6;
class Fl_File_Icon : bcd.bind.BoundClass {
this(ifloat ignore) {
super(ignore);
}
this(ifloat ignore, void *x) {
super(ignore);
__C_data = x;
__C_data_owned = false;
}
~this() {
if (__C_data && __C_data_owned) _BCD_delete_12Fl_File_Icon(__C_data);
__C_data = null;
}
this(char * p, int t, int nd, short * d) {
super(cast(ifloat) 0);
__C_data = _BCD_new__ZN12Fl_File_IconC1EPKciiPs(p, t, nd, d);
__C_data_owned = true;
}
short * add(short d) {
return _BCD__ZN12Fl_File_Icon3addEs(__C_data, d);
}
short * add_color(int c) {
return _BCD__ZN12Fl_File_Icon9add_colorE8Fl_Color(__C_data, c);
}
short * add_vertex(int x, int y) {
return _BCD__ZN12Fl_File_Icon10add_vertexEii(__C_data, x, y);
}
short * add_vertex(float x, float y) {
return _BCD__ZN12Fl_File_Icon10add_vertexEff(__C_data, x, y);
}
void clear() {
_BCD__ZN12Fl_File_Icon5clearEv(__C_data);
}
void draw(int x, int y, int w, int h, int ic, int active) {
_BCD__ZN12Fl_File_Icon4drawEiiii8Fl_Colori(__C_data, x, y, w, h, ic, active);
}
void label(bcd.bind.BoundClass * w) {
_BCD__ZN12Fl_File_Icon5labelEP9Fl_Widget(__C_data, w.__C_data);
}
static void labeltype(bcd.bind.BoundClass * o, int x, int y, int w, int h, int a) {
_BCD__ZN12Fl_File_Icon9labeltypeEPK8Fl_Labeliiii8Fl_Align(o.__C_data, x, y, w, h, a);
}
void load(char * f) {
_BCD__ZN12Fl_File_Icon4loadEPKc(__C_data, f);
}
int load_fti(char * fti) {
return _BCD__ZN12Fl_File_Icon8load_ftiEPKc(__C_data, fti);
}
int load_image(char * i) {
return _BCD__ZN12Fl_File_Icon10load_imageEPKc(__C_data, i);
}
Fl_File_Icon * next() {
return _BCD__ZN12Fl_File_Icon4nextEv(__C_data);
}
char * pattern() {
return _BCD__ZN12Fl_File_Icon7patternEv(__C_data);
}
int size() {
return _BCD__ZN12Fl_File_Icon4sizeEv(__C_data);
}
int type() {
return _BCD__ZN12Fl_File_Icon4typeEv(__C_data);
}
short * value() {
return _BCD__ZN12Fl_File_Icon5valueEv(__C_data);
}
static Fl_File_Icon * find(char * filename, int filetype) {
return _BCD__ZN12Fl_File_Icon4findEPKci(filename, filetype);
}
static Fl_File_Icon * first() {
return _BCD__ZN12Fl_File_Icon5firstEv();
}
static void load_system_icons() {
_BCD__ZN12Fl_File_Icon17load_system_iconsEv();
}
}
class Fl_File_Icon_R : Fl_File_Icon {
~this() {
if (__C_data && __C_data_owned) _BCD_delete_12Fl_File_Icon__Fl_File_Icon_R(__C_data);
__C_data = null;
}
this(char * p, int t, int nd, short * d) {
super(cast(ifloat) 0);
__C_data = _BCD_new__ZN12Fl_File_IconC1EPKciiPs_R(p, t, nd, d);
__C_data_owned = true;
_BCD_RI_12Fl_File_Icon(__C_data, cast(void *) this);
}
}
