/* THIS FILE GENERATED BY bcd.gen */
#include <stdlib.h>
#include <string.h>
#include "../bind.h"
#include "FL/fl_message.H"
extern "C" {
typedef long unsigned int _BCD__56_ulong;
typedef unsigned char _BCD__58_uchar;
}
