/* THIS FILE GENERATED BY bcd.gen */
#include <stdlib.h>
#include <string.h>
#include "../bind.h"
#include "FL/Fl_Overlay_Window.H"
extern "C" {
void _BCD_delete_17Fl_Overlay_Window(Fl_Overlay_Window *This) {
delete This;
}
void _BCD__ZN17Fl_Overlay_Window4showEv(Fl_Overlay_Window *This) {
(This->show());
}
void _BCD__ZN17Fl_Overlay_Window5flushEv(Fl_Overlay_Window *This) {
(This->flush());
}
void _BCD__ZN17Fl_Overlay_Window4hideEv(Fl_Overlay_Window *This) {
(This->hide());
}
void _BCD__ZN17Fl_Overlay_Window6resizeEiiii(Fl_Overlay_Window *This, int _0, int _1, int _2, int _3) {
(This->resize(_0, _1, _2, _3));
}
int _BCD__ZN17Fl_Overlay_Window14can_do_overlayEv(Fl_Overlay_Window *This) {
return (This->can_do_overlay());
}
void _BCD__ZN17Fl_Overlay_Window14redraw_overlayEv(Fl_Overlay_Window *This) {
(This->redraw_overlay());
}
void _BCD__ZN17Fl_Overlay_Window4showEiPPc(Fl_Overlay_Window *This, int a, char * * b) {
(This->show(a, b));
}
typedef void (*_BCD_func__14)(Fl_Widget *, long int);
typedef _BCD_func__14 _BCD__15_Fl_Callback1;
typedef void (*_BCD_func__16)(Fl_Widget *);
typedef _BCD_func__16 _BCD__17_Fl_Callback0;
typedef void (*_BCD_func__20)(Fl_Widget *, void *);
typedef _BCD_func__20 _BCD__21_Fl_Callback;
typedef _BCD__21_Fl_Callback _BCD__19_Fl_Callback_p;
typedef long unsigned int _BCD__61_ulong;
typedef unsigned char _BCD__63_uchar;
}
