/* THIS FILE GENERATED BY bcd.gen */
#include <stdlib.h>
#include <string.h>
#include "../bind.h"
#include "FL/Fl_Pack.H"
extern "C" {
void _BCD_delete_7Fl_Pack(Fl_Pack *This) {
delete This;
}
void _BCD__ZN7Fl_Pack4drawEv(Fl_Pack *This) {
(This->draw());
}
Fl_Pack *_BCD_new__ZN7Fl_PackC1EiiiiPKc(int x, int y, int w, int h, char const * l) {
return new Fl_Pack(x, y, w, h, l);
}
int _BCD__ZNK7Fl_Pack7spacingEv(Fl_Pack *This) {
return (This->spacing());
}
void _BCD__ZN7Fl_Pack7spacingEi(Fl_Pack *This, int i) {
(This->spacing(i));
}
typedef unsigned char _BCD__58_uchar;
_BCD__58_uchar _BCD__ZNK7Fl_Pack10horizontalEv(Fl_Pack *This) {
return (This->horizontal());
}
int _BCD_R__ZN7Fl_Pack4drawEv__Fl_Pack_R_CHECK(void *);
void _BCD_R__ZN7Fl_Pack4drawEv__Fl_Pack_R(void *);
}
class Fl_Pack_R : Fl_Pack {
public:
void *__D_data;
void draw() {
if (_BCD_R__ZN7Fl_Pack4drawEv__Fl_Pack_R_CHECK(__D_data))
_BCD_R__ZN7Fl_Pack4drawEv__Fl_Pack_R(__D_data);
else
Fl_Pack::draw();
}
Fl_Pack_R(int x, int y, int w, int h, char const * l) : Fl_Pack(x, y, w, h, l) {}
};
extern "C" {
Fl_Pack_R *_BCD_new__ZN7Fl_PackC1EiiiiPKc_R(int x, int y, int w, int h, char const * l) {
return new Fl_Pack_R(x, y, w, h, l);
}
void _BCD_delete_7Fl_Pack__Fl_Pack_R(Fl_Pack_R *This) {
delete This;
}
void _BCD_RI_7Fl_Pack(Fl_Pack_R *cd, void *dd) {
cd->__D_data = dd;
}
typedef void (*_BCD_func__9)(Fl_Widget *, long int);
typedef _BCD_func__9 _BCD__10_Fl_Callback1;
typedef void (*_BCD_func__11)(Fl_Widget *);
typedef _BCD_func__11 _BCD__12_Fl_Callback0;
typedef void (*_BCD_func__15)(Fl_Widget *, void *);
typedef _BCD_func__15 _BCD__16_Fl_Callback;
typedef _BCD__16_Fl_Callback _BCD__14_Fl_Callback_p;
typedef long unsigned int _BCD__56_ulong;
}
