/* THIS FILE GENERATED BY bcd.gen */
module bcd.fltk.Fl_Scrollbar;
public import bcd.bind;
public import bcd.fltk.Fl_Slider;
public import bcd.fltk.Fl_Valuator;
public import bcd.fltk.Fl_Widget;
public import bcd.fltk.Enumerations;
extern (C) void _BCD_delete_12Fl_Scrollbar(void *);
extern (C) void *_BCD_new__ZN12Fl_ScrollbarC1EiiiiPKc(int, int, int, int, char *);
extern (C) int _BCD__ZN12Fl_Scrollbar6handleEi(void *This, int);
extern (C) int _BCD__ZN12Fl_Scrollbar5valueEiiii(void *This, int, int, int, int);
extern (C) int _BCD__ZNK12Fl_Scrollbar8linesizeEv(void *This);
extern (C) void _BCD__ZN12Fl_Scrollbar8linesizeEi(void *This, int);
extern (C) void _BCD_RI_12Fl_Scrollbar(void *cd, void *dd);
extern (C) void _BCD_delete_12Fl_Scrollbar__Fl_Scrollbar_R(void *This);
extern (C) void *_BCD_new__ZN12Fl_ScrollbarC1EiiiiPKc_R(int, int, int, int, char *);
extern (C) int _BCD_R__ZN12Fl_Scrollbar6handleEi__Fl_Scrollbar_R_CHECK(Fl_Scrollbar_R x) {
union dp {
int delegate(int) d;
struct { void *o; void *f; }
}
dp d; d.d = &x.handle;
return cast(int) (d.f != &Fl_Scrollbar.handle);
}
extern (C) int _BCD_R__ZN12Fl_Scrollbar6handleEi__Fl_Scrollbar_R(Fl_Scrollbar_R __D_class, int _0) {
return __D_class.handle(_0);
}
alias void function(Fl_Widget *, int) _BCD_func__11;
alias void function(Fl_Widget *) _BCD_func__13;
alias void function(Fl_Widget *, void *) _BCD_func__17;
class Fl_Scrollbar : Fl_Slider {
this(ifloat ignore) {
super(ignore);
}
this(ifloat ignore, void *x) {
super(ignore);
__C_data = x;
__C_data_owned = false;
}
~this() {
if (__C_data && __C_data_owned) _BCD_delete_12Fl_Scrollbar(__C_data);
__C_data = null;
}
this(int x, int y, int w, int h, char * l) {
super(cast(ifloat) 0);
__C_data = _BCD_new__ZN12Fl_ScrollbarC1EiiiiPKc(x, y, w, h, l);
__C_data_owned = true;
}
int handle(int _0) {
return _BCD__ZN12Fl_Scrollbar6handleEi(__C_data, _0);
}
int value(int p, int s, int top, int total) {
return _BCD__ZN12Fl_Scrollbar5valueEiiii(__C_data, p, s, top, total);
}
int linesize() {
return _BCD__ZNK12Fl_Scrollbar8linesizeEv(__C_data);
}
void linesize(int i) {
_BCD__ZN12Fl_Scrollbar8linesizeEi(__C_data, i);
}
}
class Fl_Scrollbar_R : Fl_Scrollbar {
~this() {
if (__C_data && __C_data_owned) _BCD_delete_12Fl_Scrollbar__Fl_Scrollbar_R(__C_data);
__C_data = null;
}
this(int x, int y, int w, int h, char * l) {
super(cast(ifloat) 0);
__C_data = _BCD_new__ZN12Fl_ScrollbarC1EiiiiPKc_R(x, y, w, h, l);
__C_data_owned = true;
_BCD_RI_12Fl_Scrollbar(__C_data, cast(void *) this);
}
}
