/* THIS FILE GENERATED BY bcd.gen */
#include <stdlib.h>
#include <string.h>
#include "../bind.h"
#include "FL/Fl_Browser.H"
extern "C" {
void _BCD_delete_10Fl_Browser(Fl_Browser *This) {
delete This;
}
void _BCD__ZN10Fl_Browser6removeEi(Fl_Browser *This, int _0) {
(This->remove(_0));
}
void _BCD__ZN10Fl_Browser3addEPKcPv(Fl_Browser *This, char const * _0, void * _1) {
(This->add(_0, _1));
}
void _BCD__ZN10Fl_Browser6insertEiPKcPv(Fl_Browser *This, int _0, char const * _1, void * _2) {
(This->insert(_0, _1, _2));
}
void _BCD__ZN10Fl_Browser4moveEii(Fl_Browser *This, int to, int from) {
(This->move(to, from));
}
int _BCD__ZN10Fl_Browser4loadEPKc(Fl_Browser *This, char const * filename) {
return (This->load(filename));
}
void _BCD__ZN10Fl_Browser4swapEii(Fl_Browser *This, int a, int b) {
(This->swap(a, b));
}
void _BCD__ZN10Fl_Browser5clearEv(Fl_Browser *This) {
(This->clear());
}
int _BCD__ZNK10Fl_Browser4sizeEv(Fl_Browser *This) {
return (This->size());
}
void _BCD__ZN10Fl_Browser4sizeEii(Fl_Browser *This, int W, int H) {
(This->size(W, H));
}
int _BCD__ZNK10Fl_Browser7toplineEv(Fl_Browser *This) {
return (This->topline());
}
void _BCD__ZN10Fl_Browser12linepositionEiNS_16Fl_Line_PositionE(Fl_Browser *This, int _0, enum Fl_Browser::Fl_Line_Position _1) {
(This->lineposition(_0, _1));
}
void _BCD__ZN10Fl_Browser7toplineEi(Fl_Browser *This, int l) {
(This->topline(l));
}
void _BCD__ZN10Fl_Browser10bottomlineEi(Fl_Browser *This, int l) {
(This->bottomline(l));
}
void _BCD__ZN10Fl_Browser10middlelineEi(Fl_Browser *This, int l) {
(This->middleline(l));
}
int _BCD__ZN10Fl_Browser6selectEii(Fl_Browser *This, int _0, int _1) {
return (This->select(_0, _1));
}
int _BCD__ZNK10Fl_Browser8selectedEi(Fl_Browser *This, int _0) {
return (This->selected(_0));
}
void _BCD__ZN10Fl_Browser4showEi(Fl_Browser *This, int n) {
(This->show(n));
}
void _BCD__ZN10Fl_Browser4showEv(Fl_Browser *This) {
(This->show());
}
void _BCD__ZN10Fl_Browser4hideEi(Fl_Browser *This, int n) {
(This->hide(n));
}
void _BCD__ZN10Fl_Browser4hideEv(Fl_Browser *This) {
(This->hide());
}
int _BCD__ZNK10Fl_Browser7visibleEi(Fl_Browser *This, int n) {
return (This->visible(n));
}
int _BCD__ZNK10Fl_Browser5valueEv(Fl_Browser *This) {
return (This->value());
}
void _BCD__ZN10Fl_Browser5valueEi(Fl_Browser *This, int v) {
(This->value(v));
}
char const * _BCD__ZNK10Fl_Browser4textEi(Fl_Browser *This, int _0) {
return (This->text(_0));
}
void _BCD__ZN10Fl_Browser4textEiPKc(Fl_Browser *This, int _0, char const * _1) {
(This->text(_0, _1));
}
void * _BCD__ZNK10Fl_Browser4dataEi(Fl_Browser *This, int _0) {
return (This->data(_0));
}
void _BCD__ZN10Fl_Browser4dataEiPv(Fl_Browser *This, int _0, void * v) {
(This->data(_0, v));
}
Fl_Browser *_BCD_new__ZN10Fl_BrowserC1EiiiiPKc(int _0, int _1, int _2, int _3, char const * _4) {
return new Fl_Browser(_0, _1, _2, _3, _4);
}
char _BCD__ZNK10Fl_Browser11format_charEv(Fl_Browser *This) {
return (This->format_char());
}
void _BCD__ZN10Fl_Browser11format_charEc(Fl_Browser *This, char c) {
(This->format_char(c));
}
char _BCD__ZNK10Fl_Browser11column_charEv(Fl_Browser *This) {
return (This->column_char());
}
void _BCD__ZN10Fl_Browser11column_charEc(Fl_Browser *This, char c) {
(This->column_char(c));
}
int const * _BCD__ZNK10Fl_Browser13column_widthsEv(Fl_Browser *This) {
return (This->column_widths());
}
void _BCD__ZN10Fl_Browser13column_widthsEPKi(Fl_Browser *This, int const * l) {
(This->column_widths(l));
}
int _BCD__ZNK10Fl_Browser9displayedEi(Fl_Browser *This, int n) {
return (This->displayed(n));
}
void _BCD__ZN10Fl_Browser12make_visibleEi(Fl_Browser *This, int n) {
(This->make_visible(n));
}
void _BCD__ZN10Fl_Browser7replaceEiPKc(Fl_Browser *This, int a, char const * b) {
(This->replace(a, b));
}
void _BCD__ZN10Fl_Browser7displayEii(Fl_Browser *This, int _0, int _1) {
(This->display(_0, _1));
}
}
class Fl_Browser_R : Fl_Browser {
public:
void *__D_data;
Fl_Browser_R(int _0, int _1, int _2, int _3, char const * _4) : Fl_Browser(_0, _1, _2, _3, _4) {}
};
extern "C" {
Fl_Browser_R *_BCD_new__ZN10Fl_BrowserC1EiiiiPKc_R(int _0, int _1, int _2, int _3, char const * _4) {
return new Fl_Browser_R(_0, _1, _2, _3, _4);
}
void _BCD_delete_10Fl_Browser__Fl_Browser_R(Fl_Browser_R *This) {
delete This;
}
void _BCD_RI_10Fl_Browser(Fl_Browser_R *cd, void *dd) {
cd->__D_data = dd;
}
typedef void (*_BCD_func__18)(Fl_Widget *, long int);
typedef _BCD_func__18 _BCD__19_Fl_Callback1;
typedef void (*_BCD_func__20)(Fl_Widget *);
typedef _BCD_func__20 _BCD__21_Fl_Callback0;
typedef void (*_BCD_func__24)(Fl_Widget *, void *);
typedef _BCD_func__24 _BCD__25_Fl_Callback;
typedef _BCD__25_Fl_Callback _BCD__23_Fl_Callback_p;
typedef long unsigned int _BCD__65_ulong;
typedef unsigned char _BCD__67_uchar;
}
