/* THIS FILE GENERATED BY bcd.gen */
#include <stdlib.h>
#include <string.h>
#include "../bind.h"
#include "FL/Fl_Window.H"
extern "C" {
void _BCD_delete_9Fl_Window(Fl_Window *This) {
delete This;
}
Fl_Window *_BCD_new__ZN9Fl_WindowC1EiiiiPKc(int _0, int _1, int _2, int _3, char const * _4) {
return new Fl_Window(_0, _1, _2, _3, _4);
}
Fl_Window *_BCD_new__ZN9Fl_WindowC1EiiPKc(int _0, int _1, char const * _2) {
return new Fl_Window(_0, _1, _2);
}
int _BCD__ZN9Fl_Window6handleEi(Fl_Window *This, int _0) {
return (This->handle(_0));
}
void _BCD__ZN9Fl_Window6resizeEiiii(Fl_Window *This, int _0, int _1, int _2, int _3) {
(This->resize(_0, _1, _2, _3));
}
void _BCD__ZN9Fl_Window6borderEi(Fl_Window *This, int b) {
(This->border(b));
}
void _BCD__ZN9Fl_Window12clear_borderEv(Fl_Window *This) {
(This->clear_border());
}
int _BCD__ZNK9Fl_Window6borderEv(Fl_Window *This) {
return (This->border());
}
void _BCD__ZN9Fl_Window12set_overrideEv(Fl_Window *This) {
(This->set_override());
}
int _BCD__ZNK9Fl_Window8overrideEv(Fl_Window *This) {
return (This->override());
}
void _BCD__ZN9Fl_Window9set_modalEv(Fl_Window *This) {
(This->set_modal());
}
int _BCD__ZNK9Fl_Window5modalEv(Fl_Window *This) {
return (This->modal());
}
void _BCD__ZN9Fl_Window13set_non_modalEv(Fl_Window *This) {
(This->set_non_modal());
}
int _BCD__ZNK9Fl_Window9non_modalEv(Fl_Window *This) {
return (This->non_modal());
}
void _BCD__ZN9Fl_Window7hotspotEiii(Fl_Window *This, int x, int y, int offscreen) {
(This->hotspot(x, y, offscreen));
}
void _BCD__ZN9Fl_Window7hotspotEPK9Fl_Widgeti(Fl_Window *This, Fl_Widget const * _0, int offscreen) {
(This->hotspot(_0, offscreen));
}
void _BCD__ZN9Fl_Window13free_positionEv(Fl_Window *This) {
(This->free_position());
}
void _BCD__ZN9Fl_Window10size_rangeEiiiiiii(Fl_Window *This, int a, int b, int c, int d, int e, int f, int g) {
(This->size_range(a, b, c, d, e, f, g));
}
char const * _BCD__ZNK9Fl_Window5labelEv(Fl_Window *This) {
return (This->label());
}
char const * _BCD__ZNK9Fl_Window9iconlabelEv(Fl_Window *This) {
return (This->iconlabel());
}
void _BCD__ZN9Fl_Window5labelEPKc(Fl_Window *This, char const * _0) {
(This->label(_0));
}
void _BCD__ZN9Fl_Window9iconlabelEPKc(Fl_Window *This, char const * _0) {
(This->iconlabel(_0));
}
void _BCD__ZN9Fl_Window5labelEPKcS1_(Fl_Window *This, char const * label, char const * iconlabel) {
(This->label(label, iconlabel));
}
void _BCD__ZN9Fl_Window10copy_labelEPKc(Fl_Window *This, char const * a) {
(This->copy_label(a));
}
char const * _BCD__ZNK9Fl_Window6xclassEv(Fl_Window *This) {
return (This->xclass());
}
void _BCD__ZN9Fl_Window6xclassEPKc(Fl_Window *This, char const * c) {
(This->xclass(c));
}
void const * _BCD__ZNK9Fl_Window4iconEv(Fl_Window *This) {
return (This->icon());
}
void _BCD__ZN9Fl_Window4iconEPKv(Fl_Window *This, void const * ic) {
(This->icon(ic));
}
int _BCD__ZN9Fl_Window5shownEv(Fl_Window *This) {
return (This->shown());
}
void _BCD__ZN9Fl_Window4showEv(Fl_Window *This) {
(This->show());
}
void _BCD__ZN9Fl_Window4hideEv(Fl_Window *This) {
(This->hide());
}
void _BCD__ZN9Fl_Window4showEiPPc(Fl_Window *This, int _0, char * * _1) {
(This->show(_0, _1));
}
void _BCD__ZN9Fl_Window10fullscreenEv(Fl_Window *This) {
(This->fullscreen());
}
void _BCD__ZN9Fl_Window14fullscreen_offEiiii(Fl_Window *This, int _0, int _1, int _2, int _3) {
(This->fullscreen_off(_0, _1, _2, _3));
}
void _BCD__ZN9Fl_Window7iconizeEv(Fl_Window *This) {
(This->iconize());
}
int _BCD__ZNK9Fl_Window6x_rootEv(Fl_Window *This) {
return (This->x_root());
}
int _BCD__ZNK9Fl_Window6y_rootEv(Fl_Window *This) {
return (This->y_root());
}
void _BCD__ZN9Fl_Window12make_currentEv(Fl_Window *This) {
(This->make_current());
}
void _BCD__ZN9Fl_Window6cursorE9Fl_Cursor8Fl_ColorS1_(Fl_Window *This, enum Fl_Cursor _0, enum Fl_Color _1, enum Fl_Color _2) {
(This->cursor(_0, _1, _2));
}
void _BCD__ZN9Fl_Window14default_cursorE9Fl_Cursor8Fl_ColorS1_(Fl_Window *This, enum Fl_Cursor _0, enum Fl_Color _1, enum Fl_Color _2) {
(This->default_cursor(_0, _1, _2));
}
void _BCD__ZN9Fl_Window16default_callbackEPS_Pv(Fl_Window * _0, void * v) {
(Fl_Window::default_callback(_0, v));
}
int _BCD_R__ZN9Fl_Window6handleEi__Fl_Window_R_CHECK(void *);
int _BCD_R__ZN9Fl_Window6handleEi__Fl_Window_R(void *, int _0);
int _BCD_R__ZN9Fl_Window6resizeEiiii__Fl_Window_R_CHECK(void *);
void _BCD_R__ZN9Fl_Window6resizeEiiii__Fl_Window_R(void *, int _0, int _1, int _2, int _3);
int _BCD_R__ZN9Fl_Window4showEv__Fl_Window_R_CHECK(void *);
void _BCD_R__ZN9Fl_Window4showEv__Fl_Window_R(void *);
int _BCD_R__ZN9Fl_Window4hideEv__Fl_Window_R_CHECK(void *);
void _BCD_R__ZN9Fl_Window4hideEv__Fl_Window_R(void *);
}
class Fl_Window_R : Fl_Window {
public:
void *__D_data;
Fl_Window_R(int _0, int _1, int _2, int _3, char const * _4) : Fl_Window(_0, _1, _2, _3, _4) {}
Fl_Window_R(int _0, int _1, char const * _2) : Fl_Window(_0, _1, _2) {}
int handle(int _0) {
if (_BCD_R__ZN9Fl_Window6handleEi__Fl_Window_R_CHECK(__D_data))
return _BCD_R__ZN9Fl_Window6handleEi__Fl_Window_R(__D_data, _0);
else
return Fl_Window::handle(_0);
}
void resize(int _0, int _1, int _2, int _3) {
if (_BCD_R__ZN9Fl_Window6resizeEiiii__Fl_Window_R_CHECK(__D_data))
_BCD_R__ZN9Fl_Window6resizeEiiii__Fl_Window_R(__D_data, _0, _1, _2, _3);
else
Fl_Window::resize(_0, _1, _2, _3);
}
void show() {
if (_BCD_R__ZN9Fl_Window4showEv__Fl_Window_R_CHECK(__D_data))
_BCD_R__ZN9Fl_Window4showEv__Fl_Window_R(__D_data);
else
Fl_Window::show();
}
void hide() {
if (_BCD_R__ZN9Fl_Window4hideEv__Fl_Window_R_CHECK(__D_data))
_BCD_R__ZN9Fl_Window4hideEv__Fl_Window_R(__D_data);
else
Fl_Window::hide();
}
};
extern "C" {
Fl_Window_R *_BCD_new__ZN9Fl_WindowC1EiiiiPKc_R(int _0, int _1, int _2, int _3, char const * _4) {
return new Fl_Window_R(_0, _1, _2, _3, _4);
}
Fl_Window_R *_BCD_new__ZN9Fl_WindowC1EiiPKc_R(int _0, int _1, char const * _2) {
return new Fl_Window_R(_0, _1, _2);
}
void _BCD_delete_9Fl_Window__Fl_Window_R(Fl_Window_R *This) {
delete This;
}
void _BCD_RI_9Fl_Window(Fl_Window_R *cd, void *dd) {
cd->__D_data = dd;
}
typedef void (*_BCD_func__9)(Fl_Widget *, long int);
typedef _BCD_func__9 _BCD__10_Fl_Callback1;
typedef void (*_BCD_func__11)(Fl_Widget *);
typedef _BCD_func__11 _BCD__12_Fl_Callback0;
typedef void (*_BCD_func__15)(Fl_Widget *, void *);
typedef _BCD_func__15 _BCD__16_Fl_Callback;
typedef _BCD__16_Fl_Callback _BCD__14_Fl_Callback_p;
typedef long unsigned int _BCD__56_ulong;
typedef unsigned char _BCD__58_uchar;
}
