/* THIS FILE GENERATED BY bcd.gen */
module bcd.ogg.ogg;
align(4):
extern (C) void ogg_packet_clear(ogg_packet *);
extern (C) int ogg_page_packets(ogg_page *);
extern (C) int ogg_page_pageno(ogg_page *);
extern (C) int ogg_page_serialno(ogg_page *);
extern (C) long ogg_page_granulepos(ogg_page *);
extern (C) int ogg_page_eos(ogg_page *);
extern (C) int ogg_page_bos(ogg_page *);
extern (C) int ogg_page_continued(ogg_page *);
extern (C) int ogg_page_version(ogg_page *);
extern (C) void ogg_page_checksum_set(ogg_page *);
extern (C) int ogg_stream_eos(ogg_stream_state *);
extern (C) int ogg_stream_destroy(ogg_stream_state *);
extern (C) int ogg_stream_reset_serialno(ogg_stream_state *, int);
extern (C) int ogg_stream_reset(ogg_stream_state *);
extern (C) int ogg_stream_clear(ogg_stream_state *);
extern (C) int ogg_stream_init(ogg_stream_state *, int);
extern (C) int ogg_stream_packetpeek(ogg_stream_state *, ogg_packet *);
extern (C) int ogg_stream_packetout(ogg_stream_state *, ogg_packet *);
extern (C) int ogg_stream_pagein(ogg_stream_state *, ogg_page *);
extern (C) int ogg_sync_pageout(ogg_sync_state *, ogg_page *);
extern (C) int ogg_sync_pageseek(ogg_sync_state *, ogg_page *);
extern (C) int ogg_sync_wrote(ogg_sync_state *, int);
extern (C) char * ogg_sync_buffer(ogg_sync_state *, int);
extern (C) int ogg_sync_destroy(ogg_sync_state *);
extern (C) int ogg_sync_reset(ogg_sync_state *);
extern (C) int ogg_sync_clear(ogg_sync_state *);
extern (C) int ogg_sync_init(ogg_sync_state *);
extern (C) int ogg_stream_flush(ogg_stream_state *, ogg_page *);
extern (C) int ogg_stream_pageout(ogg_stream_state *, ogg_page *);
extern (C) int ogg_stream_packetin(ogg_stream_state *, ogg_packet *);
extern (C) char * oggpackB_get_buffer(oggpack_buffer *);
extern (C) int oggpackB_bits(oggpack_buffer *);
extern (C) int oggpackB_bytes(oggpack_buffer *);
extern (C) int oggpackB_read1(oggpack_buffer *);
extern (C) int oggpackB_read(oggpack_buffer *, int);
extern (C) void oggpackB_adv1(oggpack_buffer *);
extern (C) void oggpackB_adv(oggpack_buffer *, int);
extern (C) int oggpackB_look1(oggpack_buffer *);
extern (C) int oggpackB_look(oggpack_buffer *, int);
extern (C) void oggpackB_write(oggpack_buffer *, uint, int);
extern (C) void oggpackB_readinit(oggpack_buffer *, char *, int);
extern (C) void oggpackB_writeclear(oggpack_buffer *);
extern (C) void oggpackB_reset(oggpack_buffer *);
extern (C) void oggpackB_writecopy(oggpack_buffer *, void *, int);
extern (C) void oggpackB_writealign(oggpack_buffer *);
extern (C) void oggpackB_writetrunc(oggpack_buffer *, int);
extern (C) void oggpackB_writeinit(oggpack_buffer *);
extern (C) char * oggpack_get_buffer(oggpack_buffer *);
extern (C) int oggpack_bits(oggpack_buffer *);
extern (C) int oggpack_bytes(oggpack_buffer *);
extern (C) int oggpack_read1(oggpack_buffer *);
extern (C) int oggpack_read(oggpack_buffer *, int);
extern (C) void oggpack_adv1(oggpack_buffer *);
extern (C) void oggpack_adv(oggpack_buffer *, int);
extern (C) int oggpack_look1(oggpack_buffer *);
extern (C) int oggpack_look(oggpack_buffer *, int);
extern (C) void oggpack_write(oggpack_buffer *, uint, int);
extern (C) void oggpack_readinit(oggpack_buffer *, char *, int);
extern (C) void oggpack_writeclear(oggpack_buffer *);
extern (C) void oggpack_reset(oggpack_buffer *);
extern (C) void oggpack_writecopy(oggpack_buffer *, void *, int);
extern (C) void oggpack_writealign(oggpack_buffer *);
extern (C) void oggpack_writetrunc(oggpack_buffer *, int);
extern (C) void oggpack_writeinit(oggpack_buffer *);
struct ogg_sync_state {
char * data;
int storage;
int fill;
int returned;
int unsynced;
int headerbytes;
int bodybytes;
}
struct ogg_packet {
char * packet;
int bytes;
int b_o_s;
int e_o_s;
long granulepos;
long packetno;
}
struct ogg_stream_state {
char * body_data;
int body_storage;
int body_fill;
int body_returned;
int * lacing_vals;
long * granule_vals;
int lacing_storage;
int lacing_fill;
int lacing_packet;
int lacing_returned;
char [282] header;
int header_fill;
int e_o_s;
int b_o_s;
int serialno;
int pageno;
long packetno;
long granulepos;
}
struct ogg_page {
char * header;
int header_len;
char * body_;
int body_len;
}
struct oggpack_buffer {
int endbyte;
int endbit;
char * buffer;
char * ptr;
int storage;
}
