/* THIS FILE GENERATED BY bcd.gen */
#include <stdlib.h>
#include <string.h>
#include "../bind.h"
#include "fltk/Item.h"
extern "C" {
typedef unsigned char _BCD__7_uchar;
void _BCD_delete_N4fltk4ItemE(fltk::Item *This) {
delete This;
}
void _BCD_set__ZN4fltk4Item13default_styleE(fltk::Item *This, fltk::NamedStyle * x) {
This->default_style = x;
}
fltk::NamedStyle * _BCD_get__ZN4fltk4Item13default_styleE(fltk::Item *This) {
return This->default_style;
}
void _BCD__ZN4fltk4Item4drawEv(fltk::Item *This) {
(This->draw());
}
void _BCD__ZN4fltk4Item6layoutEv(fltk::Item *This) {
(This->layout());
}
int _BCD__ZN4fltk4Item6handleEi(fltk::Item *This, int _0) {
return (This->handle(_0));
}
fltk::Item *_BCD_new__ZN4fltk4ItemC1EPKc(char const * label) {
return new fltk::Item(label);
}
fltk::Item *_BCD_new__ZN4fltk4ItemC1EPKcPKNS_6SymbolE(char const * label, fltk::Symbol const * _1) {
return new fltk::Item(label, _1);
}
typedef void (*_BCD_func__158)(fltk::Widget *, void *);
typedef _BCD_func__158 _BCD__159_Callback;
fltk::Item *_BCD_new__ZN4fltk4ItemC1EPKciPFvPNS_6WidgetEPvES5_i(char const * label, int shortcut, _BCD__159_Callback callback, void * user_data_, int flags) {
return new fltk::Item(label, shortcut, callback, user_data_, flags);
}
void _BCD__ZN4fltk4Item9set_styleEPKNS_5StyleEb(fltk::Style const * _0, bool menubar) {
(fltk::Item::set_style(_0, menubar));
}
void _BCD__ZN4fltk4Item11clear_styleEv() {
(fltk::Item::clear_style());
}
int _BCD_R__ZN4fltk4Item4drawEv__Item_R_CHECK(void *);
void _BCD_R__ZN4fltk4Item4drawEv__Item_R(void *);
int _BCD_R__ZN4fltk4Item6layoutEv__Item_R_CHECK(void *);
void _BCD_R__ZN4fltk4Item6layoutEv__Item_R(void *);
int _BCD_R__ZN4fltk4Item6handleEi__Item_R_CHECK(void *);
int _BCD_R__ZN4fltk4Item6handleEi__Item_R(void *, int _0);
}
class Item_R : fltk::Item {
public:
void *__D_data;
void draw() {
if (_BCD_R__ZN4fltk4Item4drawEv__Item_R_CHECK(__D_data))
_BCD_R__ZN4fltk4Item4drawEv__Item_R(__D_data);
else
fltk::Item::draw();
}
void layout() {
if (_BCD_R__ZN4fltk4Item6layoutEv__Item_R_CHECK(__D_data))
_BCD_R__ZN4fltk4Item6layoutEv__Item_R(__D_data);
else
fltk::Item::layout();
}
int handle(int _0) {
if (_BCD_R__ZN4fltk4Item6handleEi__Item_R_CHECK(__D_data))
return _BCD_R__ZN4fltk4Item6handleEi__Item_R(__D_data, _0);
else
return fltk::Item::handle(_0);
}
Item_R(char const * label) : fltk::Item(label) {}
Item_R(char const * label, fltk::Symbol const * _1) : fltk::Item(label, _1) {}
Item_R(char const * label, int shortcut, _BCD__159_Callback callback, void * user_data_, int flags) : fltk::Item(label, shortcut, callback, user_data_, flags) {}
};
extern "C" {
Item_R *_BCD_new__ZN4fltk4ItemC1EPKc_R(char const * label) {
return new Item_R(label);
}
Item_R *_BCD_new__ZN4fltk4ItemC1EPKcPKNS_6SymbolE_R(char const * label, fltk::Symbol const * _1) {
return new Item_R(label, _1);
}
Item_R *_BCD_new__ZN4fltk4ItemC1EPKciPFvPNS_6WidgetEPvES5_i_R(char const * label, int shortcut, _BCD__159_Callback callback, void * user_data_, int flags) {
return new Item_R(label, shortcut, callback, user_data_, flags);
}
void _BCD_delete_N4fltk4ItemE__Item_R(Item_R *This) {
delete This;
}
void _BCD_RI_N4fltk4ItemE(Item_R *cd, void *dd) {
cd->__D_data = dd;
}
typedef void (*_BCD_func__152)(fltk::Widget *, long int);
typedef _BCD_func__152 _BCD__153_Callback1;
typedef void (*_BCD_func__154)(fltk::Widget *);
typedef _BCD_func__154 _BCD__155_Callback0;
typedef _BCD__159_Callback _BCD__157_Callback_p;
typedef bool (*_BCD_func__265)();
typedef _BCD_func__265 _BCD__170_Theme;
typedef fltk::Symbol * _BCD__223_Box;
typedef unsigned int _BCD__240_Color;
typedef int _BCD__243_Flags;
typedef _BCD__243_Flags _BCD__242_Align;
}
