/* THIS FILE GENERATED BY bcd.gen */
module bcd.fltk2.TiledImage;
align(4):
public import bcd.bind;
public import bcd.fltk2.Symbol;
public import bcd.fltk2.FL_API;
public import bcd.fltk2.PixelType;
public import bcd.fltk2.Rectangle;
public import bcd.fltk2.Color;
public import bcd.fltk2.Flags;
extern (C) void _BCD_delete_N4fltk10TiledImageE(void *);
extern (C) void *_BCD_new__ZN4fltk10TiledImageC1EPNS_6SymbolE(void *);
extern (C) Symbol * _BCD__ZNK4fltk10TiledImage5imageEv(void *This);
extern (C) void _BCD__ZN4fltk10TiledImage5imageEPKNS_6SymbolE(void *This, void *);
extern (C) void _BCD__ZNK4fltk10TiledImage8_measureERiS1_(void *This, int *, int *);
extern (C) void _BCD__ZNK4fltk10TiledImage5_drawERKNS_9RectangleE(void *This, void *);
extern (C) void _BCD_RI_N4fltk10TiledImageE(void *cd, void *dd);
extern (C) void _BCD_delete_N4fltk10TiledImageE__TiledImage_R(void *This);
extern (C) void *_BCD_new__ZN4fltk10TiledImageC1EPNS_6SymbolE_R(void *);
extern (C) int _BCD_R__ZNK4fltk10TiledImage8_measureERiS1___TiledImage_R_CHECK(TiledImage_R x) {
union dp {
void delegate(int *, int *) d;
struct { void *o; void *f; }
}
dp d; d.d = &x._measure;
return cast(int) (d.f != &TiledImage._measure);
}
extern (C) void _BCD_R__ZNK4fltk10TiledImage8_measureERiS1___TiledImage_R(TiledImage_R __D_class, int * w, int * h) {
__D_class._measure(w, h);
}
extern (C) int _BCD_R__ZNK4fltk10TiledImage5_drawERKNS_9RectangleE__TiledImage_R_CHECK(TiledImage_R x) {
union dp {
void delegate(Rectangle) d;
struct { void *o; void *f; }
}
dp d; d.d = &x._draw;
return cast(int) (d.f != &TiledImage._draw);
}
extern (C) void _BCD_R__ZNK4fltk10TiledImage5_drawERKNS_9RectangleE__TiledImage_R(TiledImage_R __D_class, void *_0) {
__D_class._draw(cast(Rectangle) new Rectangle(cast(ifloat) 0, _0));
}
class TiledImage : Symbol {
this(ifloat ignore) {
super(ignore);
}
this(ifloat ignore, void *x) {
super(ignore);
__C_data = x;
__C_data_owned = false;
}
~this() {
if (__C_data && __C_data_owned) _BCD_delete_N4fltk10TiledImageE(__C_data);
__C_data = null;
}
this(Symbol * i) {
super(cast(ifloat) 0);
__C_data = _BCD_new__ZN4fltk10TiledImageC1EPNS_6SymbolE(i.__C_data);
__C_data_owned = true;
}
Symbol * image() {
return _BCD__ZNK4fltk10TiledImage5imageEv(__C_data);
}
void image(Symbol * i) {
_BCD__ZN4fltk10TiledImage5imageEPKNS_6SymbolE(__C_data, i.__C_data);
}
void _measure(int * w, int * h) {
_BCD__ZNK4fltk10TiledImage8_measureERiS1_(__C_data, w, h);
}
void _draw(Rectangle _0) {
_BCD__ZNK4fltk10TiledImage5_drawERKNS_9RectangleE(__C_data, _0.__C_data);
}
}
class TiledImage_R : TiledImage {
~this() {
if (__C_data && __C_data_owned) _BCD_delete_N4fltk10TiledImageE__TiledImage_R(__C_data);
__C_data = null;
}
this(Symbol * i) {
super(cast(ifloat) 0);
__C_data = _BCD_new__ZN4fltk10TiledImageC1EPNS_6SymbolE_R(i.__C_data);
__C_data_owned = true;
_BCD_RI_N4fltk10TiledImageE(__C_data, cast(void *) this);
}
}
