/* THIS FILE GENERATED BY bcd.gen */
#include <stdlib.h>
#include <string.h>
#include "../bind.h"
#include "fltk/ValueOutput.h"
extern "C" {
typedef unsigned char _BCD__8_uchar;
void _BCD_delete_N4fltk11ValueOutputE(fltk::ValueOutput *This) {
delete This;
}
void _BCD__ZN4fltk11ValueOutput4drawEv(fltk::ValueOutput *This) {
(This->draw());
}
int _BCD__ZN4fltk11ValueOutput6handleEi(fltk::ValueOutput *This, int _0) {
return (This->handle(_0));
}
fltk::ValueOutput *_BCD_new__ZN4fltk11ValueOutputC1EiiiiPKc(int x, int y, int w, int h, char const * l) {
return new fltk::ValueOutput(x, y, w, h, l);
}
int _BCD_R__ZN4fltk11ValueOutput4drawEv__ValueOutput_R_CHECK(void *);
void _BCD_R__ZN4fltk11ValueOutput4drawEv__ValueOutput_R(void *);
int _BCD_R__ZN4fltk11ValueOutput6handleEi__ValueOutput_R_CHECK(void *);
int _BCD_R__ZN4fltk11ValueOutput6handleEi__ValueOutput_R(void *, int _0);
}
class ValueOutput_R : fltk::ValueOutput {
public:
void *__D_data;
void draw() {
if (_BCD_R__ZN4fltk11ValueOutput4drawEv__ValueOutput_R_CHECK(__D_data))
_BCD_R__ZN4fltk11ValueOutput4drawEv__ValueOutput_R(__D_data);
else
fltk::ValueOutput::draw();
}
int handle(int _0) {
if (_BCD_R__ZN4fltk11ValueOutput6handleEi__ValueOutput_R_CHECK(__D_data))
return _BCD_R__ZN4fltk11ValueOutput6handleEi__ValueOutput_R(__D_data, _0);
else
return fltk::ValueOutput::handle(_0);
}
ValueOutput_R(int x, int y, int w, int h, char const * l) : fltk::ValueOutput(x, y, w, h, l) {}
};
extern "C" {
ValueOutput_R *_BCD_new__ZN4fltk11ValueOutputC1EiiiiPKc_R(int x, int y, int w, int h, char const * l) {
return new ValueOutput_R(x, y, w, h, l);
}
void _BCD_delete_N4fltk11ValueOutputE__ValueOutput_R(ValueOutput_R *This) {
delete This;
}
void _BCD_RI_N4fltk11ValueOutputE(ValueOutput_R *cd, void *dd) {
cd->__D_data = dd;
}
typedef void (*_BCD_func__154)(fltk::Widget *, long int);
typedef _BCD_func__154 _BCD__155_Callback1;
typedef void (*_BCD_func__156)(fltk::Widget *);
typedef _BCD_func__156 _BCD__157_Callback0;
typedef void (*_BCD_func__160)(fltk::Widget *, void *);
typedef _BCD_func__160 _BCD__161_Callback;
typedef _BCD__161_Callback _BCD__159_Callback_p;
typedef bool (*_BCD_func__288)();
typedef _BCD_func__288 _BCD__172_Theme;
typedef fltk::Symbol * _BCD__225_Box;
typedef unsigned int _BCD__242_Color;
typedef int _BCD__245_Flags;
typedef _BCD__245_Flags _BCD__244_Align;
}
