// generated by Fast Light User Interface Designer (fluid) version 1.0107

import bcd.fltk.Fl;
import bcd.fltk.Fl_Double_Window;
import bcd.fltk.Fl_Button;

int main() {
  Fl_Double_Window w;
  { Fl_Double_Window o = new Fl_Double_Window(285, 85, null);
    w = o;
    new Fl_Button(0, 0, 285, 85, "FLTK in D!");
    o.end();
  }
  w.show();
  return bcd.fltk.Fl.Fl.run();
}
