/* THIS FILE GENERATED BY bcd.gen */
module bcd.libxml2.relaxng;
align(4):
public import bcd.libxml2.hash;
public import bcd.libxml2.parser;
public import bcd.libxml2.xmlIO;
public import bcd.libxml2.globals;
public import bcd.libxml2.threads;
public import bcd.libxml2.xmlmemory;
public import bcd.libxml2.SAX2;
public import bcd.libxml2.SAX;
public import bcd.libxml2.xlink;
public import bcd.libxml2.encoding;
public import bcd.libxml2.entities;
public import bcd.libxml2.valid;
public import bcd.libxml2.xmlautomata;
public import bcd.libxml2.list;
public import bcd.libxml2.xmlerror;
public import bcd.libxml2.tree;
public import bcd.libxml2.xmlregexp;
public import bcd.libxml2.dict;
public import bcd.libxml2.xmlstring;
public import bcd.libxml2.xmlversion;
enum xmlRelaxNGParserFlag {
XML_RELAXNGP_NONE=0,
XML_RELAXNGP_FREE_DOC=1,
XML_RELAXNGP_CRNG=2,
}
enum xmlRelaxNGValidErr {
XML_RELAXNG_OK=0,
XML_RELAXNG_ERR_MEMORY=1,
XML_RELAXNG_ERR_TYPE=2,
XML_RELAXNG_ERR_TYPEVAL=3,
XML_RELAXNG_ERR_DUPID=4,
XML_RELAXNG_ERR_TYPECMP=5,
XML_RELAXNG_ERR_NOSTATE=6,
XML_RELAXNG_ERR_NODEFINE=7,
XML_RELAXNG_ERR_LISTEXTRA=8,
XML_RELAXNG_ERR_LISTEMPTY=9,
XML_RELAXNG_ERR_INTERNODATA=10,
XML_RELAXNG_ERR_INTERSEQ=11,
XML_RELAXNG_ERR_INTEREXTRA=12,
XML_RELAXNG_ERR_ELEMNAME=13,
XML_RELAXNG_ERR_ATTRNAME=14,
XML_RELAXNG_ERR_ELEMNONS=15,
XML_RELAXNG_ERR_ATTRNONS=16,
XML_RELAXNG_ERR_ELEMWRONGNS=17,
XML_RELAXNG_ERR_ATTRWRONGNS=18,
XML_RELAXNG_ERR_ELEMEXTRANS=19,
XML_RELAXNG_ERR_ATTREXTRANS=20,
XML_RELAXNG_ERR_ELEMNOTEMPTY=21,
XML_RELAXNG_ERR_NOELEM=22,
XML_RELAXNG_ERR_NOTELEM=23,
XML_RELAXNG_ERR_ATTRVALID=24,
XML_RELAXNG_ERR_CONTENTVALID=25,
XML_RELAXNG_ERR_EXTRACONTENT=26,
XML_RELAXNG_ERR_INVALIDATTR=27,
XML_RELAXNG_ERR_DATAELEM=28,
XML_RELAXNG_ERR_VALELEM=29,
XML_RELAXNG_ERR_LISTELEM=30,
XML_RELAXNG_ERR_DATATYPE=31,
XML_RELAXNG_ERR_VALUE=32,
XML_RELAXNG_ERR_LIST=33,
XML_RELAXNG_ERR_NOGRAMMAR=34,
XML_RELAXNG_ERR_EXTRADATA=35,
XML_RELAXNG_ERR_LACKDATA=36,
XML_RELAXNG_ERR_INTERNAL=37,
XML_RELAXNG_ERR_ELEMWRONG=38,
XML_RELAXNG_ERR_TEXTWRONG=39,
}
alias void xmlRelaxNGValidCtxt;
alias void * xmlRelaxNGValidCtxtPtr;
alias void xmlRelaxNGParserCtxt;
alias void * xmlRelaxNGParserCtxtPtr;
alias void function(void *, char *, ...) _BCD_func__1689;
alias _BCD_func__1689 xmlRelaxNGValidityWarningFunc;
alias _BCD_func__1689 xmlRelaxNGValidityErrorFunc;
alias void xmlRelaxNG;
alias void * xmlRelaxNGPtr;
extern (C) int xmlRelaxNGValidateFullElement(void *, _xmlDoc *, _xmlNode *);
extern (C) int xmlRelaxNGValidatePopElement(void *, _xmlDoc *, _xmlNode *);
extern (C) int xmlRelaxNGValidatePushCData(void *, char *, int);
extern (C) int xmlRelaxNGValidatePushElement(void *, _xmlDoc *, _xmlNode *);
extern (C) int xmlRelaxNGValidateDoc(void *, _xmlDoc *);
extern (C) void xmlRelaxNGFreeValidCtxt(void *);
extern (C) void * xmlRelaxNGNewValidCtxt(void *);
alias void function(void *, _xmlError *) _BCD_func__2016;
extern (C) void xmlRelaxNGSetValidStructuredErrors(void *, _BCD_func__2016, void *);
extern (C) int xmlRelaxNGGetValidErrors(void *, _BCD_func__1689 *, _BCD_func__1689 *, void * *);
extern (C) void xmlRelaxNGSetValidErrors(void *, _BCD_func__1689, _BCD_func__1689, void *);
extern (C) void xmlRelaxNGDumpTree(_IO_FILE *, void *);
extern (C) void xmlRelaxNGDump(_IO_FILE *, void *);
extern (C) void xmlRelaxNGFree(void *);
extern (C) void * xmlRelaxNGParse(void *);
extern (C) int xmlRelaxNGGetParserErrors(void *, _BCD_func__1689 *, _BCD_func__1689 *, void * *);
extern (C) void xmlRelaxNGSetParserErrors(void *, _BCD_func__1689, _BCD_func__1689, void *);
extern (C) void xmlRelaxNGFreeParserCtxt(void *);
extern (C) int xmlRelaxParserSetFlag(void *, int);
extern (C) void * xmlRelaxNGNewDocParserCtxt(_xmlDoc *);
extern (C) void * xmlRelaxNGNewMemParserCtxt(char *, int);
extern (C) void * xmlRelaxNGNewParserCtxt(char *);
extern (C) void xmlRelaxNGCleanupTypes();
extern (C) int xmlRelaxNGInitTypes();
alias void function(void *, void *, char *, char *, char *) _BCD_func__1690;
alias void function(void *, void *, char *) _BCD_func__1691;
alias void * function(void *, char *) _BCD_func__1692;
alias void function(void *, char *) _BCD_func__1693;
alias void function(_xmlNode *) _BCD_func__1743;
alias _xmlOutputBuffer * function(char *, _xmlCharEncodingHandler *, int) _BCD_func__1744;
alias _xmlParserInputBuffer * function(char *, int) _BCD_func__1745;
alias char * function(char *) _BCD_func__1750;
alias void * function(void *, uint) _BCD_func__1751;
alias void * function(uint) _BCD_func__1752;
alias void function(void *) _BCD_func__1753;
alias void function(void *, _xmlNode *, int, char * *, char * *, int, char * *, char * *) _BCD_func__1760;
alias void function(void *, _xmlNode *, int, char * *, char * *, int, char * *, char * *, int *, int *, int, char * *, char * *) _BCD_func__1761;
alias void function(void *, _xmlNode *, char *, char *, char *) _BCD_func__1762;
alias void function(void *, _xmlNode *) _BCD_func__1763;
alias int function(void *, void *) _BCD_func__1780;
alias int function(void *) _BCD_func__1431;
alias int function(void *, char *, int) _BCD_func__1923;
alias void * function(char *) _BCD_func__1924;
alias int function(char *) _BCD_func__1925;
alias int function(void *, char *, int) _BCD_func__1926;
alias int function(char *, int *, char *, int *) _BCD_func__1936;
alias _xmlParserInput * function(char *, char *, _xmlParserCtxt *) _BCD_func__1939;
alias void function(void *, char *, char *, char *) _BCD_func__1970;
alias void function(void *, char *, char *, char *, int, char * *, int, int, char * *) _BCD_func__1971;
alias void function(void *, char *, int) _BCD_func__1972;
alias void function(void *, char *) _BCD_func__1973;
alias void function(void *, char *, char *) _BCD_func__1974;
alias void function(void *, char *, char * *) _BCD_func__1975;
alias void function(void *, _xmlSAXLocator *) _BCD_func__1976;
alias void function(void *, char *, char *, char *, char *) _BCD_func__1977;
alias void function(void *, char *, int, _xmlElementContent *) _BCD_func__1978;
alias void function(void *, char *, char *, int, int, char *, _xmlEnumeration *) _BCD_func__1979;
alias void function(void *, char *, int, char *, char *, char *) _BCD_func__1980;
alias _xmlEntity * function(void *, char *) _BCD_func__1981;
alias _xmlParserInput * function(void *, char *, char *) _BCD_func__1982;
alias void function(char *) _BCD_func__1995;
alias void function(void *) _BCD_func__2015;
alias void function(void *, char *, void *, void *) _BCD_func__2150;
alias int function(void *, long *, int) _BCD_func__1433;
alias int function(void *, char *, uint) _BCD_func__1435;
alias int function(void *, char *, uint) _BCD_func__1437;
alias int function(void * *, char *) _BCD_func__2422;
alias int function(char *, char * * *, uint *) _BCD_func__2423;
alias int function(void *, char *, char *, char *, char *) _BCD_func__2424;
