/* THIS FILE GENERATED BY bcd.gen */
module bcd.fltk.Fl_Help_View;
public import bcd.bind;
public import bcd.fltk.Fl_Shared_Image;
public import bcd.fltk.Fl_Image;
public import bcd.fltk.fl_draw;
public import bcd.fltk.Fl_Scrollbar;
public import bcd.fltk.Fl_Slider;
public import bcd.fltk.Fl_Valuator;
public import bcd.fltk.Fl_Group;
public import bcd.fltk.Fl_Widget;
public import bcd.fltk.Fl;
public import bcd.fltk.Enumerations;
extern (C) void _BCD_delete_12Fl_Help_View(void *);
extern (C) void *_BCD_new__ZN12Fl_Help_ViewC1EiiiiPKc(int, int, int, int, char *);
extern (C) char * _BCD__ZNK12Fl_Help_View9directoryEv(void *This);
extern (C) char * _BCD__ZNK12Fl_Help_View8filenameEv(void *This);
extern (C) int _BCD__ZN12Fl_Help_View4findEPKci(void *This, char *, int);
alias char * function(Fl_Widget *, char *) _BCD_func__8;
alias _BCD_func__8 Fl_Help_Func;
extern (C) void _BCD__ZN12Fl_Help_View4linkEPFPKcP9Fl_WidgetS1_E(void *This, _BCD_func__8);
extern (C) int _BCD__ZN12Fl_Help_View4loadEPKc(void *This, char *);
extern (C) void _BCD__ZN12Fl_Help_View6resizeEiiii(void *This, int, int, int, int);
extern (C) int _BCD__ZNK12Fl_Help_View4sizeEv(void *This);
extern (C) void _BCD__ZN12Fl_Help_View4sizeEii(void *This, int, int);
extern (C) void _BCD__ZN12Fl_Help_View9textcolorE8Fl_Color(void *This, int);
extern (C) int _BCD__ZNK12Fl_Help_View9textcolorEv(void *This);
extern (C) void _BCD__ZN12Fl_Help_View8textfontEh(void *This, char);
extern (C) char _BCD__ZNK12Fl_Help_View8textfontEv(void *This);
extern (C) void _BCD__ZN12Fl_Help_View8textsizeEh(void *This, char);
extern (C) char _BCD__ZNK12Fl_Help_View8textsizeEv(void *This);
extern (C) char * _BCD__ZN12Fl_Help_View5titleEv(void *This);
extern (C) void _BCD__ZN12Fl_Help_View7toplineEPKc(void *This, char *);
extern (C) void _BCD__ZN12Fl_Help_View7toplineEi(void *This, int);
extern (C) int _BCD__ZNK12Fl_Help_View7toplineEv(void *This);
extern (C) void _BCD__ZN12Fl_Help_View8leftlineEi(void *This, int);
extern (C) int _BCD__ZNK12Fl_Help_View8leftlineEv(void *This);
extern (C) void _BCD__ZN12Fl_Help_View5valueEPKc(void *This, char *);
extern (C) char * _BCD__ZNK12Fl_Help_View5valueEv(void *This);
extern (C) void _BCD_RI_12Fl_Help_View(void *cd, void *dd);
extern (C) void _BCD_delete_12Fl_Help_View__Fl_Help_View_R(void *This);
extern (C) void *_BCD_new__ZN12Fl_Help_ViewC1EiiiiPKc_R(int, int, int, int, char *);
extern (C) int _BCD_R__ZN12Fl_Help_View6resizeEiiii__Fl_Help_View_R_CHECK(Fl_Help_View_R x) {
union dp {
void delegate(int, int, int, int) d;
struct { void *o; void *f; }
}
dp d; d.d = &x.resize;
return cast(int) (d.f != &Fl_Help_View.resize);
}
extern (C) void _BCD_R__ZN12Fl_Help_View6resizeEiiii__Fl_Help_View_R(Fl_Help_View_R __D_class, int _0, int _1, int _2, int _3) {
__D_class.resize(_0, _1, _2, _3);
}
extern (C) void _BCD_delete_14Fl_Help_Target(void *);
extern (C) void _BCD_set__ZN14Fl_Help_Target1yE(void *, int);
extern (C) int _BCD_get__ZN14Fl_Help_Target1yE(void *);
extern (C) void _BCD_RI_14Fl_Help_Target(void *cd, void *dd);
extern (C) void _BCD_delete_14Fl_Help_Target__Fl_Help_Target_R(void *This);
extern (C) void _BCD_delete_12Fl_Help_Link(void *);
extern (C) void _BCD_set__ZN12Fl_Help_Link1xE(void *, int);
extern (C) int _BCD_get__ZN12Fl_Help_Link1xE(void *);
extern (C) void _BCD_set__ZN12Fl_Help_Link1yE(void *, int);
extern (C) int _BCD_get__ZN12Fl_Help_Link1yE(void *);
extern (C) void _BCD_set__ZN12Fl_Help_Link1wE(void *, int);
extern (C) int _BCD_get__ZN12Fl_Help_Link1wE(void *);
extern (C) void _BCD_set__ZN12Fl_Help_Link1hE(void *, int);
extern (C) int _BCD_get__ZN12Fl_Help_Link1hE(void *);
extern (C) void _BCD_RI_12Fl_Help_Link(void *cd, void *dd);
extern (C) void _BCD_delete_12Fl_Help_Link__Fl_Help_Link_R(void *This);
extern (C) void _BCD_delete_13Fl_Help_Block(void *);
extern (C) void _BCD_set__ZN13Fl_Help_Block5startE(void *, char *);
extern (C) char * _BCD_get__ZN13Fl_Help_Block5startE(void *);
extern (C) void _BCD_set__ZN13Fl_Help_Block3endE(void *, char *);
extern (C) char * _BCD_get__ZN13Fl_Help_Block3endE(void *);
extern (C) void _BCD_set__ZN13Fl_Help_Block6borderE(void *, char);
extern (C) char _BCD_get__ZN13Fl_Help_Block6borderE(void *);
extern (C) void _BCD_set__ZN13Fl_Help_Block7bgcolorE(void *, int);
extern (C) int _BCD_get__ZN13Fl_Help_Block7bgcolorE(void *);
extern (C) void _BCD_set__ZN13Fl_Help_Block1xE(void *, int);
extern (C) int _BCD_get__ZN13Fl_Help_Block1xE(void *);
extern (C) void _BCD_set__ZN13Fl_Help_Block1yE(void *, int);
extern (C) int _BCD_get__ZN13Fl_Help_Block1yE(void *);
extern (C) void _BCD_set__ZN13Fl_Help_Block1wE(void *, int);
extern (C) int _BCD_get__ZN13Fl_Help_Block1wE(void *);
extern (C) void _BCD_set__ZN13Fl_Help_Block1hE(void *, int);
extern (C) int _BCD_get__ZN13Fl_Help_Block1hE(void *);
extern (C) void _BCD_RI_13Fl_Help_Block(void *cd, void *dd);
extern (C) void _BCD_delete_13Fl_Help_Block__Fl_Help_Block_R(void *This);
alias Fl_Image * function(char *, char *, int) _BCD_func__691;
alias void function(void *, int, int, int, char *) _BCD_func__717;
alias void function(Fl_Widget *, int) _BCD_func__126;
alias void function(Fl_Widget *) _BCD_func__128;
alias void function(Fl_Widget *, void *) _BCD_func__132;
alias void function(void *) _BCD_func__1004;
alias void function(int, int, int, int, int) _BCD_func__138;
alias void function(Fl_Label *, int *, int *) _BCD_func__140;
alias void function(Fl_Label *, int, int, int, int, int) _BCD_func__142;
alias int function(void *) _BCD_func__309;
alias int function(void *, long *, int) _BCD_func__311;
alias int function(void *, char *, uint) _BCD_func__313;
alias int function(void *, char *, uint) _BCD_func__315;
alias int function(void * *, char *) _BCD_func__1242;
alias int function(char *, char * * *, uint *) _BCD_func__1243;
alias int function(void *, char *, char *, char *, char *) _BCD_func__1244;
class Fl_Help_View : Fl_Group {
this(ifloat ignore) {
super(ignore);
}
this(ifloat ignore, void *x) {
super(ignore);
__C_data = x;
__C_data_owned = false;
}
~this() {
if (__C_data && __C_data_owned) _BCD_delete_12Fl_Help_View(__C_data);
__C_data = null;
}
this(int xx, int yy, int ww, int hh, char * l) {
super(cast(ifloat) 0);
__C_data = _BCD_new__ZN12Fl_Help_ViewC1EiiiiPKc(xx, yy, ww, hh, l);
__C_data_owned = true;
}
char * directory() {
return _BCD__ZNK12Fl_Help_View9directoryEv(__C_data);
}
char * filename() {
return _BCD__ZNK12Fl_Help_View8filenameEv(__C_data);
}
int find(char * s, int p) {
return _BCD__ZN12Fl_Help_View4findEPKci(__C_data, s, p);
}
void link(_BCD_func__8 fn) {
_BCD__ZN12Fl_Help_View4linkEPFPKcP9Fl_WidgetS1_E(__C_data, fn);
}
int load(char * f) {
return _BCD__ZN12Fl_Help_View4loadEPKc(__C_data, f);
}
void resize(int _0, int _1, int _2, int _3) {
_BCD__ZN12Fl_Help_View6resizeEiiii(__C_data, _0, _1, _2, _3);
}
int size() {
return _BCD__ZNK12Fl_Help_View4sizeEv(__C_data);
}
void size(int W, int H) {
_BCD__ZN12Fl_Help_View4sizeEii(__C_data, W, H);
}
void textcolor(int c) {
_BCD__ZN12Fl_Help_View9textcolorE8Fl_Color(__C_data, c);
}
int textcolor() {
return _BCD__ZNK12Fl_Help_View9textcolorEv(__C_data);
}
void textfont(char f) {
_BCD__ZN12Fl_Help_View8textfontEh(__C_data, f);
}
char textfont() {
return _BCD__ZNK12Fl_Help_View8textfontEv(__C_data);
}
void textsize(char s) {
_BCD__ZN12Fl_Help_View8textsizeEh(__C_data, s);
}
char textsize() {
return _BCD__ZNK12Fl_Help_View8textsizeEv(__C_data);
}
char * title() {
return _BCD__ZN12Fl_Help_View5titleEv(__C_data);
}
void topline(char * n) {
_BCD__ZN12Fl_Help_View7toplineEPKc(__C_data, n);
}
void topline(int _0) {
_BCD__ZN12Fl_Help_View7toplineEi(__C_data, _0);
}
int topline() {
return _BCD__ZNK12Fl_Help_View7toplineEv(__C_data);
}
void leftline(int _0) {
_BCD__ZN12Fl_Help_View8leftlineEi(__C_data, _0);
}
int leftline() {
return _BCD__ZNK12Fl_Help_View8leftlineEv(__C_data);
}
void value(char * v) {
_BCD__ZN12Fl_Help_View5valueEPKc(__C_data, v);
}
char * value() {
return _BCD__ZNK12Fl_Help_View5valueEv(__C_data);
}
}
class Fl_Help_View_R : Fl_Help_View {
~this() {
if (__C_data && __C_data_owned) _BCD_delete_12Fl_Help_View__Fl_Help_View_R(__C_data);
__C_data = null;
}
this(int xx, int yy, int ww, int hh, char * l) {
super(cast(ifloat) 0);
__C_data = _BCD_new__ZN12Fl_Help_ViewC1EiiiiPKc_R(xx, yy, ww, hh, l);
__C_data_owned = true;
_BCD_RI_12Fl_Help_View(__C_data, cast(void *) this);
}
}
class Fl_Help_Target : bcd.bind.BoundClass {
this(ifloat ignore) {
super(ignore);
}
this(ifloat ignore, void *x) {
super(ignore);
__C_data = x;
__C_data_owned = false;
}
~this() {
if (__C_data && __C_data_owned) _BCD_delete_14Fl_Help_Target(__C_data);
__C_data = null;
}
void set_y(int x) {
_BCD_set__ZN14Fl_Help_Target1yE(__C_data, x);
}
int get_y() {
return _BCD_get__ZN14Fl_Help_Target1yE(__C_data);
}
}
class Fl_Help_Target_R : Fl_Help_Target {
~this() {
if (__C_data && __C_data_owned) _BCD_delete_14Fl_Help_Target__Fl_Help_Target_R(__C_data);
__C_data = null;
}
this() { super(cast(ireal) 0); }
}
class Fl_Help_Link : bcd.bind.BoundClass {
this(ifloat ignore) {
super(ignore);
}
this(ifloat ignore, void *x) {
super(ignore);
__C_data = x;
__C_data_owned = false;
}
~this() {
if (__C_data && __C_data_owned) _BCD_delete_12Fl_Help_Link(__C_data);
__C_data = null;
}
void set_x(int x) {
_BCD_set__ZN12Fl_Help_Link1xE(__C_data, x);
}
int get_x() {
return _BCD_get__ZN12Fl_Help_Link1xE(__C_data);
}
void set_y(int x) {
_BCD_set__ZN12Fl_Help_Link1yE(__C_data, x);
}
int get_y() {
return _BCD_get__ZN12Fl_Help_Link1yE(__C_data);
}
void set_w(int x) {
_BCD_set__ZN12Fl_Help_Link1wE(__C_data, x);
}
int get_w() {
return _BCD_get__ZN12Fl_Help_Link1wE(__C_data);
}
void set_h(int x) {
_BCD_set__ZN12Fl_Help_Link1hE(__C_data, x);
}
int get_h() {
return _BCD_get__ZN12Fl_Help_Link1hE(__C_data);
}
}
class Fl_Help_Link_R : Fl_Help_Link {
~this() {
if (__C_data && __C_data_owned) _BCD_delete_12Fl_Help_Link__Fl_Help_Link_R(__C_data);
__C_data = null;
}
this() { super(cast(ireal) 0); }
}
class Fl_Help_Block : bcd.bind.BoundClass {
this(ifloat ignore) {
super(ignore);
}
this(ifloat ignore, void *x) {
super(ignore);
__C_data = x;
__C_data_owned = false;
}
~this() {
if (__C_data && __C_data_owned) _BCD_delete_13Fl_Help_Block(__C_data);
__C_data = null;
}
void set_start(char * x) {
_BCD_set__ZN13Fl_Help_Block5startE(__C_data, x);
}
char * get_start() {
return _BCD_get__ZN13Fl_Help_Block5startE(__C_data);
}
void set_end(char * x) {
_BCD_set__ZN13Fl_Help_Block3endE(__C_data, x);
}
char * get_end() {
return _BCD_get__ZN13Fl_Help_Block3endE(__C_data);
}
void set_border(char x) {
_BCD_set__ZN13Fl_Help_Block6borderE(__C_data, x);
}
char get_border() {
return _BCD_get__ZN13Fl_Help_Block6borderE(__C_data);
}
void set_bgcolor(int x) {
_BCD_set__ZN13Fl_Help_Block7bgcolorE(__C_data, x);
}
int get_bgcolor() {
return _BCD_get__ZN13Fl_Help_Block7bgcolorE(__C_data);
}
void set_x(int x) {
_BCD_set__ZN13Fl_Help_Block1xE(__C_data, x);
}
int get_x() {
return _BCD_get__ZN13Fl_Help_Block1xE(__C_data);
}
void set_y(int x) {
_BCD_set__ZN13Fl_Help_Block1yE(__C_data, x);
}
int get_y() {
return _BCD_get__ZN13Fl_Help_Block1yE(__C_data);
}
void set_w(int x) {
_BCD_set__ZN13Fl_Help_Block1wE(__C_data, x);
}
int get_w() {
return _BCD_get__ZN13Fl_Help_Block1wE(__C_data);
}
void set_h(int x) {
_BCD_set__ZN13Fl_Help_Block1hE(__C_data, x);
}
int get_h() {
return _BCD_get__ZN13Fl_Help_Block1hE(__C_data);
}
}
class Fl_Help_Block_R : Fl_Help_Block {
~this() {
if (__C_data && __C_data_owned) _BCD_delete_13Fl_Help_Block__Fl_Help_Block_R(__C_data);
__C_data = null;
}
this() { super(cast(ireal) 0); }
}
