/* THIS FILE GENERATED BY bcd.gen */
module bcd.fltk.Fl_Progress;
public import bcd.bind;
public import bcd.fltk.Fl_Widget;
public import bcd.fltk.Enumerations;
extern (C) void _BCD_delete_11Fl_Progress(void *);
extern (C) void *_BCD_new__ZN11Fl_ProgressC1EiiiiPKc(int, int, int, int, char *);
extern (C) void _BCD__ZN11Fl_Progress7maximumEf(void *This, float);
extern (C) float _BCD__ZNK11Fl_Progress7maximumEv(void *This);
extern (C) void _BCD__ZN11Fl_Progress7minimumEf(void *This, float);
extern (C) float _BCD__ZNK11Fl_Progress7minimumEv(void *This);
extern (C) void _BCD__ZN11Fl_Progress5valueEf(void *This, float);
extern (C) float _BCD__ZNK11Fl_Progress5valueEv(void *This);
extern (C) void _BCD_RI_11Fl_Progress(void *cd, void *dd);
extern (C) void _BCD_delete_11Fl_Progress__Fl_Progress_R(void *This);
extern (C) void *_BCD_new__ZN11Fl_ProgressC1EiiiiPKc_R(int, int, int, int, char *);
alias void function(Fl_Widget *, int) _BCD_func__7;
alias void function(Fl_Widget *) _BCD_func__9;
alias void function(Fl_Widget *, void *) _BCD_func__13;
class Fl_Progress : Fl_Widget {
this(ifloat ignore) {
super(ignore);
}
this(ifloat ignore, void *x) {
super(ignore);
__C_data = x;
__C_data_owned = false;
}
~this() {
if (__C_data && __C_data_owned) _BCD_delete_11Fl_Progress(__C_data);
__C_data = null;
}
this(int x, int y, int w, int h, char * l) {
super(cast(ifloat) 0);
__C_data = _BCD_new__ZN11Fl_ProgressC1EiiiiPKc(x, y, w, h, l);
__C_data_owned = true;
}
void maximum(float v) {
_BCD__ZN11Fl_Progress7maximumEf(__C_data, v);
}
float maximum() {
return _BCD__ZNK11Fl_Progress7maximumEv(__C_data);
}
void minimum(float v) {
_BCD__ZN11Fl_Progress7minimumEf(__C_data, v);
}
float minimum() {
return _BCD__ZNK11Fl_Progress7minimumEv(__C_data);
}
void value(float v) {
_BCD__ZN11Fl_Progress5valueEf(__C_data, v);
}
float value() {
return _BCD__ZNK11Fl_Progress5valueEv(__C_data);
}
}
class Fl_Progress_R : Fl_Progress {
~this() {
if (__C_data && __C_data_owned) _BCD_delete_11Fl_Progress__Fl_Progress_R(__C_data);
__C_data = null;
}
this(int x, int y, int w, int h, char * l) {
super(cast(ifloat) 0);
__C_data = _BCD_new__ZN11Fl_ProgressC1EiiiiPKc_R(x, y, w, h, l);
__C_data_owned = true;
_BCD_RI_11Fl_Progress(__C_data, cast(void *) this);
}
}
