/* THIS FILE GENERATED BY bcd.gen */
#include <stdlib.h>
#include <string.h>
#include "../bind.h"
#include "FL/Fl_Preferences.H"
extern "C" {
void _BCD_delete_N14Fl_Preferences4NameE(Fl_Preferences::Name *This) {
delete This;
}
Fl_Preferences::Name *_BCD_new__ZN14Fl_Preferences4NameC1Ej(unsigned int n) {
return new Fl_Preferences::Name(n);
}
Fl_Preferences::Name *_BCD_new__ZN14Fl_Preferences4NameC1EPKcz(char const * format) {
return new Fl_Preferences::Name(format);
}
}
class Name_R : Fl_Preferences::Name {
public:
void *__D_data;
Name_R(unsigned int n) : Fl_Preferences::Name(n) {}
Name_R(char const * format) : Fl_Preferences::Name(format) {}
};
extern "C" {
Name_R *_BCD_new__ZN14Fl_Preferences4NameC1Ej_R(unsigned int n) {
return new Name_R(n);
}
Name_R *_BCD_new__ZN14Fl_Preferences4NameC1EPKcz_R(char const * format) {
return new Name_R(format);
}
void _BCD_delete_N14Fl_Preferences4NameE__Name_R(Name_R *This) {
delete This;
}
void _BCD_RI_N14Fl_Preferences4NameE(Name_R *cd, void *dd) {
cd->__D_data = dd;
}
void _BCD_delete_N14Fl_Preferences5EntryE(Fl_Preferences::Entry *This) {
delete This;
}
void _BCD_set__ZN14Fl_Preferences5Entry4nameE(Fl_Preferences::Entry *This, char * x) {
This->name = x;
}
char * _BCD_get__ZN14Fl_Preferences5Entry4nameE(Fl_Preferences::Entry *This) {
return This->name;
}
void _BCD_set__ZN14Fl_Preferences5Entry5valueE(Fl_Preferences::Entry *This, char * x) {
This->value = x;
}
char * _BCD_get__ZN14Fl_Preferences5Entry5valueE(Fl_Preferences::Entry *This) {
return This->value;
}
}
class Entry_R : Fl_Preferences::Entry {
public:
void *__D_data;
};
extern "C" {
void _BCD_delete_N14Fl_Preferences5EntryE__Entry_R(Entry_R *This) {
delete This;
}
void _BCD_RI_N14Fl_Preferences5EntryE(Entry_R *cd, void *dd) {
cd->__D_data = dd;
}
void _BCD_delete_14Fl_Preferences(Fl_Preferences *This) {
delete This;
}
Fl_Preferences *_BCD_new__ZN14Fl_PreferencesC1ENS_4RootEPKcS2_(enum Fl_Preferences::Root root, char const * vendor, char const * application) {
return new Fl_Preferences(root, vendor, application);
}
Fl_Preferences *_BCD_new__ZN14Fl_PreferencesC1EPKcS1_S1_(char const * path, char const * vendor, char const * application) {
return new Fl_Preferences(path, vendor, application);
}
Fl_Preferences *_BCD_new__ZN14Fl_PreferencesC1ERS_PKc(Fl_Preferences   & _0, char const * group) {
return new Fl_Preferences(_0, group);
}
int _BCD__ZN14Fl_Preferences6groupsEv(Fl_Preferences *This) {
return (This->groups());
}
char const * _BCD__ZN14Fl_Preferences5groupEi(Fl_Preferences *This, int _0) {
return (This->group(_0));
}
char _BCD__ZN14Fl_Preferences11groupExistsEPKc(Fl_Preferences *This, char const * group) {
return (This->groupExists(group));
}
char _BCD__ZN14Fl_Preferences11deleteGroupEPKc(Fl_Preferences *This, char const * group) {
return (This->deleteGroup(group));
}
int _BCD__ZN14Fl_Preferences7entriesEv(Fl_Preferences *This) {
return (This->entries());
}
char const * _BCD__ZN14Fl_Preferences5entryEi(Fl_Preferences *This, int _0) {
return (This->entry(_0));
}
char _BCD__ZN14Fl_Preferences11entryExistsEPKc(Fl_Preferences *This, char const * entry) {
return (This->entryExists(entry));
}
char _BCD__ZN14Fl_Preferences11deleteEntryEPKc(Fl_Preferences *This, char const * entry) {
return (This->deleteEntry(entry));
}
char _BCD__ZN14Fl_Preferences3setEPKci(Fl_Preferences *This, char const * entry, int value) {
return (This->set(entry, value));
}
char _BCD__ZN14Fl_Preferences3setEPKcf(Fl_Preferences *This, char const * entry, float value) {
return (This->set(entry, value));
}
char _BCD__ZN14Fl_Preferences3setEPKcd(Fl_Preferences *This, char const * entry, double value) {
return (This->set(entry, value));
}
char _BCD__ZN14Fl_Preferences3setEPKcS1_(Fl_Preferences *This, char const * entry, char const * value) {
return (This->set(entry, value));
}
char _BCD__ZN14Fl_Preferences3setEPKcPKvi(Fl_Preferences *This, char const * entry, void const * value, int size) {
return (This->set(entry, value, size));
}
char _BCD__ZN14Fl_Preferences3getEPKcRii(Fl_Preferences *This, char const * entry, int & value, int defaultValue) {
return (This->get(entry, value, defaultValue));
}
char _BCD__ZN14Fl_Preferences3getEPKcRff(Fl_Preferences *This, char const * entry, float & value, float defaultValue) {
return (This->get(entry, value, defaultValue));
}
char _BCD__ZN14Fl_Preferences3getEPKcRdd(Fl_Preferences *This, char const * entry, double & value, double defaultValue) {
return (This->get(entry, value, defaultValue));
}
char _BCD__ZN14Fl_Preferences3getEPKcRPcS1_(Fl_Preferences *This, char const * entry, char * & value, char const * defaultValue) {
return (This->get(entry, value, defaultValue));
}
char _BCD__ZN14Fl_Preferences3getEPKcPcS1_i(Fl_Preferences *This, char const * entry, char * value, char const * defaultValue, int maxSize) {
return (This->get(entry, value, defaultValue, maxSize));
}
char _BCD__ZN14Fl_Preferences3getEPKcRPvPKvi(Fl_Preferences *This, char const * entry, void * & value, void const * defaultValue, int defaultSize) {
return (This->get(entry, value, defaultValue, defaultSize));
}
char _BCD__ZN14Fl_Preferences3getEPKcPvPKvii(Fl_Preferences *This, char const * entry, void * value, void const * defaultValue, int defaultSize, int maxSize) {
return (This->get(entry, value, defaultValue, defaultSize, maxSize));
}
int _BCD__ZN14Fl_Preferences4sizeEPKc(Fl_Preferences *This, char const * entry) {
return (This->size(entry));
}
char _BCD__ZN14Fl_Preferences15getUserdataPathEPci(Fl_Preferences *This, char * path, int pathlen) {
return (This->getUserdataPath(path, pathlen));
}
void _BCD__ZN14Fl_Preferences5flushEv(Fl_Preferences *This) {
(This->flush());
}
}
class Fl_Preferences_R : Fl_Preferences {
public:
void *__D_data;
Fl_Preferences_R(enum Fl_Preferences::Root root, char const * vendor, char const * application) : Fl_Preferences(root, vendor, application) {}
Fl_Preferences_R(char const * path, char const * vendor, char const * application) : Fl_Preferences(path, vendor, application) {}
Fl_Preferences_R(Fl_Preferences   & _0, char const * group) : Fl_Preferences(_0, group) {}
};
extern "C" {
Fl_Preferences_R *_BCD_new__ZN14Fl_PreferencesC1ENS_4RootEPKcS2__R(enum Fl_Preferences::Root root, char const * vendor, char const * application) {
return new Fl_Preferences_R(root, vendor, application);
}
Fl_Preferences_R *_BCD_new__ZN14Fl_PreferencesC1EPKcS1_S1__R(char const * path, char const * vendor, char const * application) {
return new Fl_Preferences_R(path, vendor, application);
}
Fl_Preferences_R *_BCD_new__ZN14Fl_PreferencesC1ERS_PKc_R(Fl_Preferences   & _0, char const * group) {
return new Fl_Preferences_R(_0, group);
}
void _BCD_delete_14Fl_Preferences__Fl_Preferences_R(Fl_Preferences_R *This) {
delete This;
}
void _BCD_RI_14Fl_Preferences(Fl_Preferences_R *cd, void *dd) {
cd->__D_data = dd;
}
typedef _G_fpos64_t * _BCD__97_fpos64_t;
typedef _G_fpos_t * _BCD__99_fpos_t;
typedef char * _BCD__148___gnuc_va_list;
typedef _BCD__148___gnuc_va_list _BCD__101_va_list;
typedef _IO_cookie_io_functions_t * _BCD__126_cookie_io_functions_t;
typedef int (*_BCD_func__127)(void *);
typedef _BCD_func__127 _BCD__135___io_close_fn;
typedef _BCD__135___io_close_fn _BCD__128_cookie_close_function_t;
typedef long long int _BCD__232___quad_t;
typedef _BCD__232___quad_t _BCD__222___off64_t;
typedef int (*_BCD_func__129)(void *, _BCD__222___off64_t *, int);
typedef _BCD_func__129 _BCD__136___io_seek_fn;
typedef _BCD__136___io_seek_fn _BCD__130_cookie_seek_function_t;
typedef int _BCD__197___ssize_t;
typedef _BCD__197___ssize_t (*_BCD_func__131)(void *, char const *, unsigned int);
typedef _BCD_func__131 _BCD__137___io_write_fn;
typedef _BCD__137___io_write_fn _BCD__132_cookie_write_function_t;
typedef _BCD__197___ssize_t (*_BCD_func__133)(void *, char *, unsigned int);
typedef _BCD_func__133 _BCD__138___io_read_fn;
typedef _BCD__138___io_read_fn _BCD__134_cookie_read_function_t;
typedef void _BCD__146__IO_lock_t;
typedef unsigned int _BCD__150__G_uint32_t;
typedef short unsigned int _BCD__152__G_uint16_t;
typedef int _BCD__154__G_int32_t;
typedef short int _BCD__156__G_int16_t;
typedef __gconv_info * _BCD__159___gconv_t;
typedef void (*_BCD_func__480)(void *);
typedef _BCD_func__480 _BCD__162___gconv_trans_end_fct;
typedef int (*_BCD_func__481)(void * *, char const *);
typedef _BCD_func__481 _BCD__164___gconv_trans_init_fct;
typedef unsigned int _BCD__247_size_t;
typedef int (*_BCD_func__482)(char const *, char const * * *, _BCD__247_size_t *);
typedef _BCD_func__482 _BCD__166___gconv_trans_query_fct;
typedef int (*_BCD_func__483)(void *, unsigned char const *, unsigned char const *, unsigned char *, unsigned char *);
typedef _BCD_func__483 _BCD__168___gconv_trans_context_fct;
typedef int (*_BCD_func__484)(__gconv_step *, __gconv_step_data *, void *, unsigned char const *, unsigned char const * *, unsigned char const *, unsigned char * *, _BCD__247_size_t *);
typedef _BCD_func__484 _BCD__170___gconv_trans_fct;
typedef void (*_BCD_func__485)(__gconv_step *);
typedef _BCD_func__485 _BCD__172___gconv_end_fct;
typedef int (*_BCD_func__486)(__gconv_step *);
typedef _BCD_func__486 _BCD__174___gconv_init_fct;
typedef unsigned int _BCD__186_wint_t;
typedef _BCD__186_wint_t (*_BCD_func__487)(__gconv_step *, unsigned char);
typedef _BCD_func__487 _BCD__176___gconv_btowc_fct;
typedef int (*_BCD_func__488)(__gconv_step *, __gconv_step_data *, unsigned char const * *, unsigned char const *, unsigned char * *, _BCD__247_size_t *, int, int);
typedef _BCD_func__488 _BCD__178___gconv_fct;
typedef _IO_FILE * _BCD__188___FILE;
typedef _IO_FILE * _BCD__189_FILE;
typedef unsigned int _BCD__190___socklen_t;
typedef int _BCD__191___intptr_t;
typedef char * _BCD__192___caddr_t;
typedef _BCD__232___quad_t * _BCD__194___qaddr_t;
typedef _BCD__222___off64_t _BCD__196___loff_t;
typedef long long unsigned int _BCD__231___u_quad_t;
typedef _BCD__231___u_quad_t _BCD__199___fsfilcnt64_t;
typedef long unsigned int _BCD__201___fsfilcnt_t;
typedef _BCD__231___u_quad_t _BCD__202___fsblkcnt64_t;
typedef long unsigned int _BCD__203___fsblkcnt_t;
typedef _BCD__232___quad_t _BCD__204___blkcnt64_t;
typedef long int _BCD__206___blkcnt_t;
typedef long int _BCD__207___blksize_t;
typedef int _BCD__208___timer_t;
typedef int _BCD__209___clockid_t;
typedef int _BCD__210___key_t;
typedef long int _BCD__211___swblk_t;
typedef int _BCD__212___daddr_t;
typedef long int _BCD__213___suseconds_t;
typedef unsigned int _BCD__214___useconds_t;
typedef long int _BCD__215___time_t;
typedef unsigned int _BCD__216___id_t;
typedef _BCD__231___u_quad_t _BCD__217___rlim64_t;
typedef long unsigned int _BCD__218___rlim_t;
typedef long int _BCD__219___clock_t;
typedef int _BCD__221___pid_t;
typedef long int _BCD__223___off_t;
typedef unsigned int _BCD__224___nlink_t;
typedef unsigned int _BCD__225___mode_t;
typedef _BCD__231___u_quad_t _BCD__226___ino64_t;
typedef long unsigned int _BCD__227___ino_t;
typedef unsigned int _BCD__228___gid_t;
typedef unsigned int _BCD__229___uid_t;
typedef _BCD__231___u_quad_t _BCD__230___dev_t;
typedef long long unsigned int _BCD__233___uint64_t;
typedef long long int _BCD__234___int64_t;
typedef unsigned int _BCD__235___uint32_t;
typedef int _BCD__236___int32_t;
typedef short unsigned int _BCD__237___uint16_t;
typedef short int _BCD__238___int16_t;
typedef unsigned char _BCD__240___uint8_t;
typedef signed char _BCD__242___int8_t;
typedef long unsigned int _BCD__243___u_long;
typedef unsigned int _BCD__244___u_int;
typedef short unsigned int _BCD__245___u_short;
typedef unsigned char _BCD__246___u_char;
}
