/* THIS FILE GENERATED BY bcd.gen */
module bcd.fltk.Fl_Select_Browser;
public import bcd.bind;
public import bcd.fltk.Fl_Browser;
public import bcd.fltk.Fl_Browser_;
public import bcd.fltk.Fl_Scrollbar;
public import bcd.fltk.Fl_Slider;
public import bcd.fltk.Fl_Valuator;
public import bcd.fltk.Fl_Group;
public import bcd.fltk.Fl_Widget;
public import bcd.fltk.Enumerations;
extern (C) void _BCD_delete_17Fl_Select_Browser(void *);
extern (C) void *_BCD_new__ZN17Fl_Select_BrowserC1EiiiiPKc(int, int, int, int, char *);
extern (C) void _BCD_RI_17Fl_Select_Browser(void *cd, void *dd);
extern (C) void _BCD_delete_17Fl_Select_Browser__Fl_Select_Browser_R(void *This);
extern (C) void *_BCD_new__ZN17Fl_Select_BrowserC1EiiiiPKc_R(int, int, int, int, char *);
alias void function(Fl_Widget *, int) _BCD_func__20;
alias void function(Fl_Widget *) _BCD_func__22;
alias void function(Fl_Widget *, void *) _BCD_func__26;
class Fl_Select_Browser : Fl_Browser {
this(ifloat ignore) {
super(ignore);
}
this(ifloat ignore, void *x) {
super(ignore);
__C_data = x;
__C_data_owned = false;
}
~this() {
if (__C_data && __C_data_owned) _BCD_delete_17Fl_Select_Browser(__C_data);
__C_data = null;
}
this(int X, int Y, int W, int H, char * l) {
super(cast(ifloat) 0);
__C_data = _BCD_new__ZN17Fl_Select_BrowserC1EiiiiPKc(X, Y, W, H, l);
__C_data_owned = true;
}
}
class Fl_Select_Browser_R : Fl_Select_Browser {
~this() {
if (__C_data && __C_data_owned) _BCD_delete_17Fl_Select_Browser__Fl_Select_Browser_R(__C_data);
__C_data = null;
}
this(int X, int Y, int W, int H, char * l) {
super(cast(ifloat) 0);
__C_data = _BCD_new__ZN17Fl_Select_BrowserC1EiiiiPKc_R(X, Y, W, H, l);
__C_data_owned = true;
_BCD_RI_17Fl_Select_Browser(__C_data, cast(void *) this);
}
}
