/* THIS FILE GENERATED BY bcd.gen */
#include <stdlib.h>
#include <string.h>
#include "../bind.h"
#include "FL/Fl_Scrollbar.H"
extern "C" {
void _BCD_delete_12Fl_Scrollbar(Fl_Scrollbar *This) {
delete This;
}
Fl_Scrollbar *_BCD_new__ZN12Fl_ScrollbarC1EiiiiPKc(int x, int y, int w, int h, char const * l) {
return new Fl_Scrollbar(x, y, w, h, l);
}
int _BCD__ZN12Fl_Scrollbar6handleEi(Fl_Scrollbar *This, int _0) {
return (This->handle(_0));
}
int _BCD__ZN12Fl_Scrollbar5valueEiiii(Fl_Scrollbar *This, int p, int s, int top, int total) {
return (This->value(p, s, top, total));
}
int _BCD__ZNK12Fl_Scrollbar8linesizeEv(Fl_Scrollbar *This) {
return (This->linesize());
}
void _BCD__ZN12Fl_Scrollbar8linesizeEi(Fl_Scrollbar *This, int i) {
(This->linesize(i));
}
int _BCD_R__ZN12Fl_Scrollbar6handleEi__Fl_Scrollbar_R_CHECK(void *);
int _BCD_R__ZN12Fl_Scrollbar6handleEi__Fl_Scrollbar_R(void *, int _0);
}
class Fl_Scrollbar_R : Fl_Scrollbar {
public:
void *__D_data;
Fl_Scrollbar_R(int x, int y, int w, int h, char const * l) : Fl_Scrollbar(x, y, w, h, l) {}
int handle(int _0) {
if (_BCD_R__ZN12Fl_Scrollbar6handleEi__Fl_Scrollbar_R_CHECK(__D_data))
return _BCD_R__ZN12Fl_Scrollbar6handleEi__Fl_Scrollbar_R(__D_data, _0);
else
return Fl_Scrollbar::handle(_0);
}
};
extern "C" {
Fl_Scrollbar_R *_BCD_new__ZN12Fl_ScrollbarC1EiiiiPKc_R(int x, int y, int w, int h, char const * l) {
return new Fl_Scrollbar_R(x, y, w, h, l);
}
void _BCD_delete_12Fl_Scrollbar__Fl_Scrollbar_R(Fl_Scrollbar_R *This) {
delete This;
}
void _BCD_RI_12Fl_Scrollbar(Fl_Scrollbar_R *cd, void *dd) {
cd->__D_data = dd;
}
typedef void (*_BCD_func__11)(Fl_Widget *, long int);
typedef _BCD_func__11 _BCD__12_Fl_Callback1;
typedef void (*_BCD_func__13)(Fl_Widget *);
typedef _BCD_func__13 _BCD__14_Fl_Callback0;
typedef void (*_BCD_func__17)(Fl_Widget *, void *);
typedef _BCD_func__17 _BCD__18_Fl_Callback;
typedef _BCD__18_Fl_Callback _BCD__16_Fl_Callback_p;
typedef long unsigned int _BCD__58_ulong;
typedef unsigned char _BCD__60_uchar;
}
