/* THIS FILE GENERATED BY bcd.gen */
module bcd.fltk.Fl_Simple_Counter;
public import bcd.bind;
public import bcd.fltk.Fl_Counter;
public import bcd.fltk.Fl_Valuator;
public import bcd.fltk.Fl_Widget;
public import bcd.fltk.Enumerations;
extern (C) void _BCD_delete_17Fl_Simple_Counter(void *);
extern (C) void *_BCD_new__ZN17Fl_Simple_CounterC1EiiiiPKc(int, int, int, int, char *);
extern (C) void _BCD_RI_17Fl_Simple_Counter(void *cd, void *dd);
extern (C) void _BCD_delete_17Fl_Simple_Counter__Fl_Simple_Counter_R(void *This);
extern (C) void *_BCD_new__ZN17Fl_Simple_CounterC1EiiiiPKc_R(int, int, int, int, char *);
alias void function(Fl_Widget *, int) _BCD_func__11;
alias void function(Fl_Widget *) _BCD_func__13;
alias void function(Fl_Widget *, void *) _BCD_func__17;
class Fl_Simple_Counter : Fl_Counter {
this(ifloat ignore) {
super(ignore);
}
this(ifloat ignore, void *x) {
super(ignore);
__C_data = x;
__C_data_owned = false;
}
~this() {
if (__C_data && __C_data_owned) _BCD_delete_17Fl_Simple_Counter(__C_data);
__C_data = null;
}
this(int x, int y, int w, int h, char * l) {
super(cast(ifloat) 0);
__C_data = _BCD_new__ZN17Fl_Simple_CounterC1EiiiiPKc(x, y, w, h, l);
__C_data_owned = true;
}
}
class Fl_Simple_Counter_R : Fl_Simple_Counter {
~this() {
if (__C_data && __C_data_owned) _BCD_delete_17Fl_Simple_Counter__Fl_Simple_Counter_R(__C_data);
__C_data = null;
}
this(int x, int y, int w, int h, char * l) {
super(cast(ifloat) 0);
__C_data = _BCD_new__ZN17Fl_Simple_CounterC1EiiiiPKc_R(x, y, w, h, l);
__C_data_owned = true;
_BCD_RI_17Fl_Simple_Counter(__C_data, cast(void *) this);
}
}
