/* THIS FILE GENERATED BY bcd.gen */
module bcd.fltk.Fl_Tiled_Image;
public import bcd.bind;
public import bcd.fltk.Fl_Image;
public import bcd.fltk.Enumerations;
extern (C) void _BCD_delete_14Fl_Tiled_Image(void *);
extern (C) void *_BCD_new__ZN14Fl_Tiled_ImageC1EP8Fl_Imageii(void *, int, int);
extern (C) Fl_Image * _BCD__ZN14Fl_Tiled_Image4copyEii(void *This, int, int);
extern (C) Fl_Image * _BCD__ZN14Fl_Tiled_Image4copyEv(void *This);
extern (C) void _BCD__ZN14Fl_Tiled_Image13color_averageE8Fl_Colorf(void *This, int, float);
extern (C) void _BCD__ZN14Fl_Tiled_Image10desaturateEv(void *This);
extern (C) void _BCD__ZN14Fl_Tiled_Image4drawEiiiiii(void *This, int, int, int, int, int, int);
extern (C) void _BCD__ZN14Fl_Tiled_Image4drawEii(void *This, int, int);
extern (C) Fl_Image * _BCD__ZN14Fl_Tiled_Image5imageEv(void *This);
extern (C) void _BCD_RI_14Fl_Tiled_Image(void *cd, void *dd);
extern (C) void _BCD_delete_14Fl_Tiled_Image__Fl_Tiled_Image_R(void *This);
extern (C) void *_BCD_new__ZN14Fl_Tiled_ImageC1EP8Fl_Imageii_R(void *, int, int);
extern (C) int _BCD_R__ZN14Fl_Tiled_Image4copyEii__Fl_Tiled_Image_R_CHECK(Fl_Tiled_Image_R x) {
union dp {
Fl_Image * delegate(int, int) d;
struct { void *o; void *f; }
}
dp d; d.d = &x.copy;
return cast(int) (d.f != &Fl_Tiled_Image.copy);
}
extern (C) Fl_Image * _BCD_R__ZN14Fl_Tiled_Image4copyEii__Fl_Tiled_Image_R(Fl_Tiled_Image_R __D_class, int W, int H) {
return __D_class.copy(W, H);
}
extern (C) int _BCD_R__ZN14Fl_Tiled_Image13color_averageE8Fl_Colorf__Fl_Tiled_Image_R_CHECK(Fl_Tiled_Image_R x) {
union dp {
void delegate(int, float) d;
struct { void *o; void *f; }
}
dp d; d.d = &x.color_average;
return cast(int) (d.f != &Fl_Tiled_Image.color_average);
}
extern (C) void _BCD_R__ZN14Fl_Tiled_Image13color_averageE8Fl_Colorf__Fl_Tiled_Image_R(Fl_Tiled_Image_R __D_class, int c, float i) {
__D_class.color_average(c, i);
}
extern (C) int _BCD_R__ZN14Fl_Tiled_Image10desaturateEv__Fl_Tiled_Image_R_CHECK(Fl_Tiled_Image_R x) {
union dp {
void delegate() d;
struct { void *o; void *f; }
}
dp d; d.d = &x.desaturate;
return cast(int) (d.f != &Fl_Tiled_Image.desaturate);
}
extern (C) void _BCD_R__ZN14Fl_Tiled_Image10desaturateEv__Fl_Tiled_Image_R(Fl_Tiled_Image_R __D_class, ) {
__D_class.desaturate();
}
extern (C) int _BCD_R__ZN14Fl_Tiled_Image4drawEiiiiii__Fl_Tiled_Image_R_CHECK(Fl_Tiled_Image_R x) {
union dp {
void delegate(int, int, int, int, int, int) d;
struct { void *o; void *f; }
}
dp d; d.d = &x.draw;
return cast(int) (d.f != &Fl_Tiled_Image.draw);
}
extern (C) void _BCD_R__ZN14Fl_Tiled_Image4drawEiiiiii__Fl_Tiled_Image_R(Fl_Tiled_Image_R __D_class, int X, int Y, int W, int H, int cx, int cy) {
__D_class.draw(X, Y, W, H, cx, cy);
}
class Fl_Tiled_Image : Fl_Image {
this(ifloat ignore) {
super(ignore);
}
this(ifloat ignore, void *x) {
super(ignore);
__C_data = x;
__C_data_owned = false;
}
~this() {
if (__C_data && __C_data_owned) _BCD_delete_14Fl_Tiled_Image(__C_data);
__C_data = null;
}
this(Fl_Image * i, int W, int H) {
super(cast(ifloat) 0);
__C_data = _BCD_new__ZN14Fl_Tiled_ImageC1EP8Fl_Imageii(i.__C_data, W, H);
__C_data_owned = true;
}
Fl_Image * copy(int W, int H) {
return _BCD__ZN14Fl_Tiled_Image4copyEii(__C_data, W, H);
}
Fl_Image * copy() {
return _BCD__ZN14Fl_Tiled_Image4copyEv(__C_data);
}
void color_average(int c, float i) {
_BCD__ZN14Fl_Tiled_Image13color_averageE8Fl_Colorf(__C_data, c, i);
}
void desaturate() {
_BCD__ZN14Fl_Tiled_Image10desaturateEv(__C_data);
}
void draw(int X, int Y, int W, int H, int cx, int cy) {
_BCD__ZN14Fl_Tiled_Image4drawEiiiiii(__C_data, X, Y, W, H, cx, cy);
}
void draw(int X, int Y) {
_BCD__ZN14Fl_Tiled_Image4drawEii(__C_data, X, Y);
}
Fl_Image * image() {
return _BCD__ZN14Fl_Tiled_Image5imageEv(__C_data);
}
}
class Fl_Tiled_Image_R : Fl_Tiled_Image {
~this() {
if (__C_data && __C_data_owned) _BCD_delete_14Fl_Tiled_Image__Fl_Tiled_Image_R(__C_data);
__C_data = null;
}
this(Fl_Image * i, int W, int H) {
super(cast(ifloat) 0);
__C_data = _BCD_new__ZN14Fl_Tiled_ImageC1EP8Fl_Imageii_R(i.__C_data, W, H);
__C_data_owned = true;
_BCD_RI_14Fl_Tiled_Image(__C_data, cast(void *) this);
}
}
