/* THIS FILE GENERATED BY bcd.gen */
module bcd.fltk2.Button;
align(4):
public import bcd.bind;
public import bcd.fltk2.Widget;
public import bcd.fltk2.Style;
public import bcd.fltk2.FL_API;
public import bcd.fltk2.Rectangle;
public import bcd.fltk2.Color;
public import bcd.fltk2.Flags;
extern (C) void _BCD_delete_N4fltk6ButtonE(void *);
extern (C) void _BCD_set__ZN4fltk6Button13default_styleE(void *, NamedStyle *);
extern (C) NamedStyle * _BCD_get__ZN4fltk6Button13default_styleE(void *);
extern (C) bool _BCD__ZNK4fltk6Button5valueEv(void *This);
extern (C) bool _BCD__ZN4fltk6Button5valueEb(void *This, bool);
extern (C) int _BCD__ZN4fltk6Button6handleEi(void *This, int);
extern (C) int _BCD__ZN4fltk6Button6handleEiRKNS_9RectangleE(void *This, int, void *);
extern (C) void *_BCD_new__ZN4fltk6ButtonC1EiiiiPKc(int, int, int, int, char *);
extern (C) void _BCD__ZN4fltk6Button4drawEv(void *This);
extern (C) void _BCD__ZNK4fltk6Button4drawEi(void *This, int);
extern (C) void _BCD_RI_N4fltk6ButtonE(void *cd, void *dd);
extern (C) void _BCD_delete_N4fltk6ButtonE__Button_R(void *This);
extern (C) int _BCD_R__ZN4fltk6Button6handleEi__Button_R_CHECK(Button_R x) {
union dp {
int delegate(int) d;
struct { void *o; void *f; }
}
dp d; d.d = &x.handle;
return cast(int) (d.f != &Button.handle);
}
extern (C) int _BCD_R__ZN4fltk6Button6handleEi__Button_R(Button_R __D_class, int _0) {
return __D_class.handle(_0);
}
extern (C) void *_BCD_new__ZN4fltk6ButtonC1EiiiiPKc_R(int, int, int, int, char *);
extern (C) int _BCD_R__ZN4fltk6Button4drawEv__Button_R_CHECK(Button_R x) {
union dp {
void delegate() d;
struct { void *o; void *f; }
}
dp d; d.d = &x.draw;
return cast(int) (d.f != &Button.draw);
}
extern (C) void _BCD_R__ZN4fltk6Button4drawEv__Button_R(Button_R __D_class, ) {
__D_class.draw();
}
alias void function(Widget *, int) _BCD_func__152;
alias void function(Widget *) _BCD_func__154;
alias void function(Widget *, void *) _BCD_func__158;
alias bool function() _BCD_func__263;
const int HIDDEN = 3;
class Button : Widget {
this(ifloat ignore) {
super(ignore);
}
this(ifloat ignore, void *x) {
super(ignore);
__C_data = x;
__C_data_owned = false;
}
~this() {
if (__C_data && __C_data_owned) _BCD_delete_N4fltk6ButtonE(__C_data);
__C_data = null;
}
void set_default_style(NamedStyle * x) {
_BCD_set__ZN4fltk6Button13default_styleE(__C_data, x);
}
NamedStyle * get_default_style() {
return _BCD_get__ZN4fltk6Button13default_styleE(__C_data);
}
bool value() {
return _BCD__ZNK4fltk6Button5valueEv(__C_data);
}
bool value(bool v) {
return _BCD__ZN4fltk6Button5valueEb(__C_data, v);
}
int handle(int _0) {
return _BCD__ZN4fltk6Button6handleEi(__C_data, _0);
}
int handle(int event, Rectangle _1) {
return _BCD__ZN4fltk6Button6handleEiRKNS_9RectangleE(__C_data, event, _1.__C_data);
}
this(int _0, int _1, int _2, int _3, char * _4 = null) {
super(cast(ifloat) 0);
__C_data = _BCD_new__ZN4fltk6ButtonC1EiiiiPKc(_0, _1, _2, _3, _4);
__C_data_owned = true;
}
void draw() {
_BCD__ZN4fltk6Button4drawEv(__C_data);
}
void draw(int glyph_width) {
_BCD__ZNK4fltk6Button4drawEi(__C_data, glyph_width);
}
}
class Button_R : Button {
~this() {
if (__C_data && __C_data_owned) _BCD_delete_N4fltk6ButtonE__Button_R(__C_data);
__C_data = null;
}
this(int _0, int _1, int _2, int _3, char * _4 = null) {
super(cast(ifloat) 0);
__C_data = _BCD_new__ZN4fltk6ButtonC1EiiiiPKc_R(_0, _1, _2, _3, _4);
__C_data_owned = true;
_BCD_RI_N4fltk6ButtonE(__C_data, cast(void *) this);
}
}
