/* THIS FILE GENERATED BY bcd.gen */
module bcd.fltk2.Clock;
align(4):
public import bcd.bind;
public import bcd.fltk2.Widget;
public import bcd.fltk2.Style;
public import bcd.fltk2.FL_API;
public import bcd.fltk2.Rectangle;
public import bcd.fltk2.Color;
public import bcd.fltk2.Flags;
extern (C) void _BCD_delete_N4fltk5ClockE(void *);
extern (C) void _BCD_set__ZN4fltk5Clock13default_styleE(void *, NamedStyle *);
extern (C) NamedStyle * _BCD_get__ZN4fltk5Clock13default_styleE(void *);
extern (C) int _BCD__ZN4fltk5Clock6handleEi(void *This, int);
extern (C) void _BCD__ZN4fltk5Clock6updateEv(void *This);
extern (C) void *_BCD_new__ZN4fltk5ClockC1EiiiiPKc(int, int, int, int, char *);
extern (C) void _BCD_RI_N4fltk5ClockE(void *cd, void *dd);
extern (C) void _BCD_delete_N4fltk5ClockE__Clock_R(void *This);
extern (C) int _BCD_R__ZN4fltk5Clock6handleEi__Clock_R_CHECK(Clock_R x) {
union dp {
int delegate(int) d;
struct { void *o; void *f; }
}
dp d; d.d = &x.handle;
return cast(int) (d.f != &Clock.handle);
}
extern (C) int _BCD_R__ZN4fltk5Clock6handleEi__Clock_R(Clock_R __D_class, int _0) {
return __D_class.handle(_0);
}
extern (C) void *_BCD_new__ZN4fltk5ClockC1EiiiiPKc_R(int, int, int, int, char *);
extern (C) void _BCD_delete_N4fltk11ClockOutputE(void *);
extern (C) void *_BCD_new__ZN4fltk11ClockOutputC1EiiiiPKc(int, int, int, int, char *);
extern (C) void _BCD__ZN4fltk11ClockOutput5valueEm(void *This, uint);
extern (C) void _BCD__ZN4fltk11ClockOutput5valueEiii(void *This, int, int, int);
extern (C) uint _BCD__ZNK4fltk11ClockOutput5valueEv(void *This);
extern (C) int _BCD__ZNK4fltk11ClockOutput4hourEv(void *This);
extern (C) int _BCD__ZNK4fltk11ClockOutput6minuteEv(void *This);
extern (C) int _BCD__ZNK4fltk11ClockOutput6secondEv(void *This);
extern (C) void _BCD_RI_N4fltk11ClockOutputE(void *cd, void *dd);
extern (C) void _BCD_delete_N4fltk11ClockOutputE__ClockOutput_R(void *This);
extern (C) void *_BCD_new__ZN4fltk11ClockOutputC1EiiiiPKc_R(int, int, int, int, char *);
alias void function(Widget *, int) _BCD_func__154;
alias void function(Widget *) _BCD_func__156;
alias void function(Widget *, void *) _BCD_func__160;
alias bool function() _BCD_func__277;
const int SQUARE = 0;
const int ANALOG = 0;
const int ROUND = 1;
const int DIGITAL = 2;
class Clock : ClockOutput {
this(ifloat ignore) {
super(ignore);
}
this(ifloat ignore, void *x) {
super(ignore);
__C_data = x;
__C_data_owned = false;
}
~this() {
if (__C_data && __C_data_owned) _BCD_delete_N4fltk5ClockE(__C_data);
__C_data = null;
}
void set_default_style(NamedStyle * x) {
_BCD_set__ZN4fltk5Clock13default_styleE(__C_data, x);
}
NamedStyle * get_default_style() {
return _BCD_get__ZN4fltk5Clock13default_styleE(__C_data);
}
int handle(int _0) {
return _BCD__ZN4fltk5Clock6handleEi(__C_data, _0);
}
void update() {
_BCD__ZN4fltk5Clock6updateEv(__C_data);
}
this(int x, int y, int w, int h, char * l = null) {
super(cast(ifloat) 0);
__C_data = _BCD_new__ZN4fltk5ClockC1EiiiiPKc(x, y, w, h, l);
__C_data_owned = true;
}
}
class Clock_R : Clock {
~this() {
if (__C_data && __C_data_owned) _BCD_delete_N4fltk5ClockE__Clock_R(__C_data);
__C_data = null;
}
this(int x, int y, int w, int h, char * l = null) {
super(cast(ifloat) 0);
__C_data = _BCD_new__ZN4fltk5ClockC1EiiiiPKc_R(x, y, w, h, l);
__C_data_owned = true;
_BCD_RI_N4fltk5ClockE(__C_data, cast(void *) this);
}
}
class ClockOutput : Widget {
this(ifloat ignore) {
super(ignore);
}
this(ifloat ignore, void *x) {
super(ignore);
__C_data = x;
__C_data_owned = false;
}
~this() {
if (__C_data && __C_data_owned) _BCD_delete_N4fltk11ClockOutputE(__C_data);
__C_data = null;
}
this(int x, int y, int w, int h, char * l = null) {
super(cast(ifloat) 0);
__C_data = _BCD_new__ZN4fltk11ClockOutputC1EiiiiPKc(x, y, w, h, l);
__C_data_owned = true;
}
void value(uint v) {
_BCD__ZN4fltk11ClockOutput5valueEm(__C_data, v);
}
void value(int _0, int _1, int _2) {
_BCD__ZN4fltk11ClockOutput5valueEiii(__C_data, _0, _1, _2);
}
uint value() {
return _BCD__ZNK4fltk11ClockOutput5valueEv(__C_data);
}
int hour() {
return _BCD__ZNK4fltk11ClockOutput4hourEv(__C_data);
}
int minute() {
return _BCD__ZNK4fltk11ClockOutput6minuteEv(__C_data);
}
int second() {
return _BCD__ZNK4fltk11ClockOutput6secondEv(__C_data);
}
}
class ClockOutput_R : ClockOutput {
~this() {
if (__C_data && __C_data_owned) _BCD_delete_N4fltk11ClockOutputE__ClockOutput_R(__C_data);
__C_data = null;
}
this(int x, int y, int w, int h, char * l = null) {
super(cast(ifloat) 0);
__C_data = _BCD_new__ZN4fltk11ClockOutputC1EiiiiPKc_R(x, y, w, h, l);
__C_data_owned = true;
_BCD_RI_N4fltk11ClockOutputE(__C_data, cast(void *) this);
}
}
