/* THIS FILE GENERATED BY bcd.gen */
#include <stdlib.h>
#include <string.h>
#include "../bind.h"
#include "fltk/StatusBarGroup.h"
extern "C" {
typedef unsigned char _BCD__9_uchar;
void _BCD_delete_N4fltk14StatusBarGroupE(fltk::StatusBarGroup *This) {
delete This;
}
void _BCD_set__ZN4fltk14StatusBarGroup13default_styleE(fltk::StatusBarGroup *This, fltk::NamedStyle * x) {
This->default_style = x;
}
fltk::NamedStyle * _BCD_get__ZN4fltk14StatusBarGroup13default_styleE(fltk::StatusBarGroup *This) {
return This->default_style;
}
fltk::StatusBarGroup *_BCD_new__ZN4fltk14StatusBarGroupC1EiiiiPKcb(int x, int y, int w, int h, char const * l, bool begin) {
return new fltk::StatusBarGroup(x, y, w, h, l, begin);
}
fltk::StatusBarGroup *_BCD_new__ZN4fltk14StatusBarGroupC1Ei(int H) {
return new fltk::StatusBarGroup(H);
}
void _BCD__ZN4fltk14StatusBarGroup6layoutEv(fltk::StatusBarGroup *This) {
(This->layout());
}
void _BCD__ZN4fltk14StatusBarGroup4showEv(fltk::StatusBarGroup *This) {
(This->show());
}
void _BCD__ZN4fltk14StatusBarGroup4hideEv(fltk::StatusBarGroup *This) {
(This->hide());
}
void _BCD__ZN4fltk14StatusBarGroup3setEPKcNS0_8PositionE(fltk::StatusBarGroup *This, char const * t, enum fltk::StatusBarGroup::Position pos) {
(This->set(t, pos));
}
void _BCD__ZN4fltk14StatusBarGroup3setENS0_8PositionEPKcz(fltk::StatusBarGroup *This, enum fltk::StatusBarGroup::Position pos, char const * format) {
(This->set(pos, format));
}
typedef fltk::Symbol * _BCD__227_Box;
void _BCD__ZN4fltk14StatusBarGroup9child_boxEPNS_6SymbolE(fltk::StatusBarGroup *This, _BCD__227_Box b) {
(This->child_box(b));
}
void _BCD__ZN4fltk14StatusBarGroup9child_boxEPNS_6SymbolENS0_8PositionE(fltk::StatusBarGroup *This, _BCD__227_Box b, enum fltk::StatusBarGroup::Position i) {
(This->child_box(b, i));
}
int _BCD_R__ZN4fltk14StatusBarGroup6layoutEv__StatusBarGroup_R_CHECK(void *);
void _BCD_R__ZN4fltk14StatusBarGroup6layoutEv__StatusBarGroup_R(void *);
}
class StatusBarGroup_R : fltk::StatusBarGroup {
public:
void *__D_data;
StatusBarGroup_R(int x, int y, int w, int h, char const * l, bool begin) : fltk::StatusBarGroup(x, y, w, h, l, begin) {}
StatusBarGroup_R(int H) : fltk::StatusBarGroup(H) {}
void layout() {
if (_BCD_R__ZN4fltk14StatusBarGroup6layoutEv__StatusBarGroup_R_CHECK(__D_data))
_BCD_R__ZN4fltk14StatusBarGroup6layoutEv__StatusBarGroup_R(__D_data);
else
fltk::StatusBarGroup::layout();
}
};
extern "C" {
StatusBarGroup_R *_BCD_new__ZN4fltk14StatusBarGroupC1EiiiiPKcb_R(int x, int y, int w, int h, char const * l, bool begin) {
return new StatusBarGroup_R(x, y, w, h, l, begin);
}
StatusBarGroup_R *_BCD_new__ZN4fltk14StatusBarGroupC1Ei_R(int H) {
return new StatusBarGroup_R(H);
}
void _BCD_delete_N4fltk14StatusBarGroupE__StatusBarGroup_R(StatusBarGroup_R *This) {
delete This;
}
void _BCD_RI_N4fltk14StatusBarGroupE(StatusBarGroup_R *cd, void *dd) {
cd->__D_data = dd;
}
typedef void (*_BCD_func__156)(fltk::Widget *, long int);
typedef _BCD_func__156 _BCD__157_Callback1;
typedef void (*_BCD_func__158)(fltk::Widget *);
typedef _BCD_func__158 _BCD__159_Callback0;
typedef void (*_BCD_func__162)(fltk::Widget *, void *);
typedef _BCD_func__162 _BCD__163_Callback;
typedef _BCD__163_Callback _BCD__161_Callback_p;
typedef bool (*_BCD_func__335)();
typedef _BCD_func__335 _BCD__174_Theme;
typedef unsigned int _BCD__244_Color;
typedef int _BCD__247_Flags;
typedef _BCD__247_Flags _BCD__246_Align;
}
