/* THIS FILE GENERATED BY bcd.gen */
module bcd.fltk2.StyleSet;
align(4):
public import bcd.bind;
public import bcd.fltk2.Style;
public import bcd.fltk2.FL_API;
public import bcd.fltk2.Color;
public import bcd.fltk2.Flags;
extern (C) void _BCD_delete_N4fltk8StyleSetE(void *);
extern (C) void *_BCD_new__ZN4fltk8StyleSetC1Ev();
extern (C) void _BCD__ZN4fltk8StyleSet12make_currentEv(void *This);
extern (C) void _BCD_RI_N4fltk8StyleSetE(void *cd, void *dd);
extern (C) void _BCD_delete_N4fltk8StyleSetE__StyleSet_R(void *This);
extern (C) void *_BCD_new__ZN4fltk8StyleSetC1Ev_R();
alias bool function() _BCD_func__237;
class StyleSet : bcd.bind.BoundClass {
this(ifloat ignore) {
super(ignore);
}
this(ifloat ignore, void *x) {
super(ignore);
__C_data = x;
__C_data_owned = false;
}
~this() {
if (__C_data && __C_data_owned) _BCD_delete_N4fltk8StyleSetE(__C_data);
__C_data = null;
}
this() {
super(cast(ifloat) 0);
__C_data = _BCD_new__ZN4fltk8StyleSetC1Ev();
__C_data_owned = true;
}
void make_current() {
_BCD__ZN4fltk8StyleSet12make_currentEv(__C_data);
}
}
class StyleSet_R : StyleSet {
~this() {
if (__C_data && __C_data_owned) _BCD_delete_N4fltk8StyleSetE__StyleSet_R(__C_data);
__C_data = null;
}
this() {
super(cast(ifloat) 0);
__C_data = _BCD_new__ZN4fltk8StyleSetC1Ev_R();
__C_data_owned = true;
_BCD_RI_N4fltk8StyleSetE(__C_data, cast(void *) this);
}
}
