/* THIS FILE GENERATED BY bcd.gen */
#include <stdlib.h>
#include <string.h>
#include "../bind.h"
#include "fltk/Browser.h"
extern "C" {
typedef unsigned char _BCD__13_uchar;
void _BCD_delete_N4fltk7Browser4MarkE(fltk::Browser::Mark *This) {
delete This;
}
fltk::Browser::Mark *_BCD_new__ZN4fltk7Browser4MarkC1Ev() {
return new fltk::Browser::Mark();
}
fltk::Browser::Mark *_BCD_new__ZN4fltk7Browser4MarkC1ERKS1_(fltk::Browser::Mark   const & _0) {
return new fltk::Browser::Mark(_0);
}
int _BCD__ZNK4fltk7Browser4Mark7compareERKS1_(fltk::Browser::Mark *This, fltk::Browser::Mark   const & mark2) {
return (This->compare(mark2));
}
void _BCD__ZN4fltk7Browser4Mark5unsetEv(fltk::Browser::Mark *This) {
(This->unset());
}
bool _BCD__ZNK4fltk7Browser4Mark6is_setEv(fltk::Browser::Mark *This) {
return (This->is_set());
}
}
class Mark_R : fltk::Browser::Mark {
public:
void *__D_data;
Mark_R() : fltk::Browser::Mark() {}
Mark_R(fltk::Browser::Mark   const & _0) : fltk::Browser::Mark(_0) {}
};
extern "C" {
Mark_R *_BCD_new__ZN4fltk7Browser4MarkC1Ev_R() {
return new Mark_R();
}
Mark_R *_BCD_new__ZN4fltk7Browser4MarkC1ERKS1__R(fltk::Browser::Mark   const & _0) {
return new Mark_R(_0);
}
void _BCD_delete_N4fltk7Browser4MarkE__Mark_R(Mark_R *This) {
delete This;
}
void _BCD_RI_N4fltk7Browser4MarkE(Mark_R *cd, void *dd) {
cd->__D_data = dd;
}
void _BCD_delete_N4fltk7BrowserE(fltk::Browser *This) {
delete This;
}
void _BCD_set__ZN4fltk7Browser13default_styleE(fltk::Browser *This, fltk::NamedStyle * x) {
This->default_style = x;
}
fltk::NamedStyle * _BCD_get__ZN4fltk7Browser13default_styleE(fltk::Browser *This) {
return This->default_style;
}
void _BCD_set__ZN4fltk7Browser9scrollbarE(fltk::Browser *This, fltk::Scrollbar * x) {
memcpy(&This->scrollbar, x, sizeof(fltk::Scrollbar));
}
fltk::Scrollbar * _BCD_get__ZN4fltk7Browser9scrollbarE(fltk::Browser *This) {
return &This->scrollbar;
}
void _BCD_set__ZN4fltk7Browser10hscrollbarE(fltk::Browser *This, fltk::Scrollbar * x) {
memcpy(&This->hscrollbar, x, sizeof(fltk::Scrollbar));
}
fltk::Scrollbar * _BCD_get__ZN4fltk7Browser10hscrollbarE(fltk::Browser *This) {
return &This->hscrollbar;
}
int _BCD__ZN4fltk7Browser6handleEi(fltk::Browser *This, int _0) {
return (This->handle(_0));
}
void _BCD__ZN4fltk7Browser6layoutEv(fltk::Browser *This) {
(This->layout());
}
void _BCD__ZN4fltk7Browser4drawEv(fltk::Browser *This) {
(This->draw());
}
fltk::Browser *_BCD_new__ZN4fltk7BrowserC1EiiiiPKc(int X, int Y, int W, int H, char const * l) {
return new fltk::Browser(X, Y, W, H, l);
}
int _BCD__ZNK4fltk7Browser5widthEv(fltk::Browser *This) {
return (This->width());
}
int _BCD__ZNK4fltk7Browser6heightEv(fltk::Browser *This) {
return (This->height());
}
int _BCD__ZNK4fltk7Browser9box_widthEv(fltk::Browser *This) {
return (This->box_width());
}
int _BCD__ZNK4fltk7Browser10box_heightEv(fltk::Browser *This) {
return (This->box_height());
}
int _BCD__ZNK4fltk7Browser9xpositionEv(fltk::Browser *This) {
return (This->xposition());
}
void _BCD__ZN4fltk7Browser9xpositionEi(fltk::Browser *This, int _0) {
(This->xposition(_0));
}
int _BCD__ZNK4fltk7Browser9ypositionEv(fltk::Browser *This) {
return (This->yposition());
}
void _BCD__ZN4fltk7Browser9ypositionEi(fltk::Browser *This, int _0) {
(This->yposition(_0));
}
bool _BCD__ZNK4fltk7Browser8indentedEv(fltk::Browser *This) {
return (This->indented());
}
void _BCD__ZN4fltk7Browser8indentedEb(fltk::Browser *This, bool v) {
(This->indented(v));
}
fltk::Widget * _BCD__ZN4fltk7Browser8goto_topEv(fltk::Browser *This) {
return (This->goto_top());
}
fltk::Widget * _BCD__ZN4fltk7Browser10goto_focusEv(fltk::Browser *This) {
return (This->goto_focus());
}
fltk::Widget * _BCD__ZN4fltk7Browser13goto_positionEi(fltk::Browser *This, int y) {
return (This->goto_position(y));
}
fltk::Widget * _BCD__ZN4fltk7Browser10goto_indexEPKij(fltk::Browser *This, int const * indexes, unsigned int level) {
return (This->goto_index(indexes, level));
}
fltk::Widget * _BCD__ZN4fltk7Browser10goto_indexEi(fltk::Browser *This, int _0) {
return (This->goto_index(_0));
}
fltk::Widget * _BCD__ZN4fltk7Browser10goto_indexEiiiii(fltk::Browser *This, int _0, int _1, int _2, int _3, int _4) {
return (This->goto_index(_0, _1, _2, _3, _4));
}
fltk::Widget * _BCD__ZN4fltk7Browser9goto_markERKNS0_4MarkE(fltk::Browser *This, fltk::Browser::Mark   const & _0) {
return (This->goto_mark(_0));
}
fltk::Widget * _BCD__ZN4fltk7Browser4nextEv(fltk::Browser *This) {
return (This->next());
}
fltk::Widget * _BCD__ZN4fltk7Browser12next_visibleEv(fltk::Browser *This) {
return (This->next_visible());
}
fltk::Widget * _BCD__ZN4fltk7Browser16previous_visibleEv(fltk::Browser *This) {
return (This->previous_visible());
}
bool _BCD__ZNK4fltk7Browser7at_markERKNS0_4MarkE(fltk::Browser *This, fltk::Browser::Mark   const & mark) {
return (This->at_mark(mark));
}
int _BCD__ZNK4fltk7Browser15compare_to_markERKNS0_4MarkE(fltk::Browser *This, fltk::Browser::Mark   const & mark) {
return (This->compare_to_mark(mark));
}
bool _BCD__ZNK4fltk7Browser15item_is_visibleEv(fltk::Browser *This) {
return (This->item_is_visible());
}
bool _BCD__ZNK4fltk7Browser14item_is_parentEv(fltk::Browser *This) {
return (This->item_is_parent());
}
bool _BCD__ZNK4fltk7Browser12item_is_openEv(fltk::Browser *This) {
return (This->item_is_open());
}
int _BCD__ZNK4fltk7Browser6item_hEv(fltk::Browser *This) {
return (This->item_h());
}
bool _BCD__ZN4fltk7Browser9set_focusEv(fltk::Browser *This) {
return (This->set_focus());
}
void _BCD__ZNK4fltk7Browser8set_markERNS0_4MarkE(fltk::Browser *This, fltk::Browser::Mark   & dest) {
(This->set_mark(dest));
}
void _BCD__ZNK4fltk7Browser17set_mark_to_focusERNS0_4MarkE(fltk::Browser *This, fltk::Browser::Mark   & dest) {
(This->set_mark_to_focus(dest));
}
bool _BCD__ZN4fltk7Browser17set_item_selectedEbi(fltk::Browser *This, bool value, int do_callback) {
return (This->set_item_selected(value, do_callback));
}
bool _BCD__ZN4fltk7Browser16select_only_thisEi(fltk::Browser *This, int do_callback) {
return (This->select_only_this(do_callback));
}
bool _BCD__ZN4fltk7Browser8deselectEi(fltk::Browser *This, int do_callback) {
return (This->deselect(do_callback));
}
bool _BCD__ZN4fltk7Browser17make_item_visibleENS0_7lineposE(fltk::Browser *This, enum fltk::Browser::linepos _0) {
return (This->make_item_visible(_0));
}
void _BCD__ZN4fltk7Browser11damage_itemEv(fltk::Browser *This) {
(This->damage_item());
}
void _BCD__ZN4fltk7Browser11damage_itemERKNS0_4MarkE(fltk::Browser *This, fltk::Browser::Mark   const & _0) {
(This->damage_item(_0));
}
bool _BCD__ZN4fltk7Browser15set_item_openedEb(fltk::Browser *This, bool _0) {
return (This->set_item_opened(_0));
}
bool _BCD__ZN4fltk7Browser16set_item_visibleEb(fltk::Browser *This, bool _0) {
return (This->set_item_visible(_0));
}
int _BCD__ZNK4fltk7Browser13current_levelEv(fltk::Browser *This) {
return (This->current_level());
}
int const * _BCD__ZNK4fltk7Browser13current_indexEv(fltk::Browser *This) {
return (This->current_index());
}
int _BCD__ZNK4fltk7Browser16current_positionEv(fltk::Browser *This) {
return (This->current_position());
}
int _BCD__ZNK4fltk7Browser11focus_levelEv(fltk::Browser *This) {
return (This->focus_level());
}
int _BCD__ZNK4fltk7Browser14focus_positionEv(fltk::Browser *This) {
return (This->focus_position());
}
int const * _BCD__ZNK4fltk7Browser13column_widthsEv(fltk::Browser *This) {
return (This->column_widths());
}
void _BCD__ZN4fltk7Browser13column_widthsEPKi(fltk::Browser *This, int const * pWidths) {
(This->column_widths(pWidths));
}
char const * * _BCD__ZNK4fltk7Browser13column_labelsEv(fltk::Browser *This) {
return (This->column_labels());
}
void _BCD__ZN4fltk7Browser13column_labelsEPPKc(fltk::Browser *This, char const * * pLabels) {
(This->column_labels(pLabels));
}
int _BCD__ZN4fltk7Browser15selected_columnEv(fltk::Browser *This) {
return (This->selected_column());
}
int _BCD__ZN4fltk7Browser16set_column_startEii(fltk::Browser *This, int column, int x) {
return (This->set_column_start(column, x));
}
fltk::Widget * _BCD__ZN4fltk7Browser6headerEi(fltk::Browser *This, int col) {
return (This->header(col));
}
int _BCD__ZNK4fltk7Browser7nheaderEv(fltk::Browser *This) {
return (This->nheader());
}
bool _BCD__ZN4fltk7Browser6selectEib(fltk::Browser *This, int line, bool value) {
return (This->select(line, value));
}
bool _BCD__ZN4fltk7Browser8selectedEi(fltk::Browser *This, int line) {
return (This->selected(line));
}
int _BCD__ZNK4fltk7Browser7toplineEv(fltk::Browser *This) {
return (This->topline());
}
void _BCD__ZN4fltk7Browser7toplineEi(fltk::Browser *This, int line) {
(This->topline(line));
}
void _BCD__ZN4fltk7Browser10bottomlineEi(fltk::Browser *This, int line) {
(This->bottomline(line));
}
void _BCD__ZN4fltk7Browser10middlelineEi(fltk::Browser *This, int line) {
(This->middleline(line));
}
bool _BCD__ZN4fltk7Browser9displayedEi(fltk::Browser *This, int line) {
return (This->displayed(line));
}
bool _BCD__ZN4fltk7Browser7displayEib(fltk::Browser *This, int line, bool value) {
return (This->display(line, value));
}
bool _BCD__ZNK4fltk7Browser13display_linesEv(fltk::Browser *This) {
return (This->display_lines());
}
void _BCD__ZN4fltk7Browser13display_linesEb(fltk::Browser *This, bool display) {
(This->display_lines(display));
}
int _BCD__ZNK4fltk7Browser5multiEv(fltk::Browser *This) {
return (This->multi());
}
fltk::Symbol const * _BCD__ZNK4fltk7Browser11leaf_symbolEv(fltk::Browser *This) {
return (This->leaf_symbol());
}
void _BCD__ZN4fltk7Browser11leaf_symbolEPKNS_6SymbolE(fltk::Browser *This, fltk::Symbol const * s) {
(This->leaf_symbol(s));
}
fltk::Symbol const * _BCD__ZNK4fltk7Browser12group_symbolEv(fltk::Browser *This) {
return (This->group_symbol());
}
void _BCD__ZN4fltk7Browser12group_symbolEPKNS_6SymbolE(fltk::Browser *This, fltk::Symbol const * s) {
(This->group_symbol(s));
}
int _BCD_R__ZN4fltk7Browser6handleEi__Browser_R_CHECK(void *);
int _BCD_R__ZN4fltk7Browser6handleEi__Browser_R(void *, int _0);
int _BCD_R__ZN4fltk7Browser6layoutEv__Browser_R_CHECK(void *);
void _BCD_R__ZN4fltk7Browser6layoutEv__Browser_R(void *);
int _BCD_R__ZN4fltk7Browser4drawEv__Browser_R_CHECK(void *);
void _BCD_R__ZN4fltk7Browser4drawEv__Browser_R(void *);
}
class Browser_R : fltk::Browser {
public:
void *__D_data;
int handle(int _0) {
if (_BCD_R__ZN4fltk7Browser6handleEi__Browser_R_CHECK(__D_data))
return _BCD_R__ZN4fltk7Browser6handleEi__Browser_R(__D_data, _0);
else
return fltk::Browser::handle(_0);
}
void layout() {
if (_BCD_R__ZN4fltk7Browser6layoutEv__Browser_R_CHECK(__D_data))
_BCD_R__ZN4fltk7Browser6layoutEv__Browser_R(__D_data);
else
fltk::Browser::layout();
}
void draw() {
if (_BCD_R__ZN4fltk7Browser4drawEv__Browser_R_CHECK(__D_data))
_BCD_R__ZN4fltk7Browser4drawEv__Browser_R(__D_data);
else
fltk::Browser::draw();
}
Browser_R(int X, int Y, int W, int H, char const * l) : fltk::Browser(X, Y, W, H, l) {}
};
extern "C" {
Browser_R *_BCD_new__ZN4fltk7BrowserC1EiiiiPKc_R(int X, int Y, int W, int H, char const * l) {
return new Browser_R(X, Y, W, H, l);
}
void _BCD_delete_N4fltk7BrowserE__Browser_R(Browser_R *This) {
delete This;
}
void _BCD_RI_N4fltk7BrowserE(Browser_R *cd, void *dd) {
cd->__D_data = dd;
}
typedef void (*_BCD_func__167)(fltk::Widget *, long int);
typedef _BCD_func__167 _BCD__168_Callback1;
typedef void (*_BCD_func__169)(fltk::Widget *);
typedef _BCD_func__169 _BCD__170_Callback0;
typedef void (*_BCD_func__173)(fltk::Widget *, void *);
typedef _BCD_func__173 _BCD__174_Callback;
typedef _BCD__174_Callback _BCD__172_Callback_p;
typedef bool (*_BCD_func__558)();
typedef _BCD_func__558 _BCD__185_Theme;
typedef fltk::Symbol * _BCD__238_Box;
typedef unsigned int _BCD__255_Color;
typedef int _BCD__258_Flags;
typedef _BCD__258_Flags _BCD__257_Align;
}
