/* THIS FILE GENERATED BY bcd.gen */
#include <stdlib.h>
#include <string.h>
#include "../bind.h"
#include "fltk/Button.h"
extern "C" {
typedef unsigned char _BCD__7_uchar;
void _BCD_delete_N4fltk6ButtonE(fltk::Button *This) {
delete This;
}
void _BCD_set__ZN4fltk6Button13default_styleE(fltk::Button *This, fltk::NamedStyle * x) {
This->default_style = x;
}
fltk::NamedStyle * _BCD_get__ZN4fltk6Button13default_styleE(fltk::Button *This) {
return This->default_style;
}
bool _BCD__ZNK4fltk6Button5valueEv(fltk::Button *This) {
return (This->value());
}
bool _BCD__ZN4fltk6Button5valueEb(fltk::Button *This, bool v) {
return (This->value(v));
}
int _BCD__ZN4fltk6Button6handleEi(fltk::Button *This, int _0) {
return (This->handle(_0));
}
int _BCD__ZN4fltk6Button6handleEiRKNS_9RectangleE(fltk::Button *This, int event, fltk::Rectangle   const & _1) {
return (This->handle(event, _1));
}
fltk::Button *_BCD_new__ZN4fltk6ButtonC1EiiiiPKc(int _0, int _1, int _2, int _3, char const * _4) {
return new fltk::Button(_0, _1, _2, _3, _4);
}
void _BCD__ZN4fltk6Button4drawEv(fltk::Button *This) {
(This->draw());
}
void _BCD__ZNK4fltk6Button4drawEi(fltk::Button *This, int glyph_width) {
(This->draw(glyph_width));
}
int _BCD_R__ZN4fltk6Button6handleEi__Button_R_CHECK(void *);
int _BCD_R__ZN4fltk6Button6handleEi__Button_R(void *, int _0);
int _BCD_R__ZN4fltk6Button4drawEv__Button_R_CHECK(void *);
void _BCD_R__ZN4fltk6Button4drawEv__Button_R(void *);
}
class Button_R : fltk::Button {
public:
void *__D_data;
int handle(int _0) {
if (_BCD_R__ZN4fltk6Button6handleEi__Button_R_CHECK(__D_data))
return _BCD_R__ZN4fltk6Button6handleEi__Button_R(__D_data, _0);
else
return fltk::Button::handle(_0);
}
Button_R(int _0, int _1, int _2, int _3, char const * _4) : fltk::Button(_0, _1, _2, _3, _4) {}
void draw() {
if (_BCD_R__ZN4fltk6Button4drawEv__Button_R_CHECK(__D_data))
_BCD_R__ZN4fltk6Button4drawEv__Button_R(__D_data);
else
fltk::Button::draw();
}
};
extern "C" {
Button_R *_BCD_new__ZN4fltk6ButtonC1EiiiiPKc_R(int _0, int _1, int _2, int _3, char const * _4) {
return new Button_R(_0, _1, _2, _3, _4);
}
void _BCD_delete_N4fltk6ButtonE__Button_R(Button_R *This) {
delete This;
}
void _BCD_RI_N4fltk6ButtonE(Button_R *cd, void *dd) {
cd->__D_data = dd;
}
typedef void (*_BCD_func__152)(fltk::Widget *, long int);
typedef _BCD_func__152 _BCD__153_Callback1;
typedef void (*_BCD_func__154)(fltk::Widget *);
typedef _BCD_func__154 _BCD__155_Callback0;
typedef void (*_BCD_func__158)(fltk::Widget *, void *);
typedef _BCD_func__158 _BCD__159_Callback;
typedef _BCD__159_Callback _BCD__157_Callback_p;
typedef bool (*_BCD_func__263)();
typedef _BCD_func__263 _BCD__170_Theme;
typedef fltk::Symbol * _BCD__223_Box;
typedef unsigned int _BCD__240_Color;
typedef int _BCD__243_Flags;
typedef _BCD__243_Flags _BCD__242_Align;
}
