/* THIS FILE GENERATED BY bcd.gen */
#include <stdlib.h>
#include <string.h>
#include "../bind.h"
#include "fltk/MenuBuild.h"
extern "C" {
typedef unsigned char _BCD__15_uchar;
typedef void (*_BCD_func__259)(fltk::Widget *, long int);
typedef _BCD_func__259 _BCD__260_Callback1;
typedef void (*_BCD_func__261)(fltk::Widget *);
typedef _BCD_func__261 _BCD__262_Callback0;
typedef void (*_BCD_func__265)(fltk::Widget *, void *);
typedef _BCD_func__265 _BCD__266_Callback;
typedef _BCD__266_Callback _BCD__264_Callback_p;
typedef bool (*_BCD_func__535)();
typedef _BCD_func__535 _BCD__277_Theme;
typedef fltk::Symbol * _BCD__330_Box;
typedef unsigned int _BCD__347_Color;
typedef int _BCD__350_Flags;
typedef _BCD__350_Flags _BCD__349_Align;
}
