/* THIS FILE GENERATED BY bcd.gen */
#include <stdlib.h>
#include <string.h>
#include "../bind.h"
#include "fltk/Output.h"
extern "C" {
typedef unsigned char _BCD__8_uchar;
void _BCD_delete_N4fltk6OutputE(fltk::Output *This) {
delete This;
}
void _BCD_set__ZN4fltk6Output13default_styleE(fltk::Output *This, fltk::NamedStyle * x) {
This->default_style = x;
}
fltk::NamedStyle * _BCD_get__ZN4fltk6Output13default_styleE(fltk::Output *This) {
return This->default_style;
}
fltk::Output *_BCD_new__ZN4fltk6OutputC1EiiiiPKc(int x, int y, int w, int h, char const * l) {
return new fltk::Output(x, y, w, h, l);
}
int _BCD__ZN4fltk6Output6handleEi(fltk::Output *This, int _0) {
return (This->handle(_0));
}
int _BCD_R__ZN4fltk6Output6handleEi__Output_R_CHECK(void *);
int _BCD_R__ZN4fltk6Output6handleEi__Output_R(void *, int _0);
}
class Output_R : fltk::Output {
public:
void *__D_data;
Output_R(int x, int y, int w, int h, char const * l) : fltk::Output(x, y, w, h, l) {}
int handle(int _0) {
if (_BCD_R__ZN4fltk6Output6handleEi__Output_R_CHECK(__D_data))
return _BCD_R__ZN4fltk6Output6handleEi__Output_R(__D_data, _0);
else
return fltk::Output::handle(_0);
}
};
extern "C" {
Output_R *_BCD_new__ZN4fltk6OutputC1EiiiiPKc_R(int x, int y, int w, int h, char const * l) {
return new Output_R(x, y, w, h, l);
}
void _BCD_delete_N4fltk6OutputE__Output_R(Output_R *This) {
delete This;
}
void _BCD_RI_N4fltk6OutputE(Output_R *cd, void *dd) {
cd->__D_data = dd;
}
typedef void (*_BCD_func__154)(fltk::Widget *, long int);
typedef _BCD_func__154 _BCD__155_Callback1;
typedef void (*_BCD_func__156)(fltk::Widget *);
typedef _BCD_func__156 _BCD__157_Callback0;
typedef void (*_BCD_func__160)(fltk::Widget *, void *);
typedef _BCD_func__160 _BCD__161_Callback;
typedef _BCD__161_Callback _BCD__159_Callback_p;
typedef bool (*_BCD_func__323)();
typedef _BCD_func__323 _BCD__172_Theme;
typedef fltk::Symbol * _BCD__225_Box;
typedef unsigned int _BCD__242_Color;
typedef int _BCD__245_Flags;
typedef _BCD__245_Flags _BCD__244_Align;
}
