/* THIS FILE GENERATED BY bcd.gen */
module bcd.fltk2.Preferences;
align(4):
public import bcd.bind;
public import bcd.fltk2.FL_API;
extern (C) void _BCD_delete_N4fltk11Preferences4NameE(void *);
extern (C) void *_BCD_new__ZN4fltk11Preferences4NameC1Ei(int);
extern (C) void *_BCD_new__ZN4fltk11Preferences4NameC1EPKcz(char *);
extern (C) void _BCD_RI_N4fltk11Preferences4NameE(void *cd, void *dd);
extern (C) void _BCD_delete_N4fltk11Preferences4NameE__Name_R(void *This);
extern (C) void *_BCD_new__ZN4fltk11Preferences4NameC1Ei_R(int);
extern (C) void *_BCD_new__ZN4fltk11Preferences4NameC1EPKcz_R(char *);
extern (C) void _BCD_delete_N4fltk11PreferencesE(void *);
enum Root {
SYSTEM=0,
USER=1,
}
alias Root.SYSTEM SYSTEM;
alias Root.USER USER;
extern (C) void *_BCD_new__ZN4fltk11PreferencesC1ENS0_4RootEPKcS3_(int, char *, char *);
extern (C) void *_BCD_new__ZN4fltk11PreferencesC1EPKcS2_S2_(char *, char *, char *);
extern (C) void *_BCD_new__ZN4fltk11PreferencesC1ERS0_PKc(void *, char *);
extern (C) int _BCD__ZN4fltk11Preferences6groupsEv(void *This);
extern (C) char * _BCD__ZN4fltk11Preferences5groupEi(void *This, int);
extern (C) bool _BCD__ZN4fltk11Preferences11groupExistsEPKc(void *This, char *);
extern (C) bool _BCD__ZN4fltk11Preferences11deleteGroupEPKc(void *This, char *);
extern (C) int _BCD__ZN4fltk11Preferences7entriesEv(void *This);
extern (C) char * _BCD__ZN4fltk11Preferences5entryEi(void *This, int);
extern (C) bool _BCD__ZN4fltk11Preferences11entryExistsEPKc(void *This, char *);
extern (C) bool _BCD__ZN4fltk11Preferences11deleteEntryEPKc(void *This, char *);
extern (C) bool _BCD__ZN4fltk11Preferences3setEPKci(void *This, char *, int);
extern (C) bool _BCD__ZN4fltk11Preferences3setEPKcf(void *This, char *, float);
extern (C) bool _BCD__ZN4fltk11Preferences3setEPKcd(void *This, char *, double);
extern (C) bool _BCD__ZN4fltk11Preferences3setEPKcS2_(void *This, char *, char *);
extern (C) bool _BCD__ZN4fltk11Preferences3setEPKcPKvi(void *This, char *, void *, int);
extern (C) bool _BCD__ZN4fltk11Preferences3getEPKcRii(void *This, char *, int *, int);
extern (C) bool _BCD__ZN4fltk11Preferences3getEPKcRff(void *This, char *, float *, float);
extern (C) bool _BCD__ZN4fltk11Preferences3getEPKcRdd(void *This, char *, double *, double);
extern (C) bool _BCD__ZN4fltk11Preferences3getEPKcRPcS2_(void *This, char *, char * *, char *);
extern (C) bool _BCD__ZN4fltk11Preferences3getEPKcPcS2_i(void *This, char *, char *, char *, int);
extern (C) bool _BCD__ZN4fltk11Preferences3getEPKcRPvPKvi(void *This, char *, void * *, void *, int);
extern (C) bool _BCD__ZN4fltk11Preferences3getEPKcPvPKvii(void *This, char *, void *, void *, int, int);
extern (C) int _BCD__ZN4fltk11Preferences4sizeEPKc(void *This, char *);
extern (C) bool _BCD__ZN4fltk11Preferences15getUserdataPathEPci(void *This, char *, int);
extern (C) void _BCD__ZN4fltk11Preferences5flushEv(void *This);
extern (C) void _BCD_RI_N4fltk11PreferencesE(void *cd, void *dd);
extern (C) void _BCD_delete_N4fltk11PreferencesE__Preferences_R(void *This);
extern (C) void *_BCD_new__ZN4fltk11PreferencesC1ENS0_4RootEPKcS3__R(int, char *, char *);
extern (C) void *_BCD_new__ZN4fltk11PreferencesC1EPKcS2_S2__R(char *, char *, char *);
extern (C) void *_BCD_new__ZN4fltk11PreferencesC1ERS0_PKc_R(void *, char *);
class Name : bcd.bind.BoundClass {
this(ifloat ignore) {
super(ignore);
}
this(ifloat ignore, void *x) {
super(ignore);
__C_data = x;
__C_data_owned = false;
}
~this() {
if (__C_data && __C_data_owned) _BCD_delete_N4fltk11Preferences4NameE(__C_data);
__C_data = null;
}
this(int n) {
super(cast(ifloat) 0);
__C_data = _BCD_new__ZN4fltk11Preferences4NameC1Ei(n);
__C_data_owned = true;
}
this(char * format) {
super(cast(ifloat) 0);
__C_data = _BCD_new__ZN4fltk11Preferences4NameC1EPKcz(format);
__C_data_owned = true;
}
}
class Name_R : Name {
~this() {
if (__C_data && __C_data_owned) _BCD_delete_N4fltk11Preferences4NameE__Name_R(__C_data);
__C_data = null;
}
this(int n) {
super(cast(ifloat) 0);
__C_data = _BCD_new__ZN4fltk11Preferences4NameC1Ei_R(n);
__C_data_owned = true;
_BCD_RI_N4fltk11Preferences4NameE(__C_data, cast(void *) this);
}
this(char * format) {
super(cast(ifloat) 0);
__C_data = _BCD_new__ZN4fltk11Preferences4NameC1EPKcz_R(format);
__C_data_owned = true;
_BCD_RI_N4fltk11Preferences4NameE(__C_data, cast(void *) this);
}
}
class Preferences : bcd.bind.BoundClass {
this(ifloat ignore) {
super(ignore);
}
this(ifloat ignore, void *x) {
super(ignore);
__C_data = x;
__C_data_owned = false;
}
~this() {
if (__C_data && __C_data_owned) _BCD_delete_N4fltk11PreferencesE(__C_data);
__C_data = null;
}
this(int root, char * vendor, char * application) {
super(cast(ifloat) 0);
__C_data = _BCD_new__ZN4fltk11PreferencesC1ENS0_4RootEPKcS3_(root, vendor, application);
__C_data_owned = true;
}
this(char * path, char * vendor, char * application) {
super(cast(ifloat) 0);
__C_data = _BCD_new__ZN4fltk11PreferencesC1EPKcS2_S2_(path, vendor, application);
__C_data_owned = true;
}
this(Preferences _0, char * group) {
super(cast(ifloat) 0);
__C_data = _BCD_new__ZN4fltk11PreferencesC1ERS0_PKc(_0.__C_data, group);
__C_data_owned = true;
}
int groups() {
return _BCD__ZN4fltk11Preferences6groupsEv(__C_data);
}
char * group(int _0) {
return _BCD__ZN4fltk11Preferences5groupEi(__C_data, _0);
}
bool groupExists(char * group) {
return _BCD__ZN4fltk11Preferences11groupExistsEPKc(__C_data, group);
}
bool deleteGroup(char * group) {
return _BCD__ZN4fltk11Preferences11deleteGroupEPKc(__C_data, group);
}
int entries() {
return _BCD__ZN4fltk11Preferences7entriesEv(__C_data);
}
char * entry(int _0) {
return _BCD__ZN4fltk11Preferences5entryEi(__C_data, _0);
}
bool entryExists(char * entry) {
return _BCD__ZN4fltk11Preferences11entryExistsEPKc(__C_data, entry);
}
bool deleteEntry(char * entry) {
return _BCD__ZN4fltk11Preferences11deleteEntryEPKc(__C_data, entry);
}
bool set(char * entry, int value) {
return _BCD__ZN4fltk11Preferences3setEPKci(__C_data, entry, value);
}
bool set(char * entry, float value) {
return _BCD__ZN4fltk11Preferences3setEPKcf(__C_data, entry, value);
}
bool set(char * entry, double value) {
return _BCD__ZN4fltk11Preferences3setEPKcd(__C_data, entry, value);
}
bool set(char * entry, char * value) {
return _BCD__ZN4fltk11Preferences3setEPKcS2_(__C_data, entry, value);
}
bool set(char * entry, void * value, int size) {
return _BCD__ZN4fltk11Preferences3setEPKcPKvi(__C_data, entry, value, size);
}
bool get(char * entry, int * value, int defaultValue) {
return _BCD__ZN4fltk11Preferences3getEPKcRii(__C_data, entry, value, defaultValue);
}
bool get(char * entry, float * value, float defaultValue) {
return _BCD__ZN4fltk11Preferences3getEPKcRff(__C_data, entry, value, defaultValue);
}
bool get(char * entry, double * value, double defaultValue) {
return _BCD__ZN4fltk11Preferences3getEPKcRdd(__C_data, entry, value, defaultValue);
}
bool get(char * entry, char * * value, char * defaultValue) {
return _BCD__ZN4fltk11Preferences3getEPKcRPcS2_(__C_data, entry, value, defaultValue);
}
bool get(char * entry, char * value, char * defaultValue, int maxSize) {
return _BCD__ZN4fltk11Preferences3getEPKcPcS2_i(__C_data, entry, value, defaultValue, maxSize);
}
bool get(char * entry, void * * value, void * defaultValue, int defaultSize) {
return _BCD__ZN4fltk11Preferences3getEPKcRPvPKvi(__C_data, entry, value, defaultValue, defaultSize);
}
bool get(char * entry, void * value, void * defaultValue, int defaultSize, int maxSize) {
return _BCD__ZN4fltk11Preferences3getEPKcPvPKvii(__C_data, entry, value, defaultValue, defaultSize, maxSize);
}
int size(char * entry) {
return _BCD__ZN4fltk11Preferences4sizeEPKc(__C_data, entry);
}
bool getUserdataPath(char * path, int pathlen) {
return _BCD__ZN4fltk11Preferences15getUserdataPathEPci(__C_data, path, pathlen);
}
void flush() {
_BCD__ZN4fltk11Preferences5flushEv(__C_data);
}
}
class Preferences_R : Preferences {
~this() {
if (__C_data && __C_data_owned) _BCD_delete_N4fltk11PreferencesE__Preferences_R(__C_data);
__C_data = null;
}
this(int root, char * vendor, char * application) {
super(cast(ifloat) 0);
__C_data = _BCD_new__ZN4fltk11PreferencesC1ENS0_4RootEPKcS3__R(root, vendor, application);
__C_data_owned = true;
_BCD_RI_N4fltk11PreferencesE(__C_data, cast(void *) this);
}
this(char * path, char * vendor, char * application) {
super(cast(ifloat) 0);
__C_data = _BCD_new__ZN4fltk11PreferencesC1EPKcS2_S2__R(path, vendor, application);
__C_data_owned = true;
_BCD_RI_N4fltk11PreferencesE(__C_data, cast(void *) this);
}
this(Preferences _0, char * group) {
super(cast(ifloat) 0);
__C_data = _BCD_new__ZN4fltk11PreferencesC1ERS0_PKc_R(_0.__C_data, group);
__C_data_owned = true;
_BCD_RI_N4fltk11PreferencesE(__C_data, cast(void *) this);
}
}
