/* THIS FILE GENERATED BY bcd.gen */
module bcd.fltk2.ProgressBar;
align(4):
public import bcd.bind;
public import bcd.fltk2.Widget;
public import bcd.fltk2.Style;
public import bcd.fltk2.FL_API;
public import bcd.fltk2.Rectangle;
public import bcd.fltk2.Color;
public import bcd.fltk2.Flags;
extern (C) void _BCD_delete_N4fltk11ProgressBarE(void *);
extern (C) void *_BCD_new__ZN4fltk11ProgressBarC1EiiiiPKc(int, int, int, int, char *);
extern (C) void _BCD__ZN4fltk11ProgressBar5rangeEddd(void *This, double, double, double);
extern (C) void _BCD__ZN4fltk11ProgressBar4stepEd(void *This, double);
extern (C) double _BCD__ZN4fltk11ProgressBar7minimumEv(void *This);
extern (C) double _BCD__ZN4fltk11ProgressBar7maximumEv(void *This);
extern (C) void _BCD__ZN4fltk11ProgressBar7minimumEd(void *This, double);
extern (C) void _BCD__ZN4fltk11ProgressBar7maximumEd(void *This, double);
extern (C) double _BCD__ZN4fltk11ProgressBar8positionEv(void *This);
extern (C) double _BCD__ZN4fltk11ProgressBar4stepEv(void *This);
extern (C) void _BCD__ZN4fltk11ProgressBar8positionEd(void *This, double);
extern (C) void _BCD__ZN4fltk11ProgressBar8showtextEb(void *This, bool);
extern (C) bool _BCD__ZN4fltk11ProgressBar8showtextEv(void *This);
extern (C) void _BCD__ZN4fltk11ProgressBar10text_colorEj(void *This, uint);
extern (C) uint _BCD__ZN4fltk11ProgressBar10text_colorEv(void *This);
extern (C) void _BCD_RI_N4fltk11ProgressBarE(void *cd, void *dd);
extern (C) void _BCD_delete_N4fltk11ProgressBarE__ProgressBar_R(void *This);
extern (C) void *_BCD_new__ZN4fltk11ProgressBarC1EiiiiPKc_R(int, int, int, int, char *);
alias void function(Widget *, int) _BCD_func__152;
alias void function(Widget *) _BCD_func__154;
alias void function(Widget *, void *) _BCD_func__158;
alias bool function() _BCD_func__275;
class ProgressBar : Widget {
this(ifloat ignore) {
super(ignore);
}
this(ifloat ignore, void *x) {
super(ignore);
__C_data = x;
__C_data_owned = false;
}
~this() {
if (__C_data && __C_data_owned) _BCD_delete_N4fltk11ProgressBarE(__C_data);
__C_data = null;
}
this(int x, int y, int w, int h, char * lbl = null) {
super(cast(ifloat) 0);
__C_data = _BCD_new__ZN4fltk11ProgressBarC1EiiiiPKc(x, y, w, h, lbl);
__C_data_owned = true;
}
void range(double min, double max, double step = 1) {
_BCD__ZN4fltk11ProgressBar5rangeEddd(__C_data, min, max, step);
}
void step(double step) {
_BCD__ZN4fltk11ProgressBar4stepEd(__C_data, step);
}
double minimum() {
return _BCD__ZN4fltk11ProgressBar7minimumEv(__C_data);
}
double maximum() {
return _BCD__ZN4fltk11ProgressBar7maximumEv(__C_data);
}
void minimum(double nm) {
_BCD__ZN4fltk11ProgressBar7minimumEd(__C_data, nm);
}
void maximum(double nm) {
_BCD__ZN4fltk11ProgressBar7maximumEd(__C_data, nm);
}
double position() {
return _BCD__ZN4fltk11ProgressBar8positionEv(__C_data);
}
double step() {
return _BCD__ZN4fltk11ProgressBar4stepEv(__C_data);
}
void position(double pos) {
_BCD__ZN4fltk11ProgressBar8positionEd(__C_data, pos);
}
void showtext(bool st) {
_BCD__ZN4fltk11ProgressBar8showtextEb(__C_data, st);
}
bool showtext() {
return _BCD__ZN4fltk11ProgressBar8showtextEv(__C_data);
}
void text_color(uint col) {
_BCD__ZN4fltk11ProgressBar10text_colorEj(__C_data, col);
}
uint text_color() {
return _BCD__ZN4fltk11ProgressBar10text_colorEv(__C_data);
}
}
class ProgressBar_R : ProgressBar {
~this() {
if (__C_data && __C_data_owned) _BCD_delete_N4fltk11ProgressBarE__ProgressBar_R(__C_data);
__C_data = null;
}
this(int x, int y, int w, int h, char * lbl = null) {
super(cast(ifloat) 0);
__C_data = _BCD_new__ZN4fltk11ProgressBarC1EiiiiPKc_R(x, y, w, h, lbl);
__C_data_owned = true;
_BCD_RI_N4fltk11ProgressBarE(__C_data, cast(void *) this);
}
}
