/* THIS FILE GENERATED BY bcd.gen */
#include <stdlib.h>
#include <string.h>
#include "../bind.h"
#include "fltk/Symbol.h"
extern "C" {
typedef unsigned char _BCD__5_uchar;
void _BCD_delete_N4fltk6SymbolE(fltk::Symbol *This) {
delete This;
}
char const * _BCD__ZNK4fltk6Symbol4nameEv(fltk::Symbol *This) {
return (This->name());
}
void _BCD__ZN4fltk6Symbol4nameEPKc(fltk::Symbol *This, char const * _0) {
(This->name(_0));
}
void _BCD__ZNK4fltk6Symbol8_measureERiS1_(fltk::Symbol *This, int & w, int & h) {
(This->_measure(w, h));
}
void _BCD__ZNK4fltk6Symbol7measureERiS1_(fltk::Symbol *This, int & w, int & h) {
(This->measure(w, h));
}
void _BCD__ZNK4fltk6Symbol5_drawERKNS_9RectangleE(fltk::Symbol *This, fltk::Rectangle   const & _0) {
(This->_draw(_0));
}
void _BCD__ZNK4fltk6Symbol4drawERKNS_9RectangleE(fltk::Symbol *This, fltk::Rectangle   const & r) {
(This->draw(r));
}
void _BCD__ZNK4fltk6Symbol19draw_symbol_overlayERKNS_9RectangleE(fltk::Symbol *This, fltk::Rectangle   const & _0) {
(This->draw_symbol_overlay(_0));
}
void _BCD__ZN4fltk6Symbol9set_insetEiiii(fltk::Symbol *This, int x, int y, int w, int h) {
(This->set_inset(x, y, w, h));
}
void _BCD__ZN4fltk6Symbol9set_insetEii(fltk::Symbol *This, int x, int y) {
(This->set_inset(x, y));
}
void _BCD__ZN4fltk6Symbol9set_insetEi(fltk::Symbol *This, int x) {
(This->set_inset(x));
}
void _BCD__ZN4fltk6Symbol9set_insetERKNS_9RectangleE(fltk::Symbol *This, fltk::Rectangle   const & r) {
(This->set_inset(r));
}
fltk::Rectangle   const & _BCD__ZNK4fltk6Symbol9get_insetEv(fltk::Symbol *This) {
return (This->get_inset());
}
int _BCD__ZNK4fltk6Symbol2dxEv(fltk::Symbol *This) {
return (This->dx());
}
int _BCD__ZNK4fltk6Symbol2dyEv(fltk::Symbol *This) {
return (This->dy());
}
int _BCD__ZNK4fltk6Symbol2dwEv(fltk::Symbol *This) {
return (This->dw());
}
int _BCD__ZNK4fltk6Symbol2dhEv(fltk::Symbol *This) {
return (This->dh());
}
void _BCD__ZNK4fltk6Symbol5insetERNS_9RectangleE(fltk::Symbol *This, fltk::Rectangle   & r) {
(This->inset(r));
}
bool _BCD__ZNK4fltk6Symbol15fills_rectangleEv(fltk::Symbol *This) {
return (This->fills_rectangle());
}
bool _BCD__ZNK4fltk6Symbol8is_frameEv(fltk::Symbol *This) {
return (This->is_frame());
}
fltk::Symbol const * _BCD__ZN4fltk6Symbol4findEPKc(char const * name) {
return (fltk::Symbol::find(name));
}
fltk::Symbol const * _BCD__ZN4fltk6Symbol4findEPKcS2_(char const * start, char const * end) {
return (fltk::Symbol::find(start, end));
}
fltk::Symbol const * _BCD__ZN4fltk6Symbol7iterateERi(int & index) {
return (fltk::Symbol::iterate(index));
}
void _BCD__ZN4fltk6Symbol4textEPKcj(char const * s, unsigned int n) {
(fltk::Symbol::text(s, n));
}
char const * _BCD__ZN4fltk6Symbol4textEv() {
return (fltk::Symbol::text());
}
unsigned int _BCD__ZN4fltk6Symbol11text_lengthEv() {
return (fltk::Symbol::text_length());
}
typedef void (*_BCD_func__246)(unsigned int);
void _BCD__ZN4fltk10add_symbolEPKcPFvjEi(char const * name, _BCD_func__246 drawit, int scalable) {
(fltk::add_symbol(name, drawit, scalable));
}
typedef unsigned int _BCD__165_Color;
typedef int _BCD__168_Flags;
typedef _BCD__168_Flags _BCD__167_Align;
}
