/* THIS FILE GENERATED BY bcd.gen */
module bcd.fltk2.Widget;
align(4):
public import bcd.bind;
public import bcd.fltk2.Style;
public import bcd.fltk2.FL_API;
public import bcd.fltk2.Rectangle;
public import bcd.fltk2.Color;
public import bcd.fltk2.Flags;
extern (C) void _BCD_delete_N4fltk6WidgetE(void *);
extern (C) void _BCD_set__ZN4fltk6Widget13default_styleE(void *, NamedStyle *);
extern (C) NamedStyle * _BCD_get__ZN4fltk6Widget13default_styleE(void *);
extern (C) void _BCD_set__ZN4fltk6Widget13default_glyphE(void *, bcd.bind.BoundClass *);
extern (C) bcd.bind.BoundClass * _BCD_get__ZN4fltk6Widget13default_glyphE(void *);
extern (C) void *_BCD_new__ZN4fltk6WidgetC1EiiiiPKc(int, int, int, int, char *);
extern (C) void _BCD__ZN4fltk6Widget4drawEv(void *This);
extern (C) int _BCD__ZN4fltk6Widget6handleEi(void *This, int);
extern (C) int _BCD__ZN4fltk6Widget4sendEi(void *This, int);
extern (C) void _BCD__ZN4fltk6Widget6layoutEv(void *This);
extern (C) Style * _BCD__ZNK4fltk6Widget5styleEv(void *This);
extern (C) void _BCD__ZN4fltk6Widget5styleEPKNS_5StyleE(void *This, void *);
extern (C) bool _BCD__ZN4fltk6Widget10copy_styleEPKNS_5StyleE(void *This, void *);
extern (C) bcd.bind.BoundClass * _BCD__ZNK4fltk6Widget6parentEv(void *This);
extern (C) void _BCD__ZN4fltk6Widget6parentEPNS_5GroupE(void *This, void *);
extern (C) bcd.bind.BoundClass * _BCD__ZNK4fltk6Widget6windowEv(void *This);
extern (C) char _BCD__ZNK4fltk6Widget4typeEv(void *This);
extern (C) void _BCD__ZN4fltk6Widget4typeEh(void *This, char);
extern (C) bool _BCD__ZNK4fltk6Widget8is_groupEv(void *This);
extern (C) bool _BCD__ZNK4fltk6Widget9is_windowEv(void *This);
extern (C) bool _BCD__ZN4fltk6Widget6resizeEiiii(void *This, int, int, int, int);
extern (C) bool _BCD__ZN4fltk6Widget8positionEii(void *This, int, int);
extern (C) bool _BCD__ZN4fltk6Widget6resizeEii(void *This, int, int);
extern (C) void _BCD__ZNK4fltk6Widget17get_absolute_rectEPNS_9RectangleE(void *This, void *);
extern (C) char * _BCD__ZNK4fltk6Widget5labelEv(void *This);
extern (C) void _BCD__ZN4fltk6Widget5labelEPKc(void *This, char *);
extern (C) void _BCD__ZN4fltk6Widget10copy_labelEPKc(void *This, char *);
extern (C) bcd.bind.BoundClass * _BCD__ZNK4fltk6Widget5imageEv(void *This);
extern (C) void _BCD__ZN4fltk6Widget5imageEPKNS_6SymbolE(void *This, void *);
extern (C) char * _BCD__ZNK4fltk6Widget7tooltipEv(void *This);
extern (C) void _BCD__ZN4fltk6Widget7tooltipEPKc(void *This, char *);
extern (C) uint _BCD__ZNK4fltk6Widget8shortcutEv(void *This);
extern (C) bool _BCD__ZN4fltk6Widget8shortcutEj(void *This, uint);
extern (C) bool _BCD__ZN4fltk6Widget12add_shortcutEj(void *This, uint);
extern (C) bool _BCD__ZN4fltk6Widget15remove_shortcutEj(void *This, uint);
extern (C) bool _BCD__ZN4fltk6Widget16remove_shortcutsEv(void *This);
extern (C) uint _BCD__ZNK4fltk6Widget14label_shortcutEv(void *This);
extern (C) bool _BCD__ZNK4fltk6Widget19test_label_shortcutEv(void *This);
extern (C) bool _BCD__ZNK4fltk6Widget13test_shortcutEv(void *This);
extern (C) bool _BCD__ZNK4fltk6Widget13test_shortcutEb(void *This, bool);
alias void function(Widget *, void *) _BCD_func__154;
alias _BCD_func__154 Callback;
alias _BCD_func__154 Callback_p;
extern (C) _BCD_func__154 _BCD__ZNK4fltk6Widget8callbackEv(void *This);
extern (C) void _BCD__ZN4fltk6Widget8callbackEPFvPS0_PvES2_(void *This, _BCD_func__154, void *);
extern (C) void _BCD__ZN4fltk6Widget8callbackEPFvPS0_PvE(void *This, _BCD_func__154);
alias void function(Widget *) _BCD_func__150;
alias _BCD_func__150 Callback0;
extern (C) void _BCD__ZN4fltk6Widget8callbackEPFvPS0_E(void *This, _BCD_func__150);
alias void function(Widget *, int) _BCD_func__148;
alias _BCD_func__148 Callback1;
extern (C) void _BCD__ZN4fltk6Widget8callbackEPFvPS0_lEl(void *This, _BCD_func__148, int);
extern (C) void * _BCD__ZNK4fltk6Widget9user_dataEv(void *This);
extern (C) void _BCD__ZN4fltk6Widget9user_dataEPv(void *This, void *);
extern (C) int _BCD__ZNK4fltk6Widget8argumentEv(void *This);
extern (C) void _BCD__ZN4fltk6Widget8argumentEl(void *This, int);
extern (C) char _BCD__ZNK4fltk6Widget4whenEv(void *This);
extern (C) void _BCD__ZN4fltk6Widget4whenEh(void *This, char);
extern (C) void _BCD__ZN4fltk6Widget16default_callbackEPS0_Pv(void *, void *);
extern (C) void _BCD__ZN4fltk6Widget11do_callbackEv(void *This);
extern (C) void _BCD__ZN4fltk6Widget11do_callbackEPS0_Pv(void *This, void *, void *);
extern (C) void _BCD__ZN4fltk6Widget11do_callbackEPS0_l(void *This, void *, int);
extern (C) bool _BCD__ZNK4fltk6Widget8containsEPKS0_(void *This, void *);
extern (C) bool _BCD__ZNK4fltk6Widget6insideEPKS0_(void *This, void *);
extern (C) bool _BCD__ZNK4fltk6Widget6pushedEv(void *This);
extern (C) bool _BCD__ZNK4fltk6Widget7focusedEv(void *This);
extern (C) bool _BCD__ZNK4fltk6Widget10belowmouseEv(void *This);
extern (C) int _BCD__ZNK4fltk6Widget5flagsEv(void *This);
extern (C) void _BCD__ZN4fltk6Widget5flagsEi(void *This, int);
extern (C) void _BCD__ZN4fltk6Widget8set_flagEj(void *This, uint);
extern (C) void _BCD__ZN4fltk6Widget10clear_flagEj(void *This, uint);
extern (C) void _BCD__ZN4fltk6Widget11invert_flagEj(void *This, uint);
extern (C) void _BCD__ZN4fltk6Widget8set_flagEjb(void *This, uint, bool);
extern (C) bool _BCD__ZNK4fltk6Widget4flagEj(void *This, uint);
extern (C) bool _BCD__ZNK4fltk6Widget6any_ofEj(void *This, uint);
extern (C) bool _BCD__ZNK4fltk6Widget6all_ofEj(void *This, uint);
extern (C) bool _BCD__ZNK4fltk6Widget5stateEv(void *This);
extern (C) bool _BCD__ZN4fltk6Widget5stateEb(void *This, bool);
extern (C) bool _BCD__ZN4fltk6Widget3setEv(void *This);
extern (C) bool _BCD__ZN4fltk6Widget5clearEv(void *This);
extern (C) void _BCD__ZN4fltk6Widget7setonlyEv(void *This);
extern (C) int _BCD__ZNK4fltk6Widget5alignEv(void *This);
extern (C) void _BCD__ZN4fltk6Widget5alignEj(void *This, uint);
extern (C) bool _BCD__ZNK4fltk6Widget7visibleEv(void *This);
extern (C) bool _BCD__ZNK4fltk6Widget9visible_rEv(void *This);
extern (C) void _BCD__ZN4fltk6Widget4showEv(void *This);
extern (C) void _BCD__ZN4fltk6Widget4hideEv(void *This);
extern (C) void _BCD__ZN4fltk6Widget11set_visibleEv(void *This);
extern (C) void _BCD__ZN4fltk6Widget13clear_visibleEv(void *This);
extern (C) bool _BCD__ZNK4fltk6Widget6activeEv(void *This);
extern (C) bool _BCD__ZNK4fltk6Widget8active_rEv(void *This);
extern (C) void _BCD__ZN4fltk6Widget8activateEv(void *This);
extern (C) void _BCD__ZN4fltk6Widget8activateEi(void *This, int);
extern (C) void _BCD__ZN4fltk6Widget10deactivateEv(void *This);
extern (C) bool _BCD__ZNK4fltk6Widget6outputEv(void *This);
extern (C) void _BCD__ZN4fltk6Widget10set_outputEv(void *This);
extern (C) void _BCD__ZN4fltk6Widget12clear_outputEv(void *This);
extern (C) bool _BCD__ZNK4fltk6Widget11takeseventsEv(void *This);
extern (C) bool _BCD__ZNK4fltk6Widget7changedEv(void *This);
extern (C) void _BCD__ZN4fltk6Widget11set_changedEv(void *This);
extern (C) void _BCD__ZN4fltk6Widget13clear_changedEv(void *This);
extern (C) bool _BCD__ZNK4fltk6Widget8selectedEv(void *This);
extern (C) void _BCD__ZN4fltk6Widget12set_selectedEv(void *This);
extern (C) void _BCD__ZN4fltk6Widget14clear_selectedEv(void *This);
extern (C) bool _BCD__ZN4fltk6Widget14click_to_focusEv(void *This);
extern (C) void _BCD__ZN4fltk6Widget18set_click_to_focusEv(void *This);
extern (C) void _BCD__ZN4fltk6Widget20clear_click_to_focusEv(void *This);
extern (C) bool _BCD__ZN4fltk6Widget12tab_to_focusEv(void *This);
extern (C) void _BCD__ZN4fltk6Widget16set_tab_to_focusEv(void *This);
extern (C) void _BCD__ZN4fltk6Widget18clear_tab_to_focusEv(void *This);
extern (C) bool _BCD__ZNK4fltk6Widget10horizontalEv(void *This);
extern (C) bool _BCD__ZNK4fltk6Widget8verticalEv(void *This);
extern (C) void _BCD__ZN4fltk6Widget14set_horizontalEv(void *This);
extern (C) void _BCD__ZN4fltk6Widget12set_verticalEv(void *This);
extern (C) bool _BCD__ZN4fltk6Widget10take_focusEv(void *This);
extern (C) void _BCD__ZN4fltk6Widget11throw_focusEv(void *This);
extern (C) void _BCD__ZN4fltk6Widget6redrawEv(void *This);
extern (C) void _BCD__ZN4fltk6Widget6redrawEh(void *This, char);
extern (C) void _BCD__ZN4fltk6Widget12redraw_labelEv(void *This);
extern (C) void _BCD__ZN4fltk6Widget16redraw_highlightEv(void *This);
extern (C) void _BCD__ZN4fltk6Widget6redrawERKNS_9RectangleE(void *This, void *);
extern (C) char _BCD__ZNK4fltk6Widget6damageEv(void *This);
extern (C) void _BCD__ZN4fltk6Widget10set_damageEh(void *This, char);
extern (C) void _BCD__ZN4fltk6Widget8relayoutEv(void *This);
extern (C) void _BCD__ZN4fltk6Widget8relayoutEh(void *This, char);
extern (C) char _BCD__ZNK4fltk6Widget13layout_damageEv(void *This);
extern (C) void _BCD__ZN4fltk6Widget13layout_damageEh(void *This, char);
extern (C) void _BCD__ZN4fltk6Widget11add_timeoutEf(void *This, float);
extern (C) void _BCD__ZN4fltk6Widget14repeat_timeoutEf(void *This, float);
extern (C) void _BCD__ZN4fltk6Widget14remove_timeoutEv(void *This);
extern (C) void _BCD__ZNK4fltk6Widget12make_currentEv(void *This);
extern (C) void _BCD__ZNK4fltk6Widget15draw_backgroundEv(void *This);
extern (C) void _BCD__ZNK4fltk6Widget10draw_frameEv(void *This);
extern (C) void _BCD__ZNK4fltk6Widget8draw_boxEv(void *This);
extern (C) void _BCD__ZNK4fltk6Widget8draw_boxERKNS_9RectangleE(void *This, void *);
extern (C) void _BCD__ZNK4fltk6Widget10draw_labelEv(void *This);
extern (C) void _BCD__ZNK4fltk6Widget10draw_labelERKNS_9RectangleEi(void *This, void *, int);
extern (C) void _BCD__ZNK4fltk6Widget10draw_glyphEiRKNS_9RectangleE(void *This, int, void *);
extern (C) void _BCD__ZNK4fltk6Widget6cursorEPNS_6CursorE(void *This, void *);
extern (C) void _BCD__ZNK4fltk6Widget13measure_labelERiS1_(void *This, int *, int *);
extern (C) bcd.bind.BoundClass * _BCD__ZNK4fltk6Widget3boxEv(void *This);
extern (C) bcd.bind.BoundClass * _BCD__ZNK4fltk6Widget9buttonboxEv(void *This);
extern (C) bcd.bind.BoundClass * _BCD__ZNK4fltk6Widget5glyphEv(void *This);
extern (C) bcd.bind.BoundClass * _BCD__ZNK4fltk6Widget9labelfontEv(void *This);
extern (C) bcd.bind.BoundClass * _BCD__ZNK4fltk6Widget8textfontEv(void *This);
extern (C) bcd.bind.BoundClass * _BCD__ZNK4fltk6Widget9labeltypeEv(void *This);
extern (C) uint _BCD__ZNK4fltk6Widget5colorEv(void *This);
extern (C) uint _BCD__ZNK4fltk6Widget9textcolorEv(void *This);
extern (C) uint _BCD__ZNK4fltk6Widget15selection_colorEv(void *This);
extern (C) uint _BCD__ZNK4fltk6Widget19selection_textcolorEv(void *This);
extern (C) uint _BCD__ZNK4fltk6Widget11buttoncolorEv(void *This);
extern (C) uint _BCD__ZNK4fltk6Widget10labelcolorEv(void *This);
extern (C) uint _BCD__ZNK4fltk6Widget15highlight_colorEv(void *This);
extern (C) uint _BCD__ZNK4fltk6Widget19highlight_textcolorEv(void *This);
extern (C) float _BCD__ZNK4fltk6Widget9labelsizeEv(void *This);
extern (C) float _BCD__ZNK4fltk6Widget8textsizeEv(void *This);
extern (C) float _BCD__ZNK4fltk6Widget7leadingEv(void *This);
extern (C) char _BCD__ZNK4fltk6Widget15scrollbar_alignEv(void *This);
extern (C) char _BCD__ZNK4fltk6Widget15scrollbar_widthEv(void *This);
extern (C) void _BCD__ZN4fltk6Widget3boxEPNS_6SymbolE(void *This, void *);
extern (C) void _BCD__ZN4fltk6Widget9buttonboxEPNS_6SymbolE(void *This, void *);
extern (C) void _BCD__ZN4fltk6Widget5glyphEPNS_6SymbolE(void *This, void *);
extern (C) void _BCD__ZN4fltk6Widget9labelfontEPNS_4FontE(void *This, void *);
extern (C) void _BCD__ZN4fltk6Widget8textfontEPNS_4FontE(void *This, void *);
extern (C) void _BCD__ZN4fltk6Widget9labeltypeEPNS_9LabelTypeE(void *This, void *);
extern (C) void _BCD__ZN4fltk6Widget5colorEj(void *This, uint);
extern (C) void _BCD__ZN4fltk6Widget9textcolorEj(void *This, uint);
extern (C) void _BCD__ZN4fltk6Widget15selection_colorEj(void *This, uint);
extern (C) void _BCD__ZN4fltk6Widget19selection_textcolorEj(void *This, uint);
extern (C) void _BCD__ZN4fltk6Widget11buttoncolorEj(void *This, uint);
extern (C) void _BCD__ZN4fltk6Widget10labelcolorEj(void *This, uint);
extern (C) void _BCD__ZN4fltk6Widget15highlight_colorEj(void *This, uint);
extern (C) void _BCD__ZN4fltk6Widget19highlight_textcolorEj(void *This, uint);
extern (C) void _BCD__ZN4fltk6Widget9labelsizeEf(void *This, float);
extern (C) void _BCD__ZN4fltk6Widget8textsizeEf(void *This, float);
extern (C) void _BCD__ZN4fltk6Widget7leadingEf(void *This, float);
extern (C) void _BCD__ZN4fltk6Widget15scrollbar_alignEh(void *This, char);
extern (C) void _BCD__ZN4fltk6Widget15scrollbar_widthEh(void *This, char);
extern (C) void _BCD_RI_N4fltk6WidgetE(void *cd, void *dd);
extern (C) void _BCD_delete_N4fltk6WidgetE__Widget_R(void *This);
extern (C) void *_BCD_new__ZN4fltk6WidgetC1EiiiiPKc_R(int, int, int, int, char *);
extern (C) int _BCD_R__ZN4fltk6Widget4drawEv__Widget_R_CHECK(Widget_R x) {
union dp {
void delegate() d;
struct { void *o; void *f; }
}
dp d; d.d = &x.draw;
return cast(int) (d.f != &Widget.draw);
}
extern (C) void _BCD_R__ZN4fltk6Widget4drawEv__Widget_R(Widget_R __D_class, ) {
__D_class.draw();
}
extern (C) int _BCD_R__ZN4fltk6Widget6handleEi__Widget_R_CHECK(Widget_R x) {
union dp {
int delegate(int) d;
struct { void *o; void *f; }
}
dp d; d.d = &x.handle;
return cast(int) (d.f != &Widget.handle);
}
extern (C) int _BCD_R__ZN4fltk6Widget6handleEi__Widget_R(Widget_R __D_class, int _0) {
return __D_class.handle(_0);
}
extern (C) int _BCD_R__ZN4fltk6Widget6layoutEv__Widget_R_CHECK(Widget_R x) {
union dp {
void delegate() d;
struct { void *o; void *f; }
}
dp d; d.d = &x.layout;
return cast(int) (d.f != &Widget.layout);
}
extern (C) void _BCD_R__ZN4fltk6Widget6layoutEv__Widget_R(Widget_R __D_class, ) {
__D_class.layout();
}
const int WHEN_NEVER = 0;
const int WHEN_CHANGED = 1;
const int WHEN_RELEASE = 4;
const int WHEN_RELEASE_ALWAYS = 6;
const int WHEN_ENTER_KEY = 8;
const int WHEN_ENTER_KEY_ALWAYS = 10;
const int WHEN_ENTER_KEY_CHANGED = 11;
const int WHEN_NOT_CHANGED = 2;
alias bool function() _BCD_func__248;
enum WidgetVisualType {
RESERVED_TYPE=100,
TOGGLE=101,
RADIO=102,
GROUP_TYPE=224,
WINDOW_TYPE=240,
}
alias WidgetVisualType.RESERVED_TYPE RESERVED_TYPE;
alias WidgetVisualType.TOGGLE TOGGLE;
alias WidgetVisualType.RADIO RADIO;
alias WidgetVisualType.GROUP_TYPE GROUP_TYPE;
alias WidgetVisualType.WINDOW_TYPE WINDOW_TYPE;
class Widget : Rectangle {
this(ifloat ignore) {
super(ignore);
}
this(ifloat ignore, void *x) {
super(ignore);
__C_data = x;
__C_data_owned = false;
}
~this() {
if (__C_data && __C_data_owned) _BCD_delete_N4fltk6WidgetE(__C_data);
__C_data = null;
}
void set_default_style(NamedStyle * x) {
_BCD_set__ZN4fltk6Widget13default_styleE(__C_data, x);
}
NamedStyle * get_default_style() {
return _BCD_get__ZN4fltk6Widget13default_styleE(__C_data);
}
void set_default_glyph(bcd.bind.BoundClass * x) {
_BCD_set__ZN4fltk6Widget13default_glyphE(__C_data, x);
}
bcd.bind.BoundClass * get_default_glyph() {
return _BCD_get__ZN4fltk6Widget13default_glyphE(__C_data);
}
this(int _0, int _1, int _2, int _3, char * _4 = null) {
super(cast(ifloat) 0);
__C_data = _BCD_new__ZN4fltk6WidgetC1EiiiiPKc(_0, _1, _2, _3, _4);
__C_data_owned = true;
}
void draw() {
_BCD__ZN4fltk6Widget4drawEv(__C_data);
}
int handle(int _0) {
return _BCD__ZN4fltk6Widget6handleEi(__C_data, _0);
}
int send(int event) {
return _BCD__ZN4fltk6Widget4sendEi(__C_data, event);
}
void layout() {
_BCD__ZN4fltk6Widget6layoutEv(__C_data);
}
Style * style() {
return _BCD__ZNK4fltk6Widget5styleEv(__C_data);
}
void style(Style * s) {
_BCD__ZN4fltk6Widget5styleEPKNS_5StyleE(__C_data, s.__C_data);
}
bool copy_style(Style * s) {
return _BCD__ZN4fltk6Widget10copy_styleEPKNS_5StyleE(__C_data, s.__C_data);
}
bcd.bind.BoundClass * parent() {
return _BCD__ZNK4fltk6Widget6parentEv(__C_data);
}
void parent(bcd.bind.BoundClass * w) {
_BCD__ZN4fltk6Widget6parentEPNS_5GroupE(__C_data, w.__C_data);
}
bcd.bind.BoundClass * window() {
return _BCD__ZNK4fltk6Widget6windowEv(__C_data);
}
char type() {
return _BCD__ZNK4fltk6Widget4typeEv(__C_data);
}
void type(char t) {
_BCD__ZN4fltk6Widget4typeEh(__C_data, t);
}
bool is_group() {
return _BCD__ZNK4fltk6Widget8is_groupEv(__C_data);
}
bool is_window() {
return _BCD__ZNK4fltk6Widget9is_windowEv(__C_data);
}
bool resize(int x, int y, int w, int h) {
return _BCD__ZN4fltk6Widget6resizeEiiii(__C_data, x, y, w, h);
}
bool position(int x, int y) {
return _BCD__ZN4fltk6Widget8positionEii(__C_data, x, y);
}
bool resize(int w, int h) {
return _BCD__ZN4fltk6Widget6resizeEii(__C_data, w, h);
}
void get_absolute_rect(Rectangle * rect) {
_BCD__ZNK4fltk6Widget17get_absolute_rectEPNS_9RectangleE(__C_data, rect.__C_data);
}
char * label() {
return _BCD__ZNK4fltk6Widget5labelEv(__C_data);
}
void label(char * a) {
_BCD__ZN4fltk6Widget5labelEPKc(__C_data, a);
}
void copy_label(char * a) {
_BCD__ZN4fltk6Widget10copy_labelEPKc(__C_data, a);
}
bcd.bind.BoundClass * image() {
return _BCD__ZNK4fltk6Widget5imageEv(__C_data);
}
void image(bcd.bind.BoundClass * a) {
_BCD__ZN4fltk6Widget5imageEPKNS_6SymbolE(__C_data, a.__C_data);
}
char * tooltip() {
return _BCD__ZNK4fltk6Widget7tooltipEv(__C_data);
}
void tooltip(char * t) {
_BCD__ZN4fltk6Widget7tooltipEPKc(__C_data, t);
}
uint shortcut() {
return _BCD__ZNK4fltk6Widget8shortcutEv(__C_data);
}
bool shortcut(uint key) {
return _BCD__ZN4fltk6Widget8shortcutEj(__C_data, key);
}
bool add_shortcut(uint key) {
return _BCD__ZN4fltk6Widget12add_shortcutEj(__C_data, key);
}
bool remove_shortcut(uint key) {
return _BCD__ZN4fltk6Widget15remove_shortcutEj(__C_data, key);
}
bool remove_shortcuts() {
return _BCD__ZN4fltk6Widget16remove_shortcutsEv(__C_data);
}
uint label_shortcut() {
return _BCD__ZNK4fltk6Widget14label_shortcutEv(__C_data);
}
bool test_label_shortcut() {
return _BCD__ZNK4fltk6Widget19test_label_shortcutEv(__C_data);
}
bool test_shortcut() {
return _BCD__ZNK4fltk6Widget13test_shortcutEv(__C_data);
}
bool test_shortcut(bool _0) {
return _BCD__ZNK4fltk6Widget13test_shortcutEb(__C_data, _0);
}
_BCD_func__154 callback() {
return _BCD__ZNK4fltk6Widget8callbackEv(__C_data);
}
void callback(_BCD_func__154 c, void * p) {
_BCD__ZN4fltk6Widget8callbackEPFvPS0_PvES2_(__C_data, c, p);
}
void callback(_BCD_func__154 c) {
_BCD__ZN4fltk6Widget8callbackEPFvPS0_PvE(__C_data, c);
}
void callback(_BCD_func__150 c) {
_BCD__ZN4fltk6Widget8callbackEPFvPS0_E(__C_data, c);
}
void callback(_BCD_func__148 c, int p = 0) {
_BCD__ZN4fltk6Widget8callbackEPFvPS0_lEl(__C_data, c, p);
}
void * user_data() {
return _BCD__ZNK4fltk6Widget9user_dataEv(__C_data);
}
void user_data(void * v) {
_BCD__ZN4fltk6Widget9user_dataEPv(__C_data, v);
}
int argument() {
return _BCD__ZNK4fltk6Widget8argumentEv(__C_data);
}
void argument(int v) {
_BCD__ZN4fltk6Widget8argumentEl(__C_data, v);
}
char when() {
return _BCD__ZNK4fltk6Widget4whenEv(__C_data);
}
void when(char i) {
_BCD__ZN4fltk6Widget4whenEh(__C_data, i);
}
static void default_callback(Widget * _0, void * _1) {
_BCD__ZN4fltk6Widget16default_callbackEPS0_Pv(_0.__C_data, _1);
}
void do_callback() {
_BCD__ZN4fltk6Widget11do_callbackEv(__C_data);
}
void do_callback(Widget * o, void * arg = null) {
_BCD__ZN4fltk6Widget11do_callbackEPS0_Pv(__C_data, o.__C_data, arg);
}
void do_callback(Widget * o, int arg) {
_BCD__ZN4fltk6Widget11do_callbackEPS0_l(__C_data, o.__C_data, arg);
}
bool contains(Widget * _0) {
return _BCD__ZNK4fltk6Widget8containsEPKS0_(__C_data, _0.__C_data);
}
bool inside(Widget * o) {
return _BCD__ZNK4fltk6Widget6insideEPKS0_(__C_data, o.__C_data);
}
bool pushed() {
return _BCD__ZNK4fltk6Widget6pushedEv(__C_data);
}
bool focused() {
return _BCD__ZNK4fltk6Widget7focusedEv(__C_data);
}
bool belowmouse() {
return _BCD__ZNK4fltk6Widget10belowmouseEv(__C_data);
}
int flags() {
return _BCD__ZNK4fltk6Widget5flagsEv(__C_data);
}
void flags(int f) {
_BCD__ZN4fltk6Widget5flagsEi(__C_data, f);
}
void set_flag(uint f) {
_BCD__ZN4fltk6Widget8set_flagEj(__C_data, f);
}
void clear_flag(uint f) {
_BCD__ZN4fltk6Widget10clear_flagEj(__C_data, f);
}
void invert_flag(uint f) {
_BCD__ZN4fltk6Widget11invert_flagEj(__C_data, f);
}
void set_flag(uint f, bool b) {
_BCD__ZN4fltk6Widget8set_flagEjb(__C_data, f, b);
}
bool flag(uint f) {
return _BCD__ZNK4fltk6Widget4flagEj(__C_data, f);
}
bool any_of(uint f) {
return _BCD__ZNK4fltk6Widget6any_ofEj(__C_data, f);
}
bool all_of(uint f) {
return _BCD__ZNK4fltk6Widget6all_ofEj(__C_data, f);
}
bool state() {
return _BCD__ZNK4fltk6Widget5stateEv(__C_data);
}
bool state(bool _0) {
return _BCD__ZN4fltk6Widget5stateEb(__C_data, _0);
}
bool set() {
return _BCD__ZN4fltk6Widget3setEv(__C_data);
}
bool clear() {
return _BCD__ZN4fltk6Widget5clearEv(__C_data);
}
void setonly() {
_BCD__ZN4fltk6Widget7setonlyEv(__C_data);
}
int align_() {
return _BCD__ZNK4fltk6Widget5alignEv(__C_data);
}
void align_(uint a) {
_BCD__ZN4fltk6Widget5alignEj(__C_data, a);
}
bool visible() {
return _BCD__ZNK4fltk6Widget7visibleEv(__C_data);
}
bool visible_r() {
return _BCD__ZNK4fltk6Widget9visible_rEv(__C_data);
}
void show() {
_BCD__ZN4fltk6Widget4showEv(__C_data);
}
void hide() {
_BCD__ZN4fltk6Widget4hideEv(__C_data);
}
void set_visible() {
_BCD__ZN4fltk6Widget11set_visibleEv(__C_data);
}
void clear_visible() {
_BCD__ZN4fltk6Widget13clear_visibleEv(__C_data);
}
bool active() {
return _BCD__ZNK4fltk6Widget6activeEv(__C_data);
}
bool active_r() {
return _BCD__ZNK4fltk6Widget8active_rEv(__C_data);
}
void activate() {
_BCD__ZN4fltk6Widget8activateEv(__C_data);
}
void activate(int b) {
_BCD__ZN4fltk6Widget8activateEi(__C_data, b);
}
void deactivate() {
_BCD__ZN4fltk6Widget10deactivateEv(__C_data);
}
bool output() {
return _BCD__ZNK4fltk6Widget6outputEv(__C_data);
}
void set_output() {
_BCD__ZN4fltk6Widget10set_outputEv(__C_data);
}
void clear_output() {
_BCD__ZN4fltk6Widget12clear_outputEv(__C_data);
}
bool takesevents() {
return _BCD__ZNK4fltk6Widget11takeseventsEv(__C_data);
}
bool changed() {
return _BCD__ZNK4fltk6Widget7changedEv(__C_data);
}
void set_changed() {
_BCD__ZN4fltk6Widget11set_changedEv(__C_data);
}
void clear_changed() {
_BCD__ZN4fltk6Widget13clear_changedEv(__C_data);
}
bool selected() {
return _BCD__ZNK4fltk6Widget8selectedEv(__C_data);
}
void set_selected() {
_BCD__ZN4fltk6Widget12set_selectedEv(__C_data);
}
void clear_selected() {
_BCD__ZN4fltk6Widget14clear_selectedEv(__C_data);
}
bool click_to_focus() {
return _BCD__ZN4fltk6Widget14click_to_focusEv(__C_data);
}
void set_click_to_focus() {
_BCD__ZN4fltk6Widget18set_click_to_focusEv(__C_data);
}
void clear_click_to_focus() {
_BCD__ZN4fltk6Widget20clear_click_to_focusEv(__C_data);
}
bool tab_to_focus() {
return _BCD__ZN4fltk6Widget12tab_to_focusEv(__C_data);
}
void set_tab_to_focus() {
_BCD__ZN4fltk6Widget16set_tab_to_focusEv(__C_data);
}
void clear_tab_to_focus() {
_BCD__ZN4fltk6Widget18clear_tab_to_focusEv(__C_data);
}
bool horizontal() {
return _BCD__ZNK4fltk6Widget10horizontalEv(__C_data);
}
bool vertical() {
return _BCD__ZNK4fltk6Widget8verticalEv(__C_data);
}
void set_horizontal() {
_BCD__ZN4fltk6Widget14set_horizontalEv(__C_data);
}
void set_vertical() {
_BCD__ZN4fltk6Widget12set_verticalEv(__C_data);
}
bool take_focus() {
return _BCD__ZN4fltk6Widget10take_focusEv(__C_data);
}
void throw_focus() {
_BCD__ZN4fltk6Widget11throw_focusEv(__C_data);
}
void redraw() {
_BCD__ZN4fltk6Widget6redrawEv(__C_data);
}
void redraw(char c) {
_BCD__ZN4fltk6Widget6redrawEh(__C_data, c);
}
void redraw_label() {
_BCD__ZN4fltk6Widget12redraw_labelEv(__C_data);
}
void redraw_highlight() {
_BCD__ZN4fltk6Widget16redraw_highlightEv(__C_data);
}
void redraw(Rectangle _0) {
_BCD__ZN4fltk6Widget6redrawERKNS_9RectangleE(__C_data, _0.__C_data);
}
char damage() {
return _BCD__ZNK4fltk6Widget6damageEv(__C_data);
}
void set_damage(char c) {
_BCD__ZN4fltk6Widget10set_damageEh(__C_data, c);
}
void relayout() {
_BCD__ZN4fltk6Widget8relayoutEv(__C_data);
}
void relayout(char damage) {
_BCD__ZN4fltk6Widget8relayoutEh(__C_data, damage);
}
char layout_damage() {
return _BCD__ZNK4fltk6Widget13layout_damageEv(__C_data);
}
void layout_damage(char c) {
_BCD__ZN4fltk6Widget13layout_damageEh(__C_data, c);
}
void add_timeout(float _0) {
_BCD__ZN4fltk6Widget11add_timeoutEf(__C_data, _0);
}
void repeat_timeout(float _0) {
_BCD__ZN4fltk6Widget14repeat_timeoutEf(__C_data, _0);
}
void remove_timeout() {
_BCD__ZN4fltk6Widget14remove_timeoutEv(__C_data);
}
void make_current() {
_BCD__ZNK4fltk6Widget12make_currentEv(__C_data);
}
void draw_background() {
_BCD__ZNK4fltk6Widget15draw_backgroundEv(__C_data);
}
void draw_frame() {
_BCD__ZNK4fltk6Widget10draw_frameEv(__C_data);
}
void draw_box() {
_BCD__ZNK4fltk6Widget8draw_boxEv(__C_data);
}
void draw_box(Rectangle r) {
_BCD__ZNK4fltk6Widget8draw_boxERKNS_9RectangleE(__C_data, r.__C_data);
}
void draw_label() {
_BCD__ZNK4fltk6Widget10draw_labelEv(__C_data);
}
void draw_label(Rectangle _0, int _1) {
_BCD__ZNK4fltk6Widget10draw_labelERKNS_9RectangleEi(__C_data, _0.__C_data, _1);
}
void draw_glyph(int _0, Rectangle _1) {
_BCD__ZNK4fltk6Widget10draw_glyphEiRKNS_9RectangleE(__C_data, _0, _1.__C_data);
}
void cursor(bcd.bind.BoundClass * _0) {
_BCD__ZNK4fltk6Widget6cursorEPNS_6CursorE(__C_data, _0.__C_data);
}
void measure_label(int * _0, int * _1) {
_BCD__ZNK4fltk6Widget13measure_labelERiS1_(__C_data, _0, _1);
}
bcd.bind.BoundClass * box() {
return _BCD__ZNK4fltk6Widget3boxEv(__C_data);
}
bcd.bind.BoundClass * buttonbox() {
return _BCD__ZNK4fltk6Widget9buttonboxEv(__C_data);
}
bcd.bind.BoundClass * glyph() {
return _BCD__ZNK4fltk6Widget5glyphEv(__C_data);
}
bcd.bind.BoundClass * labelfont() {
return _BCD__ZNK4fltk6Widget9labelfontEv(__C_data);
}
bcd.bind.BoundClass * textfont() {
return _BCD__ZNK4fltk6Widget8textfontEv(__C_data);
}
bcd.bind.BoundClass * labeltype() {
return _BCD__ZNK4fltk6Widget9labeltypeEv(__C_data);
}
uint color() {
return _BCD__ZNK4fltk6Widget5colorEv(__C_data);
}
uint textcolor() {
return _BCD__ZNK4fltk6Widget9textcolorEv(__C_data);
}
uint selection_color() {
return _BCD__ZNK4fltk6Widget15selection_colorEv(__C_data);
}
uint selection_textcolor() {
return _BCD__ZNK4fltk6Widget19selection_textcolorEv(__C_data);
}
uint buttoncolor() {
return _BCD__ZNK4fltk6Widget11buttoncolorEv(__C_data);
}
uint labelcolor() {
return _BCD__ZNK4fltk6Widget10labelcolorEv(__C_data);
}
uint highlight_color() {
return _BCD__ZNK4fltk6Widget15highlight_colorEv(__C_data);
}
uint highlight_textcolor() {
return _BCD__ZNK4fltk6Widget19highlight_textcolorEv(__C_data);
}
float labelsize() {
return _BCD__ZNK4fltk6Widget9labelsizeEv(__C_data);
}
float textsize() {
return _BCD__ZNK4fltk6Widget8textsizeEv(__C_data);
}
float leading() {
return _BCD__ZNK4fltk6Widget7leadingEv(__C_data);
}
char scrollbar_align() {
return _BCD__ZNK4fltk6Widget15scrollbar_alignEv(__C_data);
}
char scrollbar_width() {
return _BCD__ZNK4fltk6Widget15scrollbar_widthEv(__C_data);
}
void box(bcd.bind.BoundClass * _0) {
_BCD__ZN4fltk6Widget3boxEPNS_6SymbolE(__C_data, _0.__C_data);
}
void buttonbox(bcd.bind.BoundClass * _0) {
_BCD__ZN4fltk6Widget9buttonboxEPNS_6SymbolE(__C_data, _0.__C_data);
}
void glyph(bcd.bind.BoundClass * _0) {
_BCD__ZN4fltk6Widget5glyphEPNS_6SymbolE(__C_data, _0.__C_data);
}
void labelfont(bcd.bind.BoundClass * _0) {
_BCD__ZN4fltk6Widget9labelfontEPNS_4FontE(__C_data, _0.__C_data);
}
void textfont(bcd.bind.BoundClass * _0) {
_BCD__ZN4fltk6Widget8textfontEPNS_4FontE(__C_data, _0.__C_data);
}
void labeltype(bcd.bind.BoundClass * _0) {
_BCD__ZN4fltk6Widget9labeltypeEPNS_9LabelTypeE(__C_data, _0.__C_data);
}
void color(uint _0) {
_BCD__ZN4fltk6Widget5colorEj(__C_data, _0);
}
void textcolor(uint a) {
_BCD__ZN4fltk6Widget9textcolorEj(__C_data, a);
}
void selection_color(uint _0) {
_BCD__ZN4fltk6Widget15selection_colorEj(__C_data, _0);
}
void selection_textcolor(uint _0) {
_BCD__ZN4fltk6Widget19selection_textcolorEj(__C_data, _0);
}
void buttoncolor(uint _0) {
_BCD__ZN4fltk6Widget11buttoncolorEj(__C_data, _0);
}
void labelcolor(uint _0) {
_BCD__ZN4fltk6Widget10labelcolorEj(__C_data, _0);
}
void highlight_color(uint _0) {
_BCD__ZN4fltk6Widget15highlight_colorEj(__C_data, _0);
}
void highlight_textcolor(uint _0) {
_BCD__ZN4fltk6Widget19highlight_textcolorEj(__C_data, _0);
}
void labelsize(float a) {
_BCD__ZN4fltk6Widget9labelsizeEf(__C_data, a);
}
void textsize(float a) {
_BCD__ZN4fltk6Widget8textsizeEf(__C_data, a);
}
void leading(float a) {
_BCD__ZN4fltk6Widget7leadingEf(__C_data, a);
}
void scrollbar_align(char _0) {
_BCD__ZN4fltk6Widget15scrollbar_alignEh(__C_data, _0);
}
void scrollbar_width(char _0) {
_BCD__ZN4fltk6Widget15scrollbar_widthEh(__C_data, _0);
}
}
class Widget_R : Widget {
~this() {
if (__C_data && __C_data_owned) _BCD_delete_N4fltk6WidgetE__Widget_R(__C_data);
__C_data = null;
}
this(int _0, int _1, int _2, int _3, char * _4 = null) {
super(cast(ifloat) 0);
__C_data = _BCD_new__ZN4fltk6WidgetC1EiiiiPKc_R(_0, _1, _2, _3, _4);
__C_data_owned = true;
_BCD_RI_N4fltk6WidgetE(__C_data, cast(void *) this);
}
}
