/* THIS FILE GENERATED BY bcd.gen */
module bcd.fltk2.Box;
align(4):
public import bcd.bind;
public import bcd.fltk2.Symbol;
public import bcd.fltk2.FL_API;
public import bcd.fltk2.PixelType;
public import bcd.fltk2.Rectangle;
public import bcd.fltk2.Color;
public import bcd.fltk2.Flags;
extern (C) void _BCD_delete_N4fltk12HighlightBoxE(void *);
extern (C) void _BCD__ZNK4fltk12HighlightBox5_drawERKNS_9RectangleE(void *This, void *);
extern (C) bool _BCD__ZNK4fltk12HighlightBox15fills_rectangleEv(void *This);
extern (C) bool _BCD__ZNK4fltk12HighlightBox8is_frameEv(void *This);
alias Symbol Box;
extern (C) void *_BCD_new__ZN4fltk12HighlightBoxC1EPKcPKNS_6SymbolE(char *, void *);
extern (C) void _BCD_RI_N4fltk12HighlightBoxE(void *cd, void *dd);
extern (C) void _BCD_delete_N4fltk12HighlightBoxE__HighlightBox_R(void *This);
extern (C) int _BCD_R__ZNK4fltk7FlatBox5_drawERKNS_9RectangleE__HighlightBox_R_CHECK(HighlightBox_R x) {
union dp {
void delegate(Rectangle) d;
struct { void *o; void *f; }
}
dp d; d.d = &x._draw;
return cast(int) (d.f != &HighlightBox._draw);
}
extern (C) void _BCD_R__ZNK4fltk7FlatBox5_drawERKNS_9RectangleE__HighlightBox_R(HighlightBox_R __D_class, void *_0) {
__D_class._draw(cast(Rectangle) new Rectangle(cast(ifloat) 0, _0));
}
extern (C) int _BCD_R__ZNK4fltk7FlatBox15fills_rectangleEv__HighlightBox_R_CHECK(HighlightBox_R x) {
union dp {
bool delegate() d;
struct { void *o; void *f; }
}
dp d; d.d = &x.fills_rectangle;
return cast(int) (d.f != &HighlightBox.fills_rectangle);
}
extern (C) bool _BCD_R__ZNK4fltk7FlatBox15fills_rectangleEv__HighlightBox_R(HighlightBox_R __D_class, ) {
return __D_class.fills_rectangle();
}
extern (C) int _BCD_R__ZNK4fltk7FlatBox8is_frameEv__HighlightBox_R_CHECK(HighlightBox_R x) {
union dp {
bool delegate() d;
struct { void *o; void *f; }
}
dp d; d.d = &x.is_frame;
return cast(int) (d.f != &HighlightBox.is_frame);
}
extern (C) bool _BCD_R__ZNK4fltk7FlatBox8is_frameEv__HighlightBox_R(HighlightBox_R __D_class, ) {
return __D_class.is_frame();
}
extern (C) void *_BCD_new__ZN4fltk12HighlightBoxC1EPKcPKNS_6SymbolE_R(char *, void *);
extern (C) void _BCD_delete_N4fltk7FlatBoxE(void *);
extern (C) void _BCD__ZNK4fltk7FlatBox5_drawERKNS_9RectangleE(void *This, void *);
extern (C) bool _BCD__ZNK4fltk7FlatBox15fills_rectangleEv(void *This);
extern (C) bool _BCD__ZNK4fltk7FlatBox8is_frameEv(void *This);
extern (C) void *_BCD_new__ZN4fltk7FlatBoxC1EPKc(char *);
extern (C) void _BCD_RI_N4fltk7FlatBoxE(void *cd, void *dd);
extern (C) void _BCD_delete_N4fltk7FlatBoxE__FlatBox_R(void *This);
extern (C) int _BCD_R__ZNK4fltk7FlatBox5_drawERKNS_9RectangleE__FlatBox_R_CHECK(FlatBox_R x) {
union dp {
void delegate(Rectangle) d;
struct { void *o; void *f; }
}
dp d; d.d = &x._draw;
return cast(int) (d.f != &FlatBox._draw);
}
extern (C) void _BCD_R__ZNK4fltk7FlatBox5_drawERKNS_9RectangleE__FlatBox_R(FlatBox_R __D_class, void *_0) {
__D_class._draw(cast(Rectangle) new Rectangle(cast(ifloat) 0, _0));
}
extern (C) int _BCD_R__ZNK4fltk7FlatBox15fills_rectangleEv__FlatBox_R_CHECK(FlatBox_R x) {
union dp {
bool delegate() d;
struct { void *o; void *f; }
}
dp d; d.d = &x.fills_rectangle;
return cast(int) (d.f != &FlatBox.fills_rectangle);
}
extern (C) bool _BCD_R__ZNK4fltk7FlatBox15fills_rectangleEv__FlatBox_R(FlatBox_R __D_class, ) {
return __D_class.fills_rectangle();
}
extern (C) int _BCD_R__ZNK4fltk7FlatBox8is_frameEv__FlatBox_R_CHECK(FlatBox_R x) {
union dp {
bool delegate() d;
struct { void *o; void *f; }
}
dp d; d.d = &x.is_frame;
return cast(int) (d.f != &FlatBox.is_frame);
}
extern (C) bool _BCD_R__ZNK4fltk7FlatBox8is_frameEv__FlatBox_R(FlatBox_R __D_class, ) {
return __D_class.is_frame();
}
extern (C) void *_BCD_new__ZN4fltk7FlatBoxC1EPKc_R(char *);
extern (C) void _BCD_delete_N4fltk8FrameBoxE(void *);
extern (C) char * _BCD__ZNK4fltk8FrameBox4dataEv(void *This);
extern (C) void _BCD__ZN4fltk8FrameBox4dataEPKc(void *This, char *);
extern (C) void _BCD__ZNK4fltk8FrameBox5_drawERKNS_9RectangleE(void *This, void *);
extern (C) void _BCD__ZNK4fltk8FrameBox5insetERNS_9RectangleE(void *This, void *);
extern (C) bool _BCD__ZNK4fltk8FrameBox15fills_rectangleEv(void *This);
extern (C) bool _BCD__ZNK4fltk8FrameBox8is_frameEv(void *This);
extern (C) void *_BCD_new__ZN4fltk8FrameBoxC1EPKciiiiS2_PKNS_6SymbolE(char *, int, int, int, int, char *, void *);
extern (C) void _BCD_RI_N4fltk8FrameBoxE(void *cd, void *dd);
extern (C) void _BCD_delete_N4fltk8FrameBoxE__FrameBox_R(void *This);
extern (C) int _BCD_R__ZNK4fltk8FrameBox5_drawERKNS_9RectangleE__FrameBox_R_CHECK(FrameBox_R x) {
union dp {
void delegate(Rectangle) d;
struct { void *o; void *f; }
}
dp d; d.d = &x._draw;
return cast(int) (d.f != &FrameBox._draw);
}
extern (C) void _BCD_R__ZNK4fltk8FrameBox5_drawERKNS_9RectangleE__FrameBox_R(FrameBox_R __D_class, void *_0) {
__D_class._draw(cast(Rectangle) new Rectangle(cast(ifloat) 0, _0));
}
extern (C) int _BCD_R__ZNK4fltk8FrameBox5insetERNS_9RectangleE__FrameBox_R_CHECK(FrameBox_R x) {
union dp {
void delegate(Rectangle) d;
struct { void *o; void *f; }
}
dp d; d.d = &x.inset;
return cast(int) (d.f != &FrameBox.inset);
}
extern (C) void _BCD_R__ZNK4fltk8FrameBox5insetERNS_9RectangleE__FrameBox_R(FrameBox_R __D_class, void *_0) {
__D_class.inset(cast(Rectangle) new Rectangle(cast(ifloat) 0, _0));
}
extern (C) int _BCD_R__ZNK4fltk8FrameBox15fills_rectangleEv__FrameBox_R_CHECK(FrameBox_R x) {
union dp {
bool delegate() d;
struct { void *o; void *f; }
}
dp d; d.d = &x.fills_rectangle;
return cast(int) (d.f != &FrameBox.fills_rectangle);
}
extern (C) bool _BCD_R__ZNK4fltk8FrameBox15fills_rectangleEv__FrameBox_R(FrameBox_R __D_class, ) {
return __D_class.fills_rectangle();
}
extern (C) int _BCD_R__ZNK4fltk8FrameBox8is_frameEv__FrameBox_R_CHECK(FrameBox_R x) {
union dp {
bool delegate() d;
struct { void *o; void *f; }
}
dp d; d.d = &x.is_frame;
return cast(int) (d.f != &FrameBox.is_frame);
}
extern (C) bool _BCD_R__ZNK4fltk8FrameBox8is_frameEv__FrameBox_R(FrameBox_R __D_class, ) {
return __D_class.is_frame();
}
extern (C) void *_BCD_new__ZN4fltk8FrameBoxC1EPKciiiiS2_PKNS_6SymbolE_R(char *, int, int, int, int, char *, void *);
class HighlightBox : FlatBox {
this(ifloat ignore) {
super(ignore);
}
this(ifloat ignore, void *x) {
super(ignore);
__C_data = x;
__C_data_owned = false;
}
~this() {
if (__C_data && __C_data_owned) _BCD_delete_N4fltk12HighlightBoxE(__C_data);
__C_data = null;
}
void _draw(Rectangle _0) {
_BCD__ZNK4fltk12HighlightBox5_drawERKNS_9RectangleE(__C_data, _0.__C_data);
}
bool fills_rectangle() {
return _BCD__ZNK4fltk12HighlightBox15fills_rectangleEv(__C_data);
}
bool is_frame() {
return _BCD__ZNK4fltk12HighlightBox8is_frameEv(__C_data);
}
this(char * n, Symbol * d) {
super(cast(ifloat) 0);
__C_data = _BCD_new__ZN4fltk12HighlightBoxC1EPKcPKNS_6SymbolE(n, d.__C_data);
__C_data_owned = true;
}
}
class HighlightBox_R : HighlightBox {
~this() {
if (__C_data && __C_data_owned) _BCD_delete_N4fltk12HighlightBoxE__HighlightBox_R(__C_data);
__C_data = null;
}
this(char * n, Symbol * d) {
super(cast(ifloat) 0);
__C_data = _BCD_new__ZN4fltk12HighlightBoxC1EPKcPKNS_6SymbolE_R(n, d.__C_data);
__C_data_owned = true;
_BCD_RI_N4fltk12HighlightBoxE(__C_data, cast(void *) this);
}
}
class FlatBox : Symbol {
this(ifloat ignore) {
super(ignore);
}
this(ifloat ignore, void *x) {
super(ignore);
__C_data = x;
__C_data_owned = false;
}
~this() {
if (__C_data && __C_data_owned) _BCD_delete_N4fltk7FlatBoxE(__C_data);
__C_data = null;
}
void _draw(Rectangle _0) {
_BCD__ZNK4fltk7FlatBox5_drawERKNS_9RectangleE(__C_data, _0.__C_data);
}
bool fills_rectangle() {
return _BCD__ZNK4fltk7FlatBox15fills_rectangleEv(__C_data);
}
bool is_frame() {
return _BCD__ZNK4fltk7FlatBox8is_frameEv(__C_data);
}
this(char * n) {
super(cast(ifloat) 0);
__C_data = _BCD_new__ZN4fltk7FlatBoxC1EPKc(n);
__C_data_owned = true;
}
}
class FlatBox_R : FlatBox {
~this() {
if (__C_data && __C_data_owned) _BCD_delete_N4fltk7FlatBoxE__FlatBox_R(__C_data);
__C_data = null;
}
this(char * n) {
super(cast(ifloat) 0);
__C_data = _BCD_new__ZN4fltk7FlatBoxC1EPKc_R(n);
__C_data_owned = true;
_BCD_RI_N4fltk7FlatBoxE(__C_data, cast(void *) this);
}
}
class FrameBox : Symbol {
this(ifloat ignore) {
super(ignore);
}
this(ifloat ignore, void *x) {
super(ignore);
__C_data = x;
__C_data_owned = false;
}
~this() {
if (__C_data && __C_data_owned) _BCD_delete_N4fltk8FrameBoxE(__C_data);
__C_data = null;
}
char * data() {
return _BCD__ZNK4fltk8FrameBox4dataEv(__C_data);
}
void data(char * d) {
_BCD__ZN4fltk8FrameBox4dataEPKc(__C_data, d);
}
void _draw(Rectangle _0) {
_BCD__ZNK4fltk8FrameBox5_drawERKNS_9RectangleE(__C_data, _0.__C_data);
}
void inset(Rectangle _0) {
_BCD__ZNK4fltk8FrameBox5insetERNS_9RectangleE(__C_data, _0.__C_data);
}
bool fills_rectangle() {
return _BCD__ZNK4fltk8FrameBox15fills_rectangleEv(__C_data);
}
bool is_frame() {
return _BCD__ZNK4fltk8FrameBox8is_frameEv(__C_data);
}
this(char * name, int dx, int dy, int dw, int dh, char * pattern, Symbol * down = null) {
super(cast(ifloat) 0);
__C_data = _BCD_new__ZN4fltk8FrameBoxC1EPKciiiiS2_PKNS_6SymbolE(name, dx, dy, dw, dh, pattern, down.__C_data);
__C_data_owned = true;
}
}
class FrameBox_R : FrameBox {
~this() {
if (__C_data && __C_data_owned) _BCD_delete_N4fltk8FrameBoxE__FrameBox_R(__C_data);
__C_data = null;
}
this(char * name, int dx, int dy, int dw, int dh, char * pattern, Symbol * down = null) {
super(cast(ifloat) 0);
__C_data = _BCD_new__ZN4fltk8FrameBoxC1EPKciiiiS2_PKNS_6SymbolE_R(name, dx, dy, dw, dh, pattern, down.__C_data);
__C_data_owned = true;
_BCD_RI_N4fltk8FrameBoxE(__C_data, cast(void *) this);
}
}
