/* THIS FILE GENERATED BY bcd.gen */
#include <stdlib.h>
#include <string.h>
#include "../bind.h"
#include "fltk/RadioButton.h"
extern "C" {
typedef unsigned char _BCD__9_uchar;
void _BCD_delete_N4fltk11RadioButtonE(fltk::RadioButton *This) {
delete This;
}
void _BCD_set__ZN4fltk11RadioButton13default_styleE(fltk::RadioButton *This, fltk::NamedStyle * x) {
This->default_style = x;
}
fltk::NamedStyle * _BCD_get__ZN4fltk11RadioButton13default_styleE(fltk::RadioButton *This) {
return This->default_style;
}
fltk::RadioButton *_BCD_new__ZN4fltk11RadioButtonC1EiiiiPKc(int x, int y, int w, int h, char const * l) {
return new fltk::RadioButton(x, y, w, h, l);
}
}
class RadioButton_R : fltk::RadioButton {
public:
void *__D_data;
RadioButton_R(int x, int y, int w, int h, char const * l) : fltk::RadioButton(x, y, w, h, l) {}
};
extern "C" {
RadioButton_R *_BCD_new__ZN4fltk11RadioButtonC1EiiiiPKc_R(int x, int y, int w, int h, char const * l) {
return new RadioButton_R(x, y, w, h, l);
}
void _BCD_delete_N4fltk11RadioButtonE__RadioButton_R(RadioButton_R *This) {
delete This;
}
void _BCD_RI_N4fltk11RadioButtonE(RadioButton_R *cd, void *dd) {
cd->__D_data = dd;
}
typedef void (*_BCD_func__156)(fltk::Widget *, long int);
typedef _BCD_func__156 _BCD__157_Callback1;
typedef void (*_BCD_func__158)(fltk::Widget *);
typedef _BCD_func__158 _BCD__159_Callback0;
typedef void (*_BCD_func__162)(fltk::Widget *, void *);
typedef _BCD_func__162 _BCD__163_Callback;
typedef _BCD__163_Callback _BCD__161_Callback_p;
typedef bool (*_BCD_func__276)();
typedef _BCD_func__276 _BCD__174_Theme;
typedef fltk::Symbol * _BCD__227_Box;
typedef unsigned int _BCD__244_Color;
typedef int _BCD__247_Flags;
typedef _BCD__247_Flags _BCD__246_Align;
}
