/* THIS FILE GENERATED BY bcd.gen */
#include <stdlib.h>
#include <string.h>
#include "../bind.h"
#include "fltk/StyleSet.h"
extern "C" {
typedef unsigned char _BCD__5_uchar;
void _BCD_delete_N4fltk8StyleSetE(fltk::StyleSet *This) {
delete This;
}
fltk::StyleSet *_BCD_new__ZN4fltk8StyleSetC1Ev() {
return new fltk::StyleSet();
}
void _BCD__ZN4fltk8StyleSet12make_currentEv(fltk::StyleSet *This) {
(This->make_current());
}
}
class StyleSet_R : fltk::StyleSet {
public:
void *__D_data;
StyleSet_R() : fltk::StyleSet() {}
};
extern "C" {
StyleSet_R *_BCD_new__ZN4fltk8StyleSetC1Ev_R() {
return new StyleSet_R();
}
void _BCD_delete_N4fltk8StyleSetE__StyleSet_R(StyleSet_R *This) {
delete This;
}
void _BCD_RI_N4fltk8StyleSetE(StyleSet_R *cd, void *dd) {
cd->__D_data = dd;
}
typedef bool (*_BCD_func__237)();
typedef _BCD_func__237 _BCD__152_Theme;
typedef fltk::Symbol * _BCD__205_Box;
typedef unsigned int _BCD__222_Color;
typedef int _BCD__225_Flags;
typedef _BCD__225_Flags _BCD__224_Align;
}
