/* THIS FILE GENERATED BY bcd.gen */
#include <stdlib.h>
#include <string.h>
#include "../bind.h"
#include "fltk/ValueSlider.h"
extern "C" {
typedef unsigned char _BCD__12_uchar;
void _BCD_delete_N4fltk11ValueSliderE(fltk::ValueSlider *This) {
delete This;
}
void _BCD_set__ZN4fltk11ValueSlider5inputE(fltk::ValueSlider *This, fltk::FloatInput * x) {
memcpy(&This->input, x, sizeof(fltk::FloatInput));
}
fltk::FloatInput * _BCD_get__ZN4fltk11ValueSlider5inputE(fltk::ValueSlider *This) {
return &This->input;
}
int _BCD__ZN4fltk11ValueSlider6handleEi(fltk::ValueSlider *This, int _0) {
return (This->handle(_0));
}
void _BCD__ZN4fltk11ValueSlider4drawEv(fltk::ValueSlider *This) {
(This->draw());
}
fltk::ValueSlider *_BCD_new__ZN4fltk11ValueSliderC1EiiiiPKc(int x, int y, int w, int h, char const * l) {
return new fltk::ValueSlider(x, y, w, h, l);
}
void _BCD__ZN4fltk11ValueSlider6layoutEv(fltk::ValueSlider *This) {
(This->layout());
}
void _BCD__ZN4fltk11ValueSlider12value_damageEv(fltk::ValueSlider *This) {
(This->value_damage());
}
int _BCD_R__ZN4fltk11ValueSlider6handleEi__ValueSlider_R_CHECK(void *);
int _BCD_R__ZN4fltk11ValueSlider6handleEi__ValueSlider_R(void *, int _0);
int _BCD_R__ZN4fltk11ValueSlider4drawEv__ValueSlider_R_CHECK(void *);
void _BCD_R__ZN4fltk11ValueSlider4drawEv__ValueSlider_R(void *);
int _BCD_R__ZN4fltk11ValueSlider6layoutEv__ValueSlider_R_CHECK(void *);
void _BCD_R__ZN4fltk11ValueSlider6layoutEv__ValueSlider_R(void *);
int _BCD_R__ZN4fltk11ValueSlider12value_damageEv__ValueSlider_R_CHECK(void *);
void _BCD_R__ZN4fltk11ValueSlider12value_damageEv__ValueSlider_R(void *);
}
class ValueSlider_R : fltk::ValueSlider {
public:
void *__D_data;
int handle(int _0) {
if (_BCD_R__ZN4fltk11ValueSlider6handleEi__ValueSlider_R_CHECK(__D_data))
return _BCD_R__ZN4fltk11ValueSlider6handleEi__ValueSlider_R(__D_data, _0);
else
return fltk::ValueSlider::handle(_0);
}
void draw() {
if (_BCD_R__ZN4fltk11ValueSlider4drawEv__ValueSlider_R_CHECK(__D_data))
_BCD_R__ZN4fltk11ValueSlider4drawEv__ValueSlider_R(__D_data);
else
fltk::ValueSlider::draw();
}
ValueSlider_R(int x, int y, int w, int h, char const * l) : fltk::ValueSlider(x, y, w, h, l) {}
void layout() {
if (_BCD_R__ZN4fltk11ValueSlider6layoutEv__ValueSlider_R_CHECK(__D_data))
_BCD_R__ZN4fltk11ValueSlider6layoutEv__ValueSlider_R(__D_data);
else
fltk::ValueSlider::layout();
}
void value_damage() {
if (_BCD_R__ZN4fltk11ValueSlider12value_damageEv__ValueSlider_R_CHECK(__D_data))
_BCD_R__ZN4fltk11ValueSlider12value_damageEv__ValueSlider_R(__D_data);
else
fltk::ValueSlider::value_damage();
}
};
extern "C" {
ValueSlider_R *_BCD_new__ZN4fltk11ValueSliderC1EiiiiPKc_R(int x, int y, int w, int h, char const * l) {
return new ValueSlider_R(x, y, w, h, l);
}
void _BCD_delete_N4fltk11ValueSliderE__ValueSlider_R(ValueSlider_R *This) {
delete This;
}
void _BCD_RI_N4fltk11ValueSliderE(ValueSlider_R *cd, void *dd) {
cd->__D_data = dd;
}
typedef void (*_BCD_func__162)(fltk::Widget *, long int);
typedef _BCD_func__162 _BCD__163_Callback1;
typedef void (*_BCD_func__164)(fltk::Widget *);
typedef _BCD_func__164 _BCD__165_Callback0;
typedef void (*_BCD_func__168)(fltk::Widget *, void *);
typedef _BCD_func__168 _BCD__169_Callback;
typedef _BCD__169_Callback _BCD__167_Callback_p;
typedef bool (*_BCD_func__399)();
typedef _BCD_func__399 _BCD__180_Theme;
typedef fltk::Symbol * _BCD__233_Box;
typedef unsigned int _BCD__250_Color;
typedef int _BCD__253_Flags;
typedef _BCD__253_Flags _BCD__252_Align;
}
