/* THIS FILE GENERATED BY bcd.gen */
module bcd.fltk.Fl_Check_Browser;
public import bcd.bind;
public import bcd.fltk.Fl_Browser_;
public import bcd.fltk.Fl_Scrollbar;
public import bcd.fltk.Fl_Slider;
public import bcd.fltk.Fl_Valuator;
public import bcd.fltk.Fl_Group;
public import bcd.fltk.Fl_Widget;
public import bcd.fltk.Fl;
public import bcd.fltk.Enumerations;
extern (C) void _BCD_delete_N16Fl_Check_Browser7cb_itemE(void *);
extern (C) void _BCD_set__ZN16Fl_Check_Browser7cb_item4nextE(void *, cb_item *);
extern (C) cb_item * _BCD_get__ZN16Fl_Check_Browser7cb_item4nextE(void *);
extern (C) void _BCD_set__ZN16Fl_Check_Browser7cb_item4prevE(void *, cb_item *);
extern (C) cb_item * _BCD_get__ZN16Fl_Check_Browser7cb_item4prevE(void *);
extern (C) void _BCD_set__ZN16Fl_Check_Browser7cb_item7checkedE(void *, char);
extern (C) char _BCD_get__ZN16Fl_Check_Browser7cb_item7checkedE(void *);
extern (C) void _BCD_set__ZN16Fl_Check_Browser7cb_item8selectedE(void *, char);
extern (C) char _BCD_get__ZN16Fl_Check_Browser7cb_item8selectedE(void *);
extern (C) void _BCD_set__ZN16Fl_Check_Browser7cb_item4textE(void *, char *);
extern (C) char * _BCD_get__ZN16Fl_Check_Browser7cb_item4textE(void *);
extern (C) void _BCD_RI_N16Fl_Check_Browser7cb_itemE(void *cd, void *dd);
extern (C) void _BCD_delete_N16Fl_Check_Browser7cb_itemE__cb_item_R(void *This);
extern (C) void _BCD_delete_16Fl_Check_Browser(void *);
extern (C) void *_BCD_new__ZN16Fl_Check_BrowserC1EiiiiPKc(int, int, int, int, char *);
extern (C) int _BCD__ZN16Fl_Check_Browser3addEPc(void *This, char *);
extern (C) int _BCD__ZN16Fl_Check_Browser3addEPci(void *This, char *, int);
extern (C) void _BCD__ZN16Fl_Check_Browser5clearEv(void *This);
extern (C) int _BCD__ZNK16Fl_Check_Browser6nitemsEv(void *This);
extern (C) int _BCD__ZNK16Fl_Check_Browser8ncheckedEv(void *This);
extern (C) int _BCD__ZNK16Fl_Check_Browser7checkedEi(void *This, int);
extern (C) void _BCD__ZN16Fl_Check_Browser7checkedEii(void *This, int, int);
extern (C) void _BCD__ZN16Fl_Check_Browser11set_checkedEi(void *This, int);
extern (C) void _BCD__ZN16Fl_Check_Browser9check_allEv(void *This);
extern (C) void _BCD__ZN16Fl_Check_Browser10check_noneEv(void *This);
extern (C) int _BCD__ZNK16Fl_Check_Browser5valueEv(void *This);
extern (C) char * _BCD__ZNK16Fl_Check_Browser4textEi(void *This, int);
extern (C) void _BCD_RI_16Fl_Check_Browser(void *cd, void *dd);
extern (C) void _BCD_delete_16Fl_Check_Browser__Fl_Check_Browser_R(void *This);
extern (C) void *_BCD_new__ZN16Fl_Check_BrowserC1EiiiiPKc_R(int, int, int, int, char *);
alias void function(Fl_Widget *, int) _BCD_func__16;
alias void function(Fl_Widget *) _BCD_func__18;
alias void function(Fl_Widget *, void *) _BCD_func__22;
alias void function(void *) _BCD_func__587;
alias void function(int, int, int, int, int) _BCD_func__28;
alias void function(Fl_Label *, int *, int *) _BCD_func__30;
alias void function(Fl_Label *, int, int, int, int, int) _BCD_func__32;
class cb_item : bcd.bind.BoundClass {
this(ifloat ignore) {
super(ignore);
}
this(ifloat ignore, void *x) {
super(ignore);
__C_data = x;
__C_data_owned = false;
}
~this() {
if (__C_data && __C_data_owned) _BCD_delete_N16Fl_Check_Browser7cb_itemE(__C_data);
__C_data = null;
}
void set_next(cb_item * x) {
_BCD_set__ZN16Fl_Check_Browser7cb_item4nextE(__C_data, x);
}
cb_item * get_next() {
return _BCD_get__ZN16Fl_Check_Browser7cb_item4nextE(__C_data);
}
void set_prev(cb_item * x) {
_BCD_set__ZN16Fl_Check_Browser7cb_item4prevE(__C_data, x);
}
cb_item * get_prev() {
return _BCD_get__ZN16Fl_Check_Browser7cb_item4prevE(__C_data);
}
void set_checked(char x) {
_BCD_set__ZN16Fl_Check_Browser7cb_item7checkedE(__C_data, x);
}
char get_checked() {
return _BCD_get__ZN16Fl_Check_Browser7cb_item7checkedE(__C_data);
}
void set_selected(char x) {
_BCD_set__ZN16Fl_Check_Browser7cb_item8selectedE(__C_data, x);
}
char get_selected() {
return _BCD_get__ZN16Fl_Check_Browser7cb_item8selectedE(__C_data);
}
void set_text(char * x) {
_BCD_set__ZN16Fl_Check_Browser7cb_item4textE(__C_data, x);
}
char * get_text() {
return _BCD_get__ZN16Fl_Check_Browser7cb_item4textE(__C_data);
}
}
class cb_item_R : cb_item {
~this() {
if (__C_data && __C_data_owned) _BCD_delete_N16Fl_Check_Browser7cb_itemE__cb_item_R(__C_data);
__C_data = null;
}
this() { super(cast(ireal) 0); }
}
class Fl_Check_Browser : Fl_Browser_ {
this(ifloat ignore) {
super(ignore);
}
this(ifloat ignore, void *x) {
super(ignore);
__C_data = x;
__C_data_owned = false;
}
~this() {
if (__C_data && __C_data_owned) _BCD_delete_16Fl_Check_Browser(__C_data);
__C_data = null;
}
this(int x, int y, int w, int h, char * l) {
super(cast(ifloat) 0);
__C_data = _BCD_new__ZN16Fl_Check_BrowserC1EiiiiPKc(x, y, w, h, l);
__C_data_owned = true;
}
int add(char * s) {
return _BCD__ZN16Fl_Check_Browser3addEPc(__C_data, s);
}
int add(char * s, int b) {
return _BCD__ZN16Fl_Check_Browser3addEPci(__C_data, s, b);
}
void clear() {
_BCD__ZN16Fl_Check_Browser5clearEv(__C_data);
}
int nitems() {
return _BCD__ZNK16Fl_Check_Browser6nitemsEv(__C_data);
}
int nchecked() {
return _BCD__ZNK16Fl_Check_Browser8ncheckedEv(__C_data);
}
int checked(int item) {
return _BCD__ZNK16Fl_Check_Browser7checkedEi(__C_data, item);
}
void checked(int item, int b) {
_BCD__ZN16Fl_Check_Browser7checkedEii(__C_data, item, b);
}
void set_checked(int item) {
_BCD__ZN16Fl_Check_Browser11set_checkedEi(__C_data, item);
}
void check_all() {
_BCD__ZN16Fl_Check_Browser9check_allEv(__C_data);
}
void check_none() {
_BCD__ZN16Fl_Check_Browser10check_noneEv(__C_data);
}
int value() {
return _BCD__ZNK16Fl_Check_Browser5valueEv(__C_data);
}
char * text(int item) {
return _BCD__ZNK16Fl_Check_Browser4textEi(__C_data, item);
}
}
class Fl_Check_Browser_R : Fl_Check_Browser {
~this() {
if (__C_data && __C_data_owned) _BCD_delete_16Fl_Check_Browser__Fl_Check_Browser_R(__C_data);
__C_data = null;
}
this(int x, int y, int w, int h, char * l) {
super(cast(ifloat) 0);
__C_data = _BCD_new__ZN16Fl_Check_BrowserC1EiiiiPKc_R(x, y, w, h, l);
__C_data_owned = true;
_BCD_RI_16Fl_Check_Browser(__C_data, cast(void *) this);
}
}
