/* THIS FILE GENERATED BY bcd.gen */
#include <stdlib.h>
#include <string.h>
#include "../bind.h"
#include "FL/Fl_Menu_Bar.H"
extern "C" {
void _BCD_delete_11Fl_Menu_Bar(Fl_Menu_Bar *This) {
delete This;
}
int _BCD__ZN11Fl_Menu_Bar6handleEi(Fl_Menu_Bar *This, int _0) {
return (This->handle(_0));
}
Fl_Menu_Bar *_BCD_new__ZN11Fl_Menu_BarC1EiiiiPKc(int X, int Y, int W, int H, char const * l) {
return new Fl_Menu_Bar(X, Y, W, H, l);
}
int _BCD_R__ZN11Fl_Menu_Bar6handleEi__Fl_Menu_Bar_R_CHECK(void *);
int _BCD_R__ZN11Fl_Menu_Bar6handleEi__Fl_Menu_Bar_R(void *, int _0);
}
class Fl_Menu_Bar_R : Fl_Menu_Bar {
public:
void *__D_data;
int handle(int _0) {
if (_BCD_R__ZN11Fl_Menu_Bar6handleEi__Fl_Menu_Bar_R_CHECK(__D_data))
return _BCD_R__ZN11Fl_Menu_Bar6handleEi__Fl_Menu_Bar_R(__D_data, _0);
else
return Fl_Menu_Bar::handle(_0);
}
Fl_Menu_Bar_R(int X, int Y, int W, int H, char const * l) : Fl_Menu_Bar(X, Y, W, H, l) {}
};
extern "C" {
Fl_Menu_Bar_R *_BCD_new__ZN11Fl_Menu_BarC1EiiiiPKc_R(int X, int Y, int W, int H, char const * l) {
return new Fl_Menu_Bar_R(X, Y, W, H, l);
}
void _BCD_delete_11Fl_Menu_Bar__Fl_Menu_Bar_R(Fl_Menu_Bar_R *This) {
delete This;
}
void _BCD_RI_11Fl_Menu_Bar(Fl_Menu_Bar_R *cd, void *dd) {
cd->__D_data = dd;
}
typedef Fl_Menu_Item * _BCD__8_Fl_Menu;
typedef void (*_BCD_func__17)(Fl_Widget *, long int);
typedef _BCD_func__17 _BCD__18_Fl_Callback1;
typedef void (*_BCD_func__19)(Fl_Widget *);
typedef _BCD_func__19 _BCD__20_Fl_Callback0;
typedef void (*_BCD_func__23)(Fl_Widget *, void *);
typedef _BCD_func__23 _BCD__24_Fl_Callback;
typedef _BCD__24_Fl_Callback _BCD__22_Fl_Callback_p;
typedef long unsigned int _BCD__64_ulong;
typedef unsigned char _BCD__66_uchar;
}
