/* THIS FILE GENERATED BY bcd.gen */
#include <stdlib.h>
#include <string.h>
#include "../bind.h"
#include "FL/Fl_Output.H"
extern "C" {
void _BCD_delete_9Fl_Output(Fl_Output *This) {
delete This;
}
Fl_Output *_BCD_new__ZN9Fl_OutputC1EiiiiPKc(int X, int Y, int W, int H, char const * l) {
return new Fl_Output(X, Y, W, H, l);
}
}
class Fl_Output_R : Fl_Output {
public:
void *__D_data;
Fl_Output_R(int X, int Y, int W, int H, char const * l) : Fl_Output(X, Y, W, H, l) {}
};
extern "C" {
Fl_Output_R *_BCD_new__ZN9Fl_OutputC1EiiiiPKc_R(int X, int Y, int W, int H, char const * l) {
return new Fl_Output_R(X, Y, W, H, l);
}
void _BCD_delete_9Fl_Output__Fl_Output_R(Fl_Output_R *This) {
delete This;
}
void _BCD_RI_9Fl_Output(Fl_Output_R *cd, void *dd) {
cd->__D_data = dd;
}
typedef void (*_BCD_func__11)(Fl_Widget *, long int);
typedef _BCD_func__11 _BCD__12_Fl_Callback1;
typedef void (*_BCD_func__13)(Fl_Widget *);
typedef _BCD_func__13 _BCD__14_Fl_Callback0;
typedef void (*_BCD_func__17)(Fl_Widget *, void *);
typedef _BCD_func__17 _BCD__18_Fl_Callback;
typedef _BCD__18_Fl_Callback _BCD__16_Fl_Callback_p;
typedef long unsigned int _BCD__58_ulong;
typedef unsigned char _BCD__60_uchar;
}
