/* THIS FILE GENERATED BY bcd.gen */
#include <stdlib.h>
#include <string.h>
#include "../bind.h"
#include "FL/Fl_Slider.H"
extern "C" {
void _BCD_delete_9Fl_Slider(Fl_Slider *This) {
delete This;
}
void _BCD__ZN9Fl_Slider4drawEv(Fl_Slider *This) {
(This->draw());
}
int _BCD__ZN9Fl_Slider6handleEi(Fl_Slider *This, int _0) {
return (This->handle(_0));
}
Fl_Slider *_BCD_new__ZN9Fl_SliderC1EiiiiPKc(int x, int y, int w, int h, char const * l) {
return new Fl_Slider(x, y, w, h, l);
}
typedef unsigned char _BCD__58_uchar;
Fl_Slider *_BCD_new__ZN9Fl_SliderC1EhiiiiPKc(_BCD__58_uchar t, int x, int y, int w, int h, char const * l) {
return new Fl_Slider(t, x, y, w, h, l);
}
int _BCD__ZN9Fl_Slider11scrollvalueEiiii(Fl_Slider *This, int windowtop, int windowsize, int first, int totalsize) {
return (This->scrollvalue(windowtop, windowsize, first, totalsize));
}
void _BCD__ZN9Fl_Slider6boundsEdd(Fl_Slider *This, double a, double b) {
(This->bounds(a, b));
}
float _BCD__ZNK9Fl_Slider11slider_sizeEv(Fl_Slider *This) {
return (This->slider_size());
}
void _BCD__ZN9Fl_Slider11slider_sizeEd(Fl_Slider *This, double v) {
(This->slider_size(v));
}
enum Fl_Boxtype _BCD__ZNK9Fl_Slider6sliderEv(Fl_Slider *This) {
return (This->slider());
}
void _BCD__ZN9Fl_Slider6sliderE10Fl_Boxtype(Fl_Slider *This, enum Fl_Boxtype c) {
(This->slider(c));
}
int _BCD_R__ZN9Fl_Slider4drawEv__Fl_Slider_R_CHECK(void *);
void _BCD_R__ZN9Fl_Slider4drawEv__Fl_Slider_R(void *);
int _BCD_R__ZN9Fl_Slider6handleEi__Fl_Slider_R_CHECK(void *);
int _BCD_R__ZN9Fl_Slider6handleEi__Fl_Slider_R(void *, int _0);
}
class Fl_Slider_R : Fl_Slider {
public:
void *__D_data;
void draw() {
if (_BCD_R__ZN9Fl_Slider4drawEv__Fl_Slider_R_CHECK(__D_data))
_BCD_R__ZN9Fl_Slider4drawEv__Fl_Slider_R(__D_data);
else
Fl_Slider::draw();
}
int handle(int _0) {
if (_BCD_R__ZN9Fl_Slider6handleEi__Fl_Slider_R_CHECK(__D_data))
return _BCD_R__ZN9Fl_Slider6handleEi__Fl_Slider_R(__D_data, _0);
else
return Fl_Slider::handle(_0);
}
Fl_Slider_R(int x, int y, int w, int h, char const * l) : Fl_Slider(x, y, w, h, l) {}
Fl_Slider_R(_BCD__58_uchar t, int x, int y, int w, int h, char const * l) : Fl_Slider(t, x, y, w, h, l) {}
};
extern "C" {
Fl_Slider_R *_BCD_new__ZN9Fl_SliderC1EiiiiPKc_R(int x, int y, int w, int h, char const * l) {
return new Fl_Slider_R(x, y, w, h, l);
}
Fl_Slider_R *_BCD_new__ZN9Fl_SliderC1EhiiiiPKc_R(_BCD__58_uchar t, int x, int y, int w, int h, char const * l) {
return new Fl_Slider_R(t, x, y, w, h, l);
}
void _BCD_delete_9Fl_Slider__Fl_Slider_R(Fl_Slider_R *This) {
delete This;
}
void _BCD_RI_9Fl_Slider(Fl_Slider_R *cd, void *dd) {
cd->__D_data = dd;
}
typedef void (*_BCD_func__9)(Fl_Widget *, long int);
typedef _BCD_func__9 _BCD__10_Fl_Callback1;
typedef void (*_BCD_func__11)(Fl_Widget *);
typedef _BCD_func__11 _BCD__12_Fl_Callback0;
typedef void (*_BCD_func__15)(Fl_Widget *, void *);
typedef _BCD_func__15 _BCD__16_Fl_Callback;
typedef _BCD__16_Fl_Callback _BCD__14_Fl_Callback_p;
typedef long unsigned int _BCD__56_ulong;
}
