/* THIS FILE GENERATED BY bcd.gen */
module bcd.glib2.gmodule;
import bcd.glib2.glib_object;
align(4):
alias void GModule;
alias void function(void *) _BCD_func__1302;
alias _BCD_func__1302 GModuleUnload;
alias char * function(void *) _BCD_func__1303;
alias _BCD_func__1303 GModuleCheckInit;
enum GModuleFlags {
G_MODULE_BIND_LAZY=1,
G_MODULE_BIND_LOCAL=2,
G_MODULE_BIND_MASK=3,
}
extern (C) char * g_module_build_path(char *, char *);
extern (C) char * g_module_name(void *);
extern (C) int g_module_symbol(void *, char *, void * *);
extern (C) char * g_module_error();
extern (C) void g_module_make_resident(void *);
extern (C) int g_module_close(void *);
extern (C) void * g_module_open(char *, int);
extern (C) int g_module_supported();
alias int function(void *, void *, void *) _BCD_func__1305;
alias void function(void *) _BCD_func__1322;
alias void function(_GScanner *, char *, int) _BCD_func__1326;
alias void function(void *, void *, void *, _GError * *) _BCD_func__1411;
alias int function(void *, void *, void *, _GError * *) _BCD_func__1412;
alias int function(char *, char *, void *, _GError * *) _BCD_func__1413;
alias void * function(void *, void *) _BCD_func__1425;
alias void function(_GNode *, void *) _BCD_func__1426;
alias int function(_GNode *, void *) _BCD_func__1427;
alias void function(char *) _BCD_func__1435;
alias void function(char *, int, char *, void *) _BCD_func__1437;
alias int function(_GIOChannel *, int, void *) _BCD_func__1456;
alias void function() _BCD_func__1501;
alias int function(_GPollFD *, uint, int) _BCD_func__1522;
alias void function(int, int, void *) _BCD_func__1528;
alias int function(void *) _BCD_func__1529;
alias void function(_GHookList *, _GHook *) _BCD_func__1565;
alias int function(_GHook *, void *) _BCD_func__1566;
alias void function(_GHook *, void *) _BCD_func__1567;
alias int function(_GHook *, _GHook *) _BCD_func__1568;
alias void function(uint, void *, void *) _BCD_func__1602;
alias int function(char *, char *, uint) _BCD_func__1605;
alias char * function(void *) _BCD_func__1606;
alias void * function(void *) _BCD_func__1615;
alias char * function(char *, void *) _BCD_func__1728;
alias void function(void *, void *, void *) _BCD_func__1729;
alias uint function(void *) _BCD_func__1730;
alias void function(void *, void *) _BCD_func__1731;
alias int function(void *, void *) _BCD_func__1732;
alias int function(void *, void *, void *) _BCD_func__1733;
alias int function(void *, void *) _BCD_func__1734;
